import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Car, CheckCircle2, Clock3, Luggage, MapPin, Plane, ShieldCheck, Users } from "lucide-react";
import { getAirportTransfer } from "../api/airportTransferApi";

const money = (value, currency = "KES") => `${currency} ${Number(value || 0).toLocaleString("en-KE", { maximumFractionDigits: 2 })}`;

export default function AirportTransferDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const reservationPath = `/airport-transfers/${id}/reserve`;
  const { data: item, isLoading, isError } = useQuery({ queryKey: ["airport-transfer", id], queryFn: () => getAirportTransfer(id), enabled: !!id, staleTime: 30000 });

  const openReservation = () => {
    if (id) navigate(reservationPath);
  };

  if (isLoading) return <main className="min-h-screen bg-slate-50 px-5 py-16"><div className="mx-auto max-w-6xl animate-pulse space-y-6"><div className="h-72 rounded-3xl bg-slate-200"/><div className="h-12 w-1/2 rounded bg-slate-200"/><div className="h-32 rounded-3xl bg-slate-200"/></div></main>;
  if (isError || !item) return <main className="min-h-screen bg-slate-50 px-5 py-20"><div className="mx-auto max-w-xl rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-slate-200"><Plane className="mx-auto text-slate-300" size={52}/><h1 className="mt-5 text-2xl font-black">Transfer service not available</h1><p className="mt-2 text-sm leading-6 text-slate-500">This transfer may have been removed or is temporarily unavailable.</p><Link to="/airport-transfers" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Back to transfers</Link></div></main>;

  return <main className="min-h-screen bg-slate-50">
    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-5 md:px-8"><Link to="/airport-transfers" className="inline-flex items-center gap-2 text-sm font-bold text-slate-300 hover:text-white"><ArrowLeft size={17}/> Back to airport transfers</Link></div></section>
    <section className="mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-12"><div className="overflow-hidden rounded-[2rem] bg-white shadow-sm ring-1 ring-slate-200"><div className="bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-8 text-white md:p-12"><div className="flex flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><span className="inline-flex rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-black uppercase tracking-[.16em] text-emerald-300">{item.airportCode || "Airport"} · Flight-aware service</span><h1 className="mt-5 text-3xl font-black tracking-tight md:text-5xl">{item.name}</h1><p className="mt-3 flex items-center gap-2 text-slate-300"><MapPin size={17} className="text-emerald-300"/>{item.pickupLocation} <span>→</span> {item.dropoffLocation}</p><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">{item.description || "Pre-book a reliable airport transfer with your flight, passenger and luggage information captured for the operations team."}</p></div><div className="flex h-28 w-28 shrink-0 items-center justify-center rounded-3xl bg-white/10 text-emerald-300 backdrop-blur"><Car size={58}/></div></div></div><div className="grid gap-px bg-slate-200 md:grid-cols-4"><Stat icon={<Users/>} label="Passengers" value={`Up to ${item.passengerCapacity || 1}`}/><Stat icon={<Luggage/>} label="Luggage" value={`${item.luggageCapacity || 0} bags`}/><Stat icon={<Clock3/>} label="Duration" value={item.durationMinutes ? `${item.durationMinutes} min` : "Scheduled"}/><Stat icon={<Car/>} label="Vehicle" value={item.vehicleType || "Private vehicle"}/></div></div></section>
    <section className="mx-auto max-w-7xl px-5 pb-16 md:px-8"><div className="grid gap-7 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-black uppercase tracking-wider text-emerald-700">Service information</p><h2 className="mt-1 text-3xl font-black text-slate-950">A smoother arrival in Kenya</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><Info label="Airport" value={item.airportName || item.airportCode || "Regional airport"}/><Info label="Operating hours" value={item.operatingHours || "24/7"}/><Info label="Route" value={`${item.pickupLocation} → ${item.dropoffLocation}`}/><Info label="Price" value={`${money(item.price, item.currency || "KES")} ${item.pricingModel === "per_passenger" ? "per passenger" : "per vehicle"}`}/></div><div className="mt-7 rounded-2xl bg-emerald-50 p-5"><h3 className="font-black text-emerald-950">What to provide when booking</h3><div className="mt-3 grid gap-2 text-sm text-emerald-900 sm:grid-cols-2"><span>✓ Arrival/departure date & time</span><span>✓ Passenger phone number</span><span>✓ Flight number and airline</span><span>✓ Terminal and luggage count</span><span>✓ Pickup and hotel/drop-off location</span><span>✓ Special assistance requests</span></div></div></div><aside className="space-y-4"><div className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-black uppercase tracking-wider text-emerald-300">Transparent Kenya pricing</p><p className="mt-2 text-3xl font-black">{money(item.price, item.currency || "KES")}</p><p className="mt-1 text-sm text-slate-400">{item.pricingModel === "per_passenger" ? "per passenger" : "per vehicle"}</p><button type="button" onClick={openReservation} disabled={!id} className="mt-6 flex w-full justify-center rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-50">Choose service & book</button></div><div className="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-600"/><div><p className="font-black text-slate-950">Operations-ready</p><p className="text-xs text-slate-500">Flight, terminal, passenger and luggage details flow into the reservation.</p></div></div><div className="mt-5 space-y-3 text-sm text-slate-600"><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/> Confirmation handled by the operations team</p><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/> KES pricing displayed clearly</p><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/> Suitable for JKIA and regional airport workflows</p></div></div></aside></div></section>
  </main>;
}

function Stat({ icon, label, value }) { return <div className="bg-white p-5"><div className="flex items-center gap-2 text-emerald-600">{icon}</div><p className="mt-2 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-900">{value}</p></div>; }
function Info({ label, value }) { return <div className="rounded-2xl bg-slate-50 p-5"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-sm font-black text-slate-900">{value}</p></div>; }
