import { useState } from "react";
import { Link, useNavigate, useSearchParams, useParams } from "react-router-dom";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, Car, CheckCircle2, Clock3, Luggage, MapPin, Plane, ShieldCheck, Users } from "lucide-react";
import { createTransferBooking, getAirportTransfer } from "../api/airportTransferApi";

const input = "mt-1 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-slate-900 outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";
const money = (value, currency = "KES") => `${currency} ${Number(value || 0).toLocaleString("en-KE", { maximumFractionDigits: 2 })}`;

export default function AirportTransferReservation() {
  const { id } = useParams();
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const { data: item, isLoading, isError } = useQuery({ queryKey: ["airport-transfer-reservation", id], queryFn: () => getAirportTransfer(id), enabled: !!id, staleTime: 30000 });
  const [form, setForm] = useState({ pickupDateTime: "", pickupLocation: "", dropoffLocation: "", passengerName: "", passengerPhone: "", passengerEmail: "", passengers: 1, luggage: 0, flightNumber: "", airline: "", terminal: "", specialRequests: "" });
  const update = (key, value) => setForm(f => ({ ...f, [key]: value }));
  const booking = useMutation({ mutationFn: createTransferBooking, onSuccess: result => { const bookingId = result?._id || result?.id; if (bookingId) navigate(`/hospitality-payment/${bookingId}?type=airport_transfer`); }, onError: error => window.alert(error?.response?.data?.message || "Unable to create the transfer reservation. Please check your details and try again.") });
  const total = item ? (item.pricingModel === "per_passenger" ? Number(item.price || 0) * Number(form.passengers || 1) : Number(item.price || 0)) : 0;
  const valid = item && form.pickupDateTime && form.passengerName.trim() && form.passengerPhone.trim() && form.pickupLocation.trim() && form.dropoffLocation.trim() && Number(form.passengers) >= 1 && Number(form.passengers) <= Number(item.passengerCapacity || 1) && Number(form.luggage) >= 0 && Number(form.luggage) <= Number(item.luggageCapacity || 0);

  if (isLoading) return <main className="min-h-screen bg-slate-50 px-5 py-16"><div className="mx-auto max-w-5xl animate-pulse space-y-6"><div className="h-32 rounded-3xl bg-slate-200"/><div className="h-96 rounded-3xl bg-slate-200"/></div></main>;
  if (isError || !item) return <main className="min-h-screen bg-slate-50 px-5 py-20"><div className="mx-auto max-w-xl rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-slate-200"><Plane className="mx-auto text-slate-300" size={52}/><h1 className="mt-5 text-2xl font-black text-slate-900">Transfer service not available</h1><p className="mt-2 text-sm leading-6 text-slate-500">This service may have been removed or is temporarily unavailable.</p><Link to="/airport-transfers" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Back to transfers</Link></div></main>;

  return <main className="min-h-screen bg-slate-50">
    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-5 md:px-8"><Link to={`/airport-transfers/${id}`} className="inline-flex items-center gap-2 text-sm font-bold text-slate-300 hover:text-white"><ArrowLeft size={17}/> Back to service</Link></div></section>
    <section className="mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-12"><div className="grid gap-7 lg:grid-cols-[1fr_360px]">
      <div className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200">
        <div className="bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 p-7 text-white md:p-9"><div className="flex items-start gap-4"><div className="rounded-2xl bg-white/10 p-3 text-emerald-300"><Car size={28}/></div><div><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-300">Airport transfer reservation</p><h1 className="mt-1 text-2xl font-black md:text-3xl">{item.name}</h1><p className="mt-2 flex items-center gap-2 text-sm text-slate-300"><MapPin size={15}/>{item.pickupLocation} → {item.dropoffLocation}</p></div></div></div>
        <div className="grid gap-3 bg-slate-100 p-4 sm:grid-cols-3"><Summary icon={<Users/>} label="Capacity" value={`Up to ${item.passengerCapacity || 1} passengers`}/><Summary icon={<Luggage/>} label="Luggage" value={`${item.luggageCapacity || 0} bags`}/><Summary icon={<Clock3/>} label="Duration" value={item.durationMinutes ? `${item.durationMinutes} min` : "Scheduled"}/></div>
        <form className="p-6 md:p-8" onSubmit={e => { e.preventDefault(); if (!valid || booking.isPending) return; booking.mutate({ transferId: item._id, pickupDateTime: form.pickupDateTime, pickupLocation: form.pickupLocation, dropoffLocation: form.dropoffLocation, passengerName: form.passengerName.trim(), passengerPhone: form.passengerPhone.trim(), passengerEmail: form.passengerEmail.trim(), passengers: Number(form.passengers), luggage: Number(form.luggage), flightNumber: form.flightNumber.trim(), airline: form.airline.trim(), terminal: form.terminal.trim(), specialRequests: form.specialRequests.trim() }); }}>
          <div className="mb-6"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Reservation details</p><h2 className="mt-1 text-2xl font-black text-slate-950">Tell us about your journey</h2><p className="mt-2 text-sm leading-6 text-slate-500">Your flight and passenger information is sent to the operations team so the driver can be prepared before pickup.</p></div>
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Pickup / arrival date & time *"><input className={input} type="datetime-local" value={form.pickupDateTime} onChange={e => update("pickupDateTime", e.target.value)} required /></Field>
            <Field label="Passenger name *"><input className={input} value={form.passengerName} onChange={e => update("passengerName", e.target.value)} required autoComplete="name" /></Field>
            <Field label="Pickup location *"><input className={input} value={form.pickupLocation} onChange={e => update("pickupLocation", e.target.value)} required /></Field>
            <Field label="Drop-off / hotel *"><input className={input} value={form.dropoffLocation} onChange={e => update("dropoffLocation", e.target.value)} required /></Field>
            <Field label="Phone *"><input className={input} inputMode="tel" placeholder="07xx xxx xxx" value={form.passengerPhone} onChange={e => update("passengerPhone", e.target.value)} required autoComplete="tel" /></Field>
            <Field label="Email"><input className={input} type="email" value={form.passengerEmail} onChange={e => update("passengerEmail", e.target.value)} autoComplete="email" /></Field>
            <Field label="Passengers"><input className={input} type="number" min="1" max={item.passengerCapacity || 1} value={form.passengers} onChange={e => update("passengers", Math.max(1, Number(e.target.value) || 1))} /></Field>
            <Field label="Luggage"><input className={input} type="number" min="0" max={item.luggageCapacity || 0} value={form.luggage} onChange={e => update("luggage", Math.max(0, Number(e.target.value) || 0))} /></Field>
            <Field label="Flight number"><input className={input} placeholder="e.g. KQ 501" value={form.flightNumber} onChange={e => update("flightNumber", e.target.value)} /></Field>
            <Field label="Airline"><input className={input} placeholder="e.g. Kenya Airways" value={form.airline} onChange={e => update("airline", e.target.value)} /></Field>
            <Field label="Terminal"><input className={input} placeholder="e.g. 1A" value={form.terminal} onChange={e => update("terminal", e.target.value)} /></Field>
            <Field label="Special requests"><textarea className={`${input} min-h-24`} placeholder="Child seat, meet-and-greet, mobility assistance, hotel gate instructions, etc." value={form.specialRequests} onChange={e => update("specialRequests", e.target.value)} /></Field>
          </div>
          <div className="mt-7 rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-emerald-600"/><div><p className="font-black text-emerald-950">Secure, operations-ready booking</p><p className="mt-1 text-xs leading-5 text-emerald-900">Capacity and service details are validated before the reservation is created. Payment continues through the protected hospitality payment flow.</p></div></div></div>
          <div className="mt-7 flex flex-col gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:items-center sm:justify-between"><Link to={`/airport-transfers/${id}`} className="text-sm font-bold text-slate-600 hover:text-slate-950">Review service</Link><button type="submit" disabled={!valid || booking.isPending} className="rounded-xl bg-emerald-600 px-6 py-3.5 text-sm font-black text-white shadow-lg shadow-emerald-600/20 transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-50">{booking.isPending ? "Creating reservation…" : `Continue to payment · ${money(total, item.currency || "KES")}`}</button></div>
        </form>
      </div>
      <aside className="h-fit space-y-4 lg:sticky lg:top-6"><div className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-black uppercase tracking-wider text-emerald-300">Reservation summary</p><h2 className="mt-2 text-xl font-black">{item.name}</h2><div className="mt-5 space-y-3 text-sm text-slate-300"><p className="flex gap-2"><MapPin className="shrink-0 text-emerald-400" size={17}/>{item.pickupLocation} → {item.dropoffLocation}</p><p className="flex gap-2"><Car className="shrink-0 text-emerald-400" size={17}/>{item.vehicleType || "Private vehicle"}</p><p className="flex gap-2"><Clock3 className="shrink-0 text-emerald-400" size={17}/>{item.operatingHours || "24/7"}</p></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs text-slate-400">Estimated total</p><p className="mt-1 text-3xl font-black text-emerald-300">{money(total, item.currency || "KES")}</p><p className="mt-1 text-xs text-slate-500">{item.pricingModel === "per_passenger" ? "per passenger" : "per vehicle"}</p></div></div><div className="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><p className="font-black text-slate-950">Before you submit</p><div className="mt-4 space-y-3 text-sm text-slate-600"><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/> Confirm your pickup time and route.</p><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/> Add flight and terminal details for airport pickups.</p><p className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/> Keep your phone available for the operations team.</p></div></div></aside>
    </div></section>
  </main>;
}

function Field({ label, children }) { return <label className="text-sm font-semibold text-slate-700">{label}{children}</label>; }
function Summary({ icon, label, value }) { return <div className="rounded-2xl bg-white p-4"><div className="flex items-center gap-2 text-emerald-600">{icon}</div><p className="mt-2 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-900">{value}</p></div>; }
