import { useQuery } from "@tanstack/react-query";
import { useParams, Link } from "react-router-dom";
import { AlertCircle, CreditCard, Loader2 } from "lucide-react";
import { getPublicPaymentLink } from "../api/financeLifecycleApi";

const money = (v, currency = "KES") => `${currency} ${Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
export default function PaymentLink() {
  const { token } = useParams(); const q = useQuery({ queryKey: ["public-payment-link", token], queryFn: () => getPublicPaymentLink(token), enabled: Boolean(token), retry: false }); const data = q.data?.data;
  if (q.isLoading) return <div className="min-h-[70vh] flex items-center justify-center"><Loader2 className="animate-spin"/></div>;
  if (q.isError || !data) return <div className="mx-auto max-w-xl px-6 py-20 text-center"><AlertCircle className="mx-auto text-red-600" size={40}/><h1 className="mt-4 text-2xl font-black">Payment link unavailable</h1><p className="mt-2 text-slate-500">This link may be expired, cancelled, or invalid.</p><Link to="/" className="mt-6 inline-block rounded-lg bg-emerald-700 px-5 py-2 font-bold text-white">Return to website</Link></div>;
  const inactive = data.status !== "active";
  return <div className="min-h-[70vh] bg-slate-50 px-6 py-14"><div className="mx-auto max-w-lg rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Secure payment</p><h1 className="mt-2 text-3xl font-black">Complete your booking payment</h1><div className="mt-6 rounded-xl bg-slate-50 p-5"><p className="text-sm text-slate-500">Booking</p><p className="text-lg font-bold">{data.booking?.bookingNumber || "Booking"}</p>{data.invoice?.invoiceNumber && <p className="mt-2 text-sm text-slate-500">Invoice {data.invoice.invoiceNumber}</p>}<p className="mt-5 text-sm text-slate-500">Amount requested</p><p className="text-3xl font-black text-emerald-700">{money(data.amount, data.currency)}</p></div>{inactive ? <div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">This payment link is {data.status} and cannot be used.</div> : <><p className="mt-5 text-sm text-slate-600">Sign in or create an account to securely continue to the booking payment screen. Your payment amount is validated by the server.</p><Link to={`/login?redirect=${encodeURIComponent(`/checkout/booking/${data.booking?.bookingNumber || ""}`)}`} className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white"><CreditCard size={18}/>Continue to payment</Link></>}<p className="mt-5 text-center text-xs text-slate-400">Do not share sensitive card, password, or M-Pesa PIN information with anyone.</p></div></div>;
}
