import express from "express";
import { authorize } from "../middleware/permissionMiddleware.js";
import { createAccount, createJournalEntry, getLedgerSummary, listAccounts, listJournalEntries, postJournalEntry, voidJournalEntry } from "../controllers/accountingController.js";
import { getFinancialStatements, getArAging, getApAging, getCashFlow } from "../controllers/accountingReportsController.js";
import { listAssets, createAsset, disposeAsset, postAssetDepreciation, listBudgets, upsertBudget, approveBudget, budgetVsActual, listPeriods, closePeriod, reopenPeriod, closeFinancialYear } from "../controllers/managementAccountingController.js";
import { getTaxControlReport, getCustomerLedgerReport, getSupplierLedgerReport, getProfitabilityReport } from "../controllers/accountingControlReportsController.js";
import { listSubledger, createSubledger, amortizeSubledger, reverseAccrual } from "../controllers/accountingSubledgerController.js";
import { exportGeneralLedgerCSV, exportTaxControlCSV } from "../controllers/accountingExportController.js";
import { reconcileOperationalAccounting } from "../controllers/accountingOperationalReconciliationController.js";
import { listReconciliationTransactions, createReconciliationTransaction, matchReconciliationTransaction, markReconciliationException } from "../controllers/accountingReconciliationController.js";

const router = express.Router();
router.get("/accounts", authorize("finance.view"), listAccounts);
router.post("/accounts", authorize("finance.manage"), createAccount);
router.get("/journal", authorize("finance.view"), listJournalEntries);
router.post("/journal", authorize("finance.manage"), createJournalEntry);
router.post("/journal/:id/post", authorize("finance.manage"), postJournalEntry);
router.post("/journal/:id/void", authorize("finance.manage"), voidJournalEntry);
router.get("/summary", authorize("finance.view"), getLedgerSummary);
router.get("/statements", authorize("finance.view"), getFinancialStatements);
router.get("/ar-aging", authorize("finance.view"), getArAging);
router.get("/ap-aging", authorize("finance.view"), getApAging);
router.get("/cash-flow", authorize("finance.view"), getCashFlow);
router.get("/tax-control", authorize("finance.view"), getTaxControlReport);
router.get("/customer-ledger", authorize("finance.view"), getCustomerLedgerReport);
router.get("/supplier-ledger", authorize("finance.view"), getSupplierLedgerReport);
router.get("/profitability", authorize("finance.view"), getProfitabilityReport);
router.get("/exports/general-ledger.csv", authorize("finance.view"), exportGeneralLedgerCSV);
router.get("/exports/tax-control.csv", authorize("finance.view"), exportTaxControlCSV);
router.get("/subledgers", authorize("finance.view"), listSubledger);
router.post("/subledgers", authorize("finance.manage"), createSubledger);
router.post("/subledgers/:id/amortize", authorize("finance.manage"), amortizeSubledger);
router.post("/subledgers/:id/reverse", authorize("finance.manage"), reverseAccrual);
router.get("/reconciliation/transactions", authorize("finance.view"), listReconciliationTransactions);
router.post("/reconciliation/transactions", authorize("finance.manage"), createReconciliationTransaction);
router.post("/reconciliation/transactions/:id/match", authorize("finance.manage"), matchReconciliationTransaction);
router.post("/reconciliation/transactions/:id/exception", authorize("finance.manage"), markReconciliationException);
router.post("/operational-reconciliation", authorize("finance.manage"), reconcileOperationalAccounting);
router.get("/assets", authorize("finance.view"), listAssets);
router.post("/assets", authorize("finance.manage"), createAsset);
router.post("/assets/:id/depreciate", authorize("finance.manage"), postAssetDepreciation);
router.post("/assets/:id/dispose", authorize("finance.manage"), disposeAsset);
router.get("/budgets", authorize("finance.view"), listBudgets);
router.post("/budgets", authorize("finance.manage"), upsertBudget);
router.post("/budgets/:id/approve", authorize("finance.manage"), approveBudget);
router.get("/budgets-vs-actual", authorize("finance.view"), budgetVsActual);
router.get("/periods", authorize("finance.view"), listPeriods);
router.post("/periods/:period/close", authorize("finance.manage"), closePeriod);
router.post("/periods/:period/reopen", authorize("finance.manage"), reopenPeriod);
router.post("/periods/:year/year-end-close", authorize("finance.manage"), closeFinancialYear);
export default router;
