import express from "express";
import { authorize } from "../middleware/permissionMiddleware.js";
import { createAccount, createJournalEntry, getLedgerSummary, listAccounts, listJournalEntries, postJournalEntry, voidJournalEntry } from "../controllers/accountingController.js";
import { getFinancialStatements, getArAging, getApAging, getCashFlow } from "../controllers/accountingReportsController.js";
import { listAssets, createAsset, postAssetDepreciation, listBudgets, upsertBudget, approveBudget, budgetVsActual, listPeriods, closePeriod, reopenPeriod } from "../controllers/managementAccountingController.js";
import { getTaxControlReport, getCustomerLedgerReport, getSupplierLedgerReport, getProfitabilityReport } from "../controllers/accountingControlReportsController.js";
import { listSubledger, createSubledger } from "../controllers/accountingSubledgerController.js";

const router = express.Router();
router.get("/accounts", authorize("finance.view"), listAccounts);
router.post("/accounts", authorize("finance.manage"), createAccount);
router.get("/journal", authorize("finance.view"), listJournalEntries);
router.post("/journal", authorize("finance.manage"), createJournalEntry);
router.post("/journal/:id/post", authorize("finance.manage"), postJournalEntry);
router.post("/journal/:id/void", authorize("finance.manage"), voidJournalEntry);
router.get("/summary", authorize("finance.view"), getLedgerSummary);
router.get("/statements", authorize("finance.view"), getFinancialStatements);
router.get("/ar-aging", authorize("finance.view"), getArAging);
router.get("/ap-aging", authorize("finance.view"), getApAging);
router.get("/cash-flow", authorize("finance.view"), getCashFlow);
router.get("/tax-control", authorize("finance.view"), getTaxControlReport);
router.get("/customer-ledger", authorize("finance.view"), getCustomerLedgerReport);
router.get("/supplier-ledger", authorize("finance.view"), getSupplierLedgerReport);
router.get("/profitability", authorize("finance.view"), getProfitabilityReport);
router.get("/subledgers", authorize("finance.view"), listSubledger);
router.post("/subledgers", authorize("finance.manage"), createSubledger);
router.get("/assets", authorize("finance.view"), listAssets);
router.post("/assets", authorize("finance.manage"), createAsset);
router.post("/assets/:id/depreciate", authorize("finance.manage"), postAssetDepreciation);
router.get("/budgets", authorize("finance.view"), listBudgets);
router.post("/budgets", authorize("finance.manage"), upsertBudget);
router.post("/budgets/:id/approve", authorize("finance.manage"), approveBudget);
router.get("/budgets-vs-actual", authorize("finance.view"), budgetVsActual);
router.get("/periods", authorize("finance.view"), listPeriods);
router.post("/periods/:period/close", authorize("finance.manage"), closePeriod);
router.post("/periods/:period/reopen", authorize("finance.manage"), reopenPeriod);
export default router;
