import express from "express";
import { protect, managerOnly } from "../middleware/authMiddleware.js";
import { ensureOpsAccess, hospitalityDashboard, hotelCalendar, hotelPerformance, amendHotelBooking, cancelHotelBooking, blockRooms, releaseRoomBlock, ratePlans, saveRatePlan, supplierContracts, saveSupplierContract, deposits, saveDeposit, transferDispatch, assignTransfer, updateTransferStatus, paymentReconciliation, listDrivers, listVehicles } from "../controllers/hospitalityOperationsController.js";
import { amendHotelBookingProduction } from "../controllers/hospitalityBookingAmendmentController.js";
import { createConcurrentSafeRoomBlock } from "../controllers/hospitalityInventoryConcurrencyController.js";
import { createCommercialRatePlan, updateCommercialRatePlan, createCommercialSupplierContract, updateCommercialSupplierContract, createCommercialDeposit, updateCommercialDeposit } from "../controllers/hospitalityCommercialController.js";

const router=express.Router();
router.use(protect,managerOnly,ensureOpsAccess);
router.get("/dashboard",hospitalityDashboard);
router.get("/hotels/calendar",hotelCalendar);
router.get("/hotels/performance",hotelPerformance);
router.patch("/hotels/bookings/:id/amend",amendHotelBookingProduction);
router.patch("/hotels/bookings/:id/cancel",cancelHotelBooking);
router.post("/hotels/room-blocks",createConcurrentSafeRoomBlock);
router.patch("/hotels/room-blocks/:id/release",releaseRoomBlock);
router.get("/rate-plans",ratePlans);
router.post("/rate-plans",createCommercialRatePlan);
router.patch("/rate-plans/:id",updateCommercialRatePlan);
router.get("/suppliers/contracts",supplierContracts);
router.post("/suppliers/contracts",createCommercialSupplierContract);
router.patch("/suppliers/contracts/:id",updateCommercialSupplierContract);
router.get("/deposits",deposits);
router.post("/deposits",createCommercialDeposit);
router.patch("/deposits/:id",updateCommercialDeposit);
router.get("/transfers/dispatch",transferDispatch);
router.patch("/transfers/:id/assign",assignTransfer);
router.patch("/transfers/:id/status",updateTransferStatus);
router.get("/payments/reconciliation",paymentReconciliation);
router.get("/drivers",listDrivers);
router.get("/vehicles",listVehicles);
export default router;
