import { resolveTenant } from "../middleware/tenantMiddleware.js";
import "../tenancy/bootstrap.js";
import express from "express";
import { protect, checkPermission } from "../middleware/authMiddleware.js";
import superAdminRoutes from "./superAdminRoutes.js";
import superAdminRoleRoutes from "./superAdminRoleRoutes.js";
import superAdminRevenueRoutes from "./superAdminRevenueRoutes.js";
import apiMonitorRoutes from "./apiMonitorRoutes.js";
import superAdminOperationsRoutes from "./superAdminOperationsRoutes.js";
import superAdminToolsRoutes from "./superAdminToolsRoutes.js";
import superAdminMaintenanceRoutes from "./superAdminMaintenanceRoutes.js";
import tenantRoutes from "./tenantRoutes.js";
import commissionRoutes from "./commissionRoutes.js";
import agentWithdrawalRoutes from "./agentWithdrawalRoutes.js";
import tourManagerRoutes from "./tourManagerRoutes.js";
import staffRoutes from "./staffRoutes.js";
import userRoutes from "./userRoutes.js";
import vehicleRoutes from "./vehicleRoutes.js";
import authRoutes from "./authRoutes.js";
import mfaRoutes from "./mfaRoutes.js";
import bookingRoutes from "./bookingRoutes.js";
import tourRoutes from "./tourRoutes.js";
import destinationRoutes from "./destinationRoutes.js";
import adminDestinationRoutes from "./adminDestinationRoutes.js";
import reviewRoutes from "./reviewRoutes.js";
import wishlistRoutes from "./wishlistRoutes.js";
import galleryRoutes from "./galleryRoutes.js";
import heroRoutes from "./heroRoutes.js";
import mpesaRoutes from "./mpesaRoutes.js";
import stripeRoutes from "./stripeRoutes.js";
import adminRoutes from "./adminRoutes.js";
import adminTourRoutes from "./adminTourRoutes.js";
import adminBookingRoutes from "./adminBookingRoutes.js";
import adminPaymentRoutes from "./adminPaymentRoutes.js";
import adminRoleRoutes from "./adminRoleRoutes.js";
import systemHealthRoutes from "./systemHealthRoutes.js";
import securityRoutes from "./securityRoutes.js";
import adminAuthRoutes from "./adminAuthRoutes.js";
import adminDashboardRoutes from "./adminDashboardRoutes.js";
import adminReviewRoutes from "./adminReviewRoutes.js";
import adminGalleryRoutes from "./adminGalleryRoutes.js";
import adminCategoryRoutes from "./adminCategoryRoutes.js";
import adminCouponRoutes from "./adminCouponRoutes.js";
import adminHeroRoutes from "./adminHeroRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import agentRoutes from "./agentRoutes.js";
import agentBookingRoutes from "./agentBookingRoutes.js";
import agentCustomerRoutes from "./agentCustomerRoutes.js";
import agentPackageRoutes from "./agentPackageRoutes.js";
import couponRoutes from "./couponRoutes.js";
import crmRoutes from "./crmRoutes.js";
import customerRoutes from "./customerRoutes.js";
import documentRoutes from "./documentRoutes.js";
import financeRoutes from "./financeRoutes.js";
import guideRoutes from "./guideRoutes.js";
import driverRoutes from "./driverRoutes.js";
import invoiceRoutes from "./invoiceRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import quotationRoutes from "./quotationRoutes.js";
import recommendationRoutes from "./recommendationRoutes.js";
import tourAssignmentRoutes from "./tourAssignmentRoutes.js";
import tourReportRoutes from "./tourReportRoutes.js";
import aiRoutes from "./aiRoutes.js";
import adminAIRoutes from "./adminAIRoutes.js";
import seoRoutes from "./seoRoutes.js";
import settingsRoutes from "./settingsRoutes.js";
import { getPublicSettings } from "../controllers/settingsController.js";
import customTourRequestRoutes from "./customTourRequestRoutes.js";
import superAdminUserRoutes from "./superAdminUserRoutes.js";
import tenantBrandingRoutes from "./tenantBrandingRoutes.js";

const router = express.Router();
router.use("/tenant", tenantBrandingRoutes);
router.use(resolveTenant);
router.use("/categories", categoryRoutes);
router.use("/auth", authRoutes);
router.use("/mfa", mfaRoutes);
router.use("/bookings", bookingRoutes);
router.use("/tours", tourRoutes);
router.use("/destinations", destinationRoutes);
router.use("/admin/destinations", adminDestinationRoutes);
router.use("/reviews", reviewRoutes);
router.use("/custom-tour-requests", customTourRequestRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/gallery", galleryRoutes);
router.use("/hero", heroRoutes);
router.use("/mpesa", mpesaRoutes);
router.use("/payments", mpesaRoutes);
router.use("/payments/stripe", stripeRoutes);
router.use("/tenants", tenantRoutes);
router.use("/admin/auth", adminAuthRoutes);
router.use("/admin/roles", adminRoleRoutes);

// Register the specific dashboard router before the generic /admin router.
// Express matches middleware in registration order, so this prevents
// /api/admin/dashboard from being swallowed by /api/admin first.
router.use("/admin/dashboard", adminDashboardRoutes);

router.use("/admin", adminRoutes);
router.use("/admin/tours", adminTourRoutes);
router.use("/admin/bookings", adminBookingRoutes);
router.use("/admin/payments", adminPaymentRoutes);
router.use("/system", systemHealthRoutes);
router.use("/security", securityRoutes);
router.get("/admin/system-health", protect, checkPermission("system.security"), async (req, res) => {
  const mongoose = (await import("mongoose")).default;
  const memory = process.memoryUsage();
  res.json({ status: "healthy", server: "running", nodeVersion: process.version, environment: process.env.NODE_ENV || "development", uptime: Math.floor(process.uptime()), timestamp: new Date().toISOString(), database: mongoose.connection.readyState === 1 ? "connected" : "disconnected", memory: { used: Math.round(memory.heapUsed / 1024 / 1024) + " MB", total: Math.round(memory.heapTotal / 1024 / 1024) + " MB" }, platform: { os: process.platform, architecture: process.arch } });
});
router.get("/settings/public", getPublicSettings);
router.use("/admin/settings", settingsRoutes);
router.use("/admin/reviews", adminReviewRoutes);
router.use("/admin/gallery", adminGalleryRoutes);
router.use("/admin/experiences", adminCategoryRoutes);
router.use("/admin/hero", adminHeroRoutes);
router.use("/admin/coupons", adminCouponRoutes);
router.use("/admin/finance", financeRoutes);
router.use("/admin/customers", customerRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/tourmanager", tourManagerRoutes);
router.use("/tour-manager", tourManagerRoutes);
router.use("/tour-assignments", tourAssignmentRoutes);
router.use("/tour-reports", tourReportRoutes);
router.use("/agents", agentRoutes);
router.use("/agent", agentRoutes);
router.use("/agents/bookings", agentBookingRoutes);
router.use("/agent/bookings", agentBookingRoutes);
router.use("/agents/customers", agentCustomerRoutes);
router.use("/agent/customers", agentCustomerRoutes);
router.use("/agents/packages", agentPackageRoutes);
router.use("/agent/packages", agentPackageRoutes);
router.use("/agents/quotes", quotationRoutes);
router.use("/agent/quotes", quotationRoutes);
router.use("/customers", customerRoutes);
router.use("/documents", documentRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/notifications", notificationRoutes);
router.get("/health", (req, res) => res.status(200).json({ success: true, message: "Travel API healthy" }));
router.use("/recommendations", recommendationRoutes);
router.use("/guide", guideRoutes);
router.use("/driver", driverRoutes);
router.use("/vehicles", vehicleRoutes);
router.use("/users", userRoutes);
router.use("/staff", staffRoutes);
router.use("/commissions", commissionRoutes);
router.use("/agent-withdrawals", agentWithdrawalRoutes);
router.use("/crm", crmRoutes);
router.use("/coupons", couponRoutes);
router.use("/ai", aiRoutes);
router.use("/admin-ai", adminAIRoutes);
router.use("/", seoRoutes);
router.use("/superadmin", superAdminRoutes);
router.use("/superadmin/revenue", superAdminRevenueRoutes);
router.use("/superadmin/roles", superAdminRoleRoutes);
router.use("/superadmin/api-monitor", apiMonitorRoutes);
router.use("/superadmin", superAdminOperationsRoutes);
router.use("/superadmin/users", superAdminUserRoutes);
router.use("/superadmin-tools", superAdminToolsRoutes);
router.use("/superadmin/maintenance", superAdminMaintenanceRoutes);
export default router;
