import express from "express";
import { resolveTenant } from "../middleware/tenantMiddleware.js";
import { protect, checkPermission } from "../middleware/authMiddleware.js";
import { getOperationsOverview } from "../controllers/operationsController.js";
import operationsModuleRoutes from "./operationsModuleRoutes.js";
const router=express.Router();
router.use(resolveTenant, protect, checkPermission("booking.manage"));
router.get("/", getOperationsOverview);
router.use("/module", operationsModuleRoutes);
export default router;
