import api from "./axios";
const unwrap=r=>r?.data?.data??r?.data??[];
export const getHospitalityDashboard=()=>api.get("/admin/hospitality-operations/dashboard").then(unwrap);
export const getHotelCalendar=(params={})=>api.get("/admin/hospitality-operations/hotels/calendar",{params}).then(unwrap);
export const getHotelPerformance=(params={})=>api.get("/admin/hospitality-operations/hotels/performance",{params}).then(unwrap);
export const amendHotelBooking=(id,payload)=>api.patch(`/admin/hospitality-operations/hotels/bookings/${id}/amend`,payload).then(unwrap);
export const cancelHotelBooking=(id,payload={})=>api.patch(`/admin/hospitality-operations/hotels/bookings/${id}/cancel`,payload).then(unwrap);
export const blockRooms=payload=>api.post("/admin/hospitality-operations/hotels/room-blocks",payload).then(unwrap);
export const releaseRoomBlock=id=>api.patch(`/admin/hospitality-operations/hotels/room-blocks/${id}/release`).then(unwrap);
export const getRatePlans=(params={})=>api.get("/admin/hospitality-operations/rate-plans",{params}).then(unwrap);
export const createRatePlan=payload=>api.post("/admin/hospitality-operations/rate-plans",payload).then(unwrap);
export const updateRatePlan=(id,payload)=>api.patch(`/admin/hospitality-operations/rate-plans/${id}`,payload).then(unwrap);
export const getSupplierContracts=(params={})=>api.get("/admin/hospitality-operations/suppliers/contracts",{params}).then(unwrap);
export const createSupplierContract=payload=>api.post("/admin/hospitality-operations/suppliers/contracts",payload).then(unwrap);
export const updateSupplierContract=(id,payload)=>api.patch(`/admin/hospitality-operations/suppliers/contracts/${id}`,payload).then(unwrap);
export const getHospitalityDeposits=(params={})=>api.get("/admin/hospitality-operations/deposits",{params}).then(unwrap);
export const createHospitalityDeposit=payload=>api.post("/admin/hospitality-operations/deposits",payload).then(unwrap);
export const updateHospitalityDeposit=(id,payload)=>api.patch(`/admin/hospitality-operations/deposits/${id}`,payload).then(unwrap);
export const getTransferDispatch=(params={})=>api.get("/admin/hospitality-operations/transfers/dispatch",{params}).then(unwrap);
export const assignTransfer=(id,payload)=>api.patch(`/admin/hospitality-operations/transfers/${id}/assign`,payload).then(unwrap);
export const updateTransferStatus=(id,payload)=>api.patch(`/admin/hospitality-operations/transfers/${id}/status`,payload).then(unwrap);
export const getHospitalityPaymentReconciliation=(params={})=>api.get("/admin/hospitality-operations/payments/reconciliation",{params}).then(unwrap);
export const getHospitalityDrivers=()=>api.get("/admin/hospitality-operations/drivers").then(unwrap);
export const getHospitalityVehicles=()=>api.get("/admin/hospitality-operations/vehicles").then(unwrap);
