export default function PopularTours({ tours = [] }) {
  const list = Array.isArray(tours) ? tours : [];
  const rankStyles = ["bg-amber-400 text-amber-950", "bg-slate-300 text-slate-800", "bg-orange-300 text-orange-950", "bg-indigo-200 text-indigo-900"];

  return (
    <section className="rounded-2xl border border-orange-200 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-sm sm:p-6">
      <div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">Top Performing Tours</h2><p className="mt-1 text-sm text-slate-600">Ranked by booking activity and paid bookings.</p></div>{list.length > 0 && <span className="shrink-0 rounded-full bg-orange-600 px-3 py-1 text-xs font-bold text-white shadow-sm">Top {list.length}</span>}</div>
      {list.length === 0 ? <div className="rounded-xl border border-dashed border-orange-300 bg-white/70 p-8 text-center text-slate-500">No tour booking data available yet.</div> : <div className="space-y-3">{list.map((tour, index) => { const totalBookings = Number(tour?.totalBookings || 0); const paidBookings = Number(tour?.paidBookings ?? tour?.confirmedPaidBookings ?? 0); return <div key={tour?._id || index} className="flex items-center justify-between gap-4 rounded-xl border border-orange-100 bg-white/90 p-3.5 shadow-sm transition hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-md"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-extrabold shadow-sm ${rankStyles[index] || "bg-indigo-100 text-indigo-800"}`}>{index + 1}</span><div className="min-w-0"><p className="truncate font-semibold text-slate-900">{tour?.title || "Untitled tour"}</p><p className="mt-0.5 text-xs font-medium text-slate-500">{paidBookings.toLocaleString()} paid {paidBookings === 1 ? "booking" : "bookings"}</p></div></div><div className="shrink-0 rounded-lg bg-indigo-50 px-3 py-2 text-right ring-1 ring-indigo-100"><p className="text-lg font-extrabold leading-none text-indigo-800">{totalBookings.toLocaleString()}</p><p className="mt-1 text-[11px] font-semibold text-indigo-600">{totalBookings === 1 ? "booking" : "bookings"}</p></div></div>; })}</div>}
    </section>
  );
}
