import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Car, CalendarDays, MapPin, Users, CheckCircle2, Clock3, Wrench, RefreshCw, Play, Flag, ShieldCheck, Eye, X } from "lucide-react";
import { getDriverDashboard, getDriverAssignedTours, getDriverTour, getDriverTourGuests, updateDriverTourStatus } from "../../api/driverApi";
import { firstNumeric, numeric, unwrapData } from "../../utils/dashboardData";

const idOf = (value) => value?._id || value?.id || value;
const startOfDay = (value) => { const date = new Date(value); if (Number.isNaN(date.getTime())) return null; date.setHours(0, 0, 0, 0); return date; };
const tourStart = (tour) => tour?.startDate || tour?.date || tour?.tourDate;
const tourEnd = (tour) => tour?.endDate || tour?.startDate || tour?.date || tour?.tourDate;
const isTourActiveOnDate = (tour, value) => { const day = startOfDay(value); const start = startOfDay(tourStart(tour)); const end = startOfDay(tourEnd(tour)); return Boolean(day && start && end && day >= start && day <= end); };
const formatDateTime = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString([], { dateStyle: "medium", timeStyle: "short" }); };

export default function DriverDashboard() {
  const [actionId, setActionId] = useState("");
  const [actionMessage, setActionMessage] = useState("");
  const [selectedTour, setSelectedTour] = useState(null);
  const [showGuests, setShowGuests] = useState(false);
  const dashboardQuery = useQuery({ queryKey: ["driver-dashboard"], queryFn: getDriverDashboard, staleTime: 30000, refetchOnWindowFocus: true, refetchOnMount: "always", retry: 1 });
  const toursQuery = useQuery({ queryKey: ["driver-assigned-tours"], queryFn: getDriverAssignedTours, staleTime: 30000, refetchOnWindowFocus: true, refetchOnMount: "always", retry: 1 });
  const loading = dashboardQuery.isLoading || toursQuery.isLoading;
  const error = dashboardQuery.error || toursQuery.error;
  const dashboard = unwrapData(dashboardQuery.data);
  const tourPayload = unwrapData(toursQuery.data);
  const assignedTours = Array.isArray(tourPayload?.tours) ? tourPayload.tours : Array.isArray(tourPayload) ? tourPayload : [];
  const tours = useMemo(() => assignedTours.length ? assignedTours : (dashboard?.assignedTours || dashboard?.upcomingTours || dashboard?.tours || []), [assignedTours, dashboard]);
  const vehicle = dashboard?.vehicle || dashboard?.assignedVehicle || tours.find((tour) => tour?.assignedVehicle)?.assignedVehicle || null;
  const today = new Date();
  const todayTrips = tours.filter((tour) => isTourActiveOnDate(tour, today) && !["completed", "cancelled"].includes(String(tour?.status || "").toLowerCase()));
  const nextTour = tours.map((tour) => ({ tour, date: new Date(tourStart(tour) || 0) })).filter(({ tour, date }) => { const start = startOfDay(today); return !Number.isNaN(date.getTime()) && start && date >= start && !["completed", "cancelled"].includes(String(tour?.status || "").toLowerCase()); }).sort((a, b) => a.date - b.date)[0]?.tour;
  const nextPickup = nextTour?.pickupTime || nextTour?.pickupDateTime || tourStart(nextTour);
  const stats = dashboard?.stats || dashboard?.summary || {};
  const completedTours = firstNumeric(stats.completedTours, dashboard?.completedTours, tours.filter((tour) => String(tour?.status || "").toLowerCase() === "completed").length);
  const ongoingTours = firstNumeric(stats.ongoingTours, dashboard?.ongoingTours, tours.filter((tour) => String(tour?.status || "").toLowerCase() === "ongoing").length);
  const totalTours = firstNumeric(stats.totalTours, dashboard?.totalTours, tours.length);
  const totalGuests = firstNumeric(stats.totalGuests, tours.reduce((sum, tour) => sum + Number(tour?.guests ?? tour?.guestCount ?? tour?.numberOfGuests ?? 0), 0));
  const vehicleStatus = vehicle?.status || (vehicle ? "available" : "Not assigned");
  const refresh = () => { void dashboardQuery.refetch(); void toursQuery.refetch(); };
  const changeStatus = async (tour, status) => { const tourId = idOf(tour); if (!tourId) return; try { setActionId(`${tourId}:${status}`); setActionMessage(""); await updateDriverTourStatus(tourId, status); setActionMessage(status === "ongoing" ? "Tour started successfully." : "Tour completed successfully."); await Promise.all([dashboardQuery.refetch(), toursQuery.refetch()]); setSelectedTour((current) => current ? { ...current, status } : current); } catch (err) { setActionMessage(err?.response?.data?.message || err?.message || "Unable to update tour status."); } finally { setActionId(""); } };
  if (loading) return <div className="ops-page"><div className="ops-card ops-panel">Loading driver operations...</div></div>;
  return <div className="ops-page">
    <div className="ops-page-head"><div><div className="ops-page-title">Driver Operations</div><div className="ops-page-subtitle">{dashboard?.driver?.name || dashboard?.profile?.name || "Driver"} — assignments, pickups, guests and vehicle readiness.</div></div><button className="btn btn-secondary" type="button" onClick={refresh} disabled={dashboardQuery.isFetching || toursQuery.isFetching}><RefreshCw size={15} className={dashboardQuery.isFetching || toursQuery.isFetching ? "spin" : ""} /> {dashboardQuery.isFetching || toursQuery.isFetching ? "Refreshing..." : "Refresh"}</button></div>
    {error && <div className="ops-card ops-alert" role="alert">{error?.response?.data?.message || error?.message || "Unable to load your driver operations."}</div>}
    {actionMessage && <div className="ops-card ops-alert" role="status">{actionMessage}</div>}
    <div className="ops-kpis"><div className="ops-card ops-kpi"><div className="ops-kpi-label">Today&apos;s Trips</div><div className="ops-kpi-value">{numeric(firstNumeric(stats.todayTrips, todayTrips.length))}</div><div className="ops-kpi-meta">Tours active today</div></div><div className="ops-card ops-kpi"><div className="ops-kpi-label">Next Pickup</div><div className="ops-kpi-value">{nextPickup ? formatDateTime(nextPickup) : "—"}</div><div className="ops-kpi-meta">Next scheduled movement</div></div><div className="ops-card ops-kpi"><div className="ops-kpi-label">Guests</div><div className="ops-kpi-value">{numeric(totalGuests)}</div><div className="ops-kpi-meta">Across assigned tours</div></div><div className="ops-card ops-kpi"><div className="ops-kpi-label">Completed Tours</div><div className="ops-kpi-value">{numeric(completedTours)}</div><div className="ops-kpi-meta">{numeric(ongoingTours)} currently ongoing</div></div></div>
    <div className="ops-grid-2"><div className="ops-card ops-panel"><div className="ops-panel-head"><div className="ops-panel-title">Assigned tours</div><CalendarDays size={17} /></div>{tours.length === 0 ? <div className="ops-alert">No tours are currently assigned to you.</div> : <div className="ops-list">{tours.slice(0, 10).map((tour) => { const tourId = idOf(tour); const status = String(tour?.status || "scheduled").toLowerCase(); const start = new Date(tourStart(tour) || 0); const isToday = isTourActiveOnDate(tour, today); const title = tour?.title || tour?.destination?.name || tour?.destinationName || tour?.location || "Tour"; const guests = tour?.guests ?? tour?.guestCount ?? tour?.numberOfGuests ?? 0; return <div className="ops-list-item" key={tourId}><span><MapPin size={15} /> {title} · {Number.isNaN(start.getTime()) ? "—" : start.toLocaleDateString()} · {numeric(guests)} guests</span><span className="ops-status neutral">{status}</span><button className="btn btn-secondary" type="button" onClick={() => { setSelectedTour(tour); setShowGuests(false); }}><Eye size={14}/> Details</button>{["scheduled", "upcoming"].includes(status) && <button className="btn btn-secondary" type="button" disabled={!isToday || actionId === `${tourId}:ongoing`} title={!isToday ? "This tour can only be started on its start date" : "Start tour"} onClick={() => void changeStatus(tour, "ongoing")}><Play size={14} /> {actionId === `${tourId}:ongoing` ? "Starting..." : "Start"}</button>}{status === "ongoing" && <button className="btn btn-secondary" type="button" disabled={actionId === `${tourId}:completed`} onClick={() => void changeStatus(tour, "completed")}><Flag size={14} /> {actionId === `${tourId}:completed` ? "Completing..." : "Complete"}</button>}</div>; })}</div>}</div>
      <div className="ops-card ops-panel"><div className="ops-panel-head"><div className="ops-panel-title">Vehicle & readiness</div><Car size={17} /></div><div className="ops-list"><div className="ops-list-item"><span><Car size={15} /> Vehicle</span><span>{vehicle?.registrationNumber || vehicle?.registration || vehicle?.name || "Not assigned"}</span></div><div className="ops-list-item"><span><Wrench size={15} /> Vehicle status</span><span className={`ops-status ${vehicle && vehicleStatus !== "maintenance" && vehicleStatus !== "out_of_service" ? "ok" : "neutral"}`}>{vehicleStatus}</span></div><div className="ops-list-item"><span><CheckCircle2 size={15} /> Total tours</span><span>{numeric(totalTours)}</span></div><div className="ops-list-item"><span><ShieldCheck size={15} /> Driver status</span><span className="ops-status ok">{dashboard?.driver?.status || "active"}</span></div><div className="ops-list-item"><span><Clock3 size={15} /> Availability</span><span>{dashboard?.driver?.availability || "available"}</span></div></div><div className="ops-alert">Before departure, verify fuel, tyres, lights, insurance and mechanical safety. Report any issue before starting the trip.</div></div></div>
    <div className="ops-grid-2"><div className="ops-card ops-panel"><div className="ops-panel-head"><div className="ops-panel-title">Trip control</div><CalendarDays size={17} /></div><div className="ops-list"><div className="ops-list-item"><span><CalendarDays size={15} /> Today&apos;s schedule</span><span className="ops-status neutral">{todayTrips.length ? `${todayTrips.length} trip${todayTrips.length > 1 ? "s" : ""}` : "None"}</span></div><div className="ops-list-item"><span><MapPin size={15} /> Next destination</span><span className="ops-status neutral">{nextTour?.destination?.name || nextTour?.destinationName || nextTour?.location || "Not assigned"}</span></div><div className="ops-list-item"><span><Users size={15} /> Next tour guests</span><span className="ops-status neutral">{numeric(nextTour?.guests ?? nextTour?.guestCount ?? nextTour?.numberOfGuests ?? 0)}</span></div><div className="ops-list-item"><span><Clock3 size={15} /> Next tour status</span><span className="ops-status ok">{nextTour?.status || "Ready"}</span></div></div></div><div className="ops-card ops-panel"><div className="ops-panel-head"><div className="ops-panel-title">Driver profile</div><ShieldCheck size={17} /></div><div className="ops-list"><div className="ops-list-item"><span>Name</span><span>{dashboard?.driver?.name || "—"}</span></div><div className="ops-list-item"><span>Phone</span><span>{dashboard?.driver?.phone || "—"}</span></div><div className="ops-list-item"><span>Licence</span><span>{dashboard?.driver?.licenseNumber || "Not recorded"}</span></div><div className="ops-list-item"><span>Licence expiry</span><span>{dashboard?.driver?.licenseExpiry ? new Date(dashboard.driver.licenseExpiry).toLocaleDateString() : "Not recorded"}</span></div></div></div></div>
    {selectedTour && <DriverTourDetails tour={selectedTour} showGuests={showGuests} setShowGuests={setShowGuests} onClose={() => setSelectedTour(null)} />}
  </div>;
}

function DriverTourDetails({ tour, showGuests, setShowGuests, onClose }) {
  const id = idOf(tour);
  const detailQuery = useQuery({ queryKey: ["driver-tour", id], queryFn: () => getDriverTour(id), enabled: Boolean(id) });
  const guestsQuery = useQuery({ queryKey: ["driver-tour-guests", id], queryFn: () => getDriverTourGuests(id), enabled: Boolean(id && showGuests) });
  const detail = unwrapData(detailQuery.data) || tour;
  const guests = guestsQuery.data?.guests || guestsQuery.data?.data?.guests || guestsQuery.data || [];
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-bold">{detail?.title || detail?.name || "Tour Details"}</h2><p className="text-sm text-slate-500">Tour ID: {id}</p></div><button type="button" onClick={onClose} aria-label="Close" className="rounded-lg p-2 hover:bg-slate-100"><X size={20}/></button></div>{detailQuery.isLoading ? <p className="p-5">Loading details...</p> : <><div className="grid gap-4 p-5 sm:grid-cols-2"><Info label="Date" value={detail?.startDate || detail?.travelDate || detail?.date ? new Date(detail.startDate || detail.travelDate || detail.date).toLocaleDateString() : "Not set"}/><Info label="Location" value={detail?.location || detail?.destination?.name || detail?.destinationName}/><Info label="Pickup" value={detail?.pickupLocation || detail?.pickupTime}/><Info label="Status" value={detail?.status}/><Info label="Guests" value={detail?.numberOfGuests || detail?.guestsCount || detail?.guestCount || 0}/><Info label="Vehicle" value={detail?.assignedVehicle?.registrationNumber || detail?.assignedVehicle?.plateNumber || detail?.vehicle?.registrationNumber || "Not assigned"}/></div><div className="border-t p-5"><button type="button" onClick={() => setShowGuests((value) => !value)} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 font-semibold"><Users size={16}/>{showGuests ? "Hide Guests" : "View Guests"}</button>{showGuests && <div className="mt-4">{guestsQuery.isLoading ? <p>Loading guests...</p> : guestsQuery.isError ? <p className="text-red-600">Unable to load guests.</p> : <pre className="max-h-64 overflow-auto rounded-lg bg-slate-50 p-4 text-xs">{JSON.stringify(guests, null, 2)}</pre>}</div>}</div></>}<div className="flex justify-end border-t p-5"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 font-semibold">Close</button></div></div></div>;
}
function Info({ label, value }) { return <div className="rounded-xl bg-slate-50 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 font-medium">{value || "Not available"}</div></div>; }
