import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Link as LinkIcon, Plus, ReceiptText, XCircle } from "lucide-react";
import { createPaymentLink, getPaymentLinks, cancelPaymentLink, createCreditDebitNote, getCreditDebitNotes, issueCreditDebitNote, cancelCreditDebitNote } from "../../api/financeLifecycleApi";

const money = (v) => `KES ${Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const list = (v) => Array.isArray(v) ? v : v?.data || [];
export default function FinanceLifecycleCenter() {
  const qc = useQueryClient(); const [bookingId, setBookingId] = useState(""); const [linkAmount, setLinkAmount] = useState(""); const [invoiceId, setInvoiceId] = useState(""); const [noteType, setNoteType] = useState("credit"); const [noteAmount, setNoteAmount] = useState(""); const [taxAmount, setTaxAmount] = useState("0"); const [reason, setReason] = useState(""); const [createdPath, setCreatedPath] = useState("");
  const linksQ = useQuery({ queryKey: ["finance-payment-links"], queryFn: getPaymentLinks }); const notesQ = useQuery({ queryKey: ["finance-credit-debit-notes"], queryFn: getCreditDebitNotes });
  const refresh = () => { qc.invalidateQueries({ queryKey: ["finance-payment-links"] }); qc.invalidateQueries({ queryKey: ["finance-credit-debit-notes"] }); qc.invalidateQueries({ queryKey: ["admin-finance-accounting"] }); };
  const linkMutation = useMutation({ mutationFn: createPaymentLink, onSuccess: (data) => { setCreatedPath(data?.paymentPath || ""); setBookingId(""); setLinkAmount(""); refresh(); } });
  const cancelLink = useMutation({ mutationFn: cancelPaymentLink, onSuccess: refresh });
  const noteMutation = useMutation({ mutationFn: createCreditDebitNote, onSuccess: () => { setInvoiceId(""); setNoteAmount(""); setReason(""); refresh(); } });
  const issueNote = useMutation({ mutationFn: issueCreditDebitNote, onSuccess: refresh }); const cancelNote = useMutation({ mutationFn: cancelCreditDebitNote, onSuccess: refresh });
  const copy = async (text) => { try { await navigator.clipboard.writeText(`${window.location.origin}${text}`); } catch {} };
  return <section className="space-y-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
    <div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Finance lifecycle</p><h2 className="text-xl font-bold">Payment links & credit/debit notes</h2><p className="mt-1 text-sm text-slate-500">Create controlled customer payment links and issue accounting notes without changing the original invoice.</p></div>
    <div className="grid gap-6 xl:grid-cols-2">
      <form onSubmit={(e)=>{e.preventDefault(); linkMutation.mutate({ bookingId, ...(linkAmount ? { amount: Number(linkAmount) } : {}) });}} className="rounded-xl border p-5 space-y-3"><div className="flex items-center gap-2 font-bold"><LinkIcon size={18}/> Create payment link</div><input required value={bookingId} onChange={e=>setBookingId(e.target.value)} placeholder="Booking ID" className="w-full rounded-lg border p-2"/><input value={linkAmount} onChange={e=>setLinkAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="Amount (blank = full balance)" className="w-full rounded-lg border p-2"/><button disabled={linkMutation.isPending} className="inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-50"><Plus size={16}/>Create link</button>{createdPath && <div className="rounded-lg bg-emerald-50 p-3 text-sm"><p className="font-semibold">Payment link created</p><code className="break-all">{window.location.origin}{createdPath}</code><button type="button" onClick={()=>copy(createdPath)} className="ml-2 inline-flex items-center gap-1 rounded border px-2 py-1"><Copy size={13}/>Copy</button></div>}{linkMutation.isError && <p className="text-sm text-red-600">{linkMutation.error?.response?.data?.message || linkMutation.error?.message}</p>}</form>
      <form onSubmit={(e)=>{e.preventDefault(); noteMutation.mutate({ type: noteType, originalInvoice: invoiceId, amount: Number(noteAmount), taxAmount: Number(taxAmount), reason });}} className="rounded-xl border p-5 space-y-3"><div className="flex items-center gap-2 font-bold"><ReceiptText size={18}/> Create credit/debit note</div><input required value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} placeholder="Original invoice ID" className="w-full rounded-lg border p-2"/><div className="grid grid-cols-2 gap-2"><select value={noteType} onChange={e=>setNoteType(e.target.value)} className="rounded-lg border p-2"><option value="credit">Credit note</option><option value="debit">Debit note</option></select><input required value={noteAmount} onChange={e=>setNoteAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="Net amount" className="rounded-lg border p-2"/></div><input value={taxAmount} onChange={e=>setTaxAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="Tax amount" className="w-full rounded-lg border p-2"/><textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason" className="w-full rounded-lg border p-2"/><button disabled={noteMutation.isPending} className="rounded-lg bg-slate-900 px-4 py-2 font-bold text-white">Save draft</button>{noteMutation.isError && <p className="text-sm text-red-600">{noteMutation.error?.response?.data?.message || noteMutation.error?.message}</p>}</form>
    </div>
    <div className="grid gap-6 xl:grid-cols-2"><div><h3 className="font-bold">Recent payment links</h3><div className="mt-3 space-y-2">{list(linksQ.data).slice(0,8).map(l=><div key={l._id} className="flex items-center justify-between gap-3 rounded-lg border p-3 text-sm"><div><p className="font-semibold">{l.booking?.bookingNumber || l.booking}</p><p>{money(l.amount)} · {l.status}</p><p className="text-xs text-slate-500">Expires {l.expiresAt ? new Date(l.expiresAt).toLocaleDateString() : "—"}</p></div>{l.status === "active" && <button onClick={()=>cancelLink.mutate(l._id)} className="rounded border p-2 text-red-600"><XCircle size={16}/></button>}</div>)}</div></div><div><h3 className="font-bold">Credit/debit notes</h3><div className="mt-3 space-y-2">{list(notesQ.data).slice(0,8).map(n=><div key={n._id} className="flex items-center justify-between gap-3 rounded-lg border p-3 text-sm"><div><p className="font-semibold">{n.noteNumber} · {n.type}</p><p>{money(n.totalAmount)} · {n.status}</p><p className="text-xs text-slate-500">{n.reason}</p></div>{n.status === "draft" && <div className="flex gap-2"><button onClick={()=>issueNote.mutate(n._id)} className="rounded bg-emerald-700 px-3 py-1 text-xs font-bold text-white">Issue</button><button onClick={()=>cancelNote.mutate(n._id)} className="rounded border px-3 py-1 text-xs">Cancel</button></div>}</div>)}</div></div></div>
  </section>;
}
