import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Copy, Link as LinkIcon, Plus, ReceiptText, RefreshCw, XCircle } from "lucide-react";
import { createPaymentLink, getPaymentLinks, cancelPaymentLink, createCreditDebitNote, getCreditDebitNotes, issueCreditDebitNote, cancelCreditDebitNote } from "../../api/financeLifecycleApi";

const money = (v) => `KES ${Number(v || 0).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const list = (v) => Array.isArray(v) ? v : v?.data || [];
const errorText = (e) => e?.response?.data?.message || e?.message || "The request could not be completed.";

export default function FinanceLifecycleCenter() {
  const qc = useQueryClient(); const [bookingId, setBookingId] = useState(""); const [linkAmount, setLinkAmount] = useState(""); const [invoiceId, setInvoiceId] = useState(""); const [noteType, setNoteType] = useState("credit"); const [noteAmount, setNoteAmount] = useState(""); const [taxAmount, setTaxAmount] = useState("0"); const [reason, setReason] = useState(""); const [createdPath, setCreatedPath] = useState("");
  const linksQ = useQuery({ queryKey: ["finance-payment-links"], queryFn: getPaymentLinks, staleTime: 30000, retry: 2 }); const notesQ = useQuery({ queryKey: ["finance-credit-debit-notes"], queryFn: getCreditDebitNotes, staleTime: 30000, retry: 2 });
  const refresh = () => { qc.invalidateQueries({ queryKey: ["finance-payment-links"] }); qc.invalidateQueries({ queryKey: ["finance-credit-debit-notes"] }); qc.invalidateQueries({ queryKey: ["admin-finance-accounting"] }); };
  const linkMutation = useMutation({ mutationFn: createPaymentLink, onSuccess: (data) => { setCreatedPath(data?.paymentPath || ""); setBookingId(""); setLinkAmount(""); refresh(); } });
  const cancelLink = useMutation({ mutationFn: cancelPaymentLink, onSuccess: refresh });
  const noteMutation = useMutation({ mutationFn: createCreditDebitNote, onSuccess: () => { setInvoiceId(""); setNoteAmount(""); setReason(""); refresh(); } });
  const issueNote = useMutation({ mutationFn: issueCreditDebitNote, onSuccess: refresh }); const cancelNote = useMutation({ mutationFn: cancelCreditDebitNote, onSuccess: refresh });
  const copy = async (text) => { try { await navigator.clipboard.writeText(`${window.location.origin}${text}`); } catch (error) { console.warn("Unable to copy payment link:", error); } };
  return <section className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sky-600">Finance lifecycle</p><h2 className="mt-1 text-2xl font-black text-slate-950">Payment links & credit/debit notes</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">Controlled collections and accounting adjustments with a clear draft → issue lifecycle.</p></div><button onClick={refresh} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50"><RefreshCw size={16}/> Refresh</button></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <form onSubmit={(e)=>{e.preventDefault(); linkMutation.mutate({ bookingId, ...(linkAmount ? { amount: Number(linkAmount) } : {}) });}} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-5"><div className="flex items-center gap-2 font-black text-slate-950"><span className="rounded-xl bg-indigo-50 p-2 text-indigo-700"><LinkIcon size={18}/></span>Create payment link</div><p className="mt-1 text-xs text-slate-500">Create a controlled link against an existing booking.</p><div className="mt-4 space-y-3"><input required value={bookingId} onChange={e=>setBookingId(e.target.value)} placeholder="Booking ID" className="w-full rounded-xl border border-slate-200 bg-white p-2.5"/><input value={linkAmount} onChange={e=>setLinkAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="Amount (blank = full balance)" className="w-full rounded-xl border border-slate-200 bg-white p-2.5"/><button disabled={linkMutation.isPending} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-bold text-white hover:bg-indigo-500 disabled:opacity-50"><Plus size={16}/>{linkMutation.isPending ? "Creating…" : "Create link"}</button>{createdPath && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm"><p className="font-bold text-emerald-800">Payment link created</p><code className="mt-1 block break-all text-emerald-900">{window.location.origin}{createdPath}</code><button type="button" onClick={()=>copy(createdPath)} className="mt-2 inline-flex items-center gap-1 rounded-lg border border-emerald-200 bg-white px-2.5 py-1.5 text-xs font-bold text-emerald-800"><Copy size={13}/>Copy link</button></div>}{linkMutation.isError && <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{errorText(linkMutation.error)}</p>}</div></form>
      <form onSubmit={(e)=>{e.preventDefault(); noteMutation.mutate({ type: noteType, originalInvoice: invoiceId, amount: Number(noteAmount), taxAmount: Number(taxAmount), reason });}} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-5"><div className="flex items-center gap-2 font-black text-slate-950"><span className="rounded-xl bg-violet-50 p-2 text-violet-700"><ReceiptText size={18}/></span>Create credit/debit note</div><p className="mt-1 text-xs text-slate-500">Adjust an original invoice without rewriting its history.</p><div className="mt-4 space-y-3"><input required value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} placeholder="Original invoice ID" className="w-full rounded-xl border border-slate-200 bg-white p-2.5"/><div className="grid grid-cols-2 gap-2"><select value={noteType} onChange={e=>setNoteType(e.target.value)} className="rounded-xl border border-slate-200 bg-white p-2.5"><option value="credit">Credit note</option><option value="debit">Debit note</option></select><input required value={noteAmount} onChange={e=>setNoteAmount(e.target.value)} type="number" min="0.01" step="0.01" placeholder="Net amount" className="rounded-xl border border-slate-200 bg-white p-2.5"/></div><input value={taxAmount} onChange={e=>setTaxAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="Tax amount" className="w-full rounded-xl border border-slate-200 bg-white p-2.5"/><textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason" className="w-full rounded-xl border border-slate-200 bg-white p-2.5"/><button disabled={noteMutation.isPending} className="rounded-xl bg-slate-950 px-4 py-2.5 font-bold text-white hover:bg-slate-800">{noteMutation.isPending ? "Saving…" : "Save draft"}</button>{noteMutation.isError && <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{errorText(noteMutation.error)}</p>}</div></form>
    </div>
    <div className="grid gap-5 xl:grid-cols-2"><ListPanel title="Recent payment links" items={list(linksQ.data)} loading={linksQ.isLoading} empty="No payment links have been created yet." render={(l)=><div key={l._id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4"><div><p className="font-bold text-slate-900">{l.booking?.bookingNumber || l.booking || "Booking"}</p><p className="mt-1 text-sm font-semibold text-slate-700">{money(l.amount)} · <span className="capitalize">{l.status}</span></p><p className="mt-1 text-xs text-slate-400">Expires {l.expiresAt ? new Date(l.expiresAt).toLocaleDateString("en-KE") : "—"}</p></div>{l.status === "active" && <button onClick={()=>cancelLink.mutate(l._id)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><XCircle size={17}/></button>}</div>}/><ListPanel title="Credit/debit notes" items={list(notesQ.data)} loading={notesQ.isLoading} empty="No accounting notes have been created yet." render={(n)=><div key={n._id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4"><div><p className="font-bold text-slate-900">{n.noteNumber} · <span className="capitalize">{n.type}</span></p><p className="mt-1 text-sm font-semibold text-slate-700">{money(n.totalAmount)} · <span className="capitalize">{n.status}</span></p><p className="mt-1 text-xs text-slate-400">{n.reason}</p></div>{n.status === "draft" && <div className="flex gap-2"><button onClick={()=>issueNote.mutate(n._id)} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-bold text-white"><CheckCircle2 size={13}/>Issue</button><button onClick={()=>cancelNote.mutate(n._id)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-600">Cancel</button></div>}</div>}/></div>
  </section>;
}
function ListPanel({ title, items, loading, empty, render }) { return <div><h3 className="font-black text-slate-950">{title}</h3><div className="mt-3 space-y-2">{loading ? <div className="rounded-xl bg-slate-50 p-6 text-sm text-slate-400">Loading…</div> : items.length ? items.slice(0,8).map(render) : <div className="rounded-xl border border-dashed border-slate-200 p-6 text-sm text-slate-400">{empty}</div>}</div></div>; }
