import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Building2, CircleDollarSign, FilePlus2, Handshake, Receipt, Send } from "lucide-react";
import { createCorporateAccount, createPurchaseOrder, createSupplier, createSupplierPayable, createTourCost, paySupplierPayable, reconcileCorporateAccount, transitionPurchaseOrder } from "../../api/operationsModuleApi";

const input = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100";
const btn = "rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-800 disabled:opacity-50";
const money = (v) => Number(v || 0);

export default function OperationsActionCenter({ suppliers = [], purchaseOrders = [], payables = [], corporate = [] }) {
  const qc = useQueryClient();
  const refresh = () => ["operations-suppliers", "operations-purchase-orders", "operations-tour-costs", "operations-payables", "operations-corporate", "operations-overview"].forEach((key) => qc.invalidateQueries({ queryKey: [key] }));
  const [notice, setNotice] = useState("");
  const run = (fn) => ({ mutationFn: fn, onSuccess: () => { setNotice("Saved successfully."); refresh(); }, onError: (e) => setNotice(e?.response?.data?.message || e?.message || "Unable to save record.") });
  const supplierMutation = useMutation(run(createSupplier));
  const corporateMutation = useMutation(run(createCorporateAccount));
  const poMutation = useMutation(run(createPurchaseOrder));
  const costMutation = useMutation(run(createTourCost));
  const payableMutation = useMutation(run(createSupplierPayable));
  const payMutation = useMutation({ mutationFn: ({ id, amount, paymentReference }) => paySupplierPayable(id, amount, paymentReference), onSuccess: () => { setNotice("Supplier payment recorded."); refresh(); }, onError: (e) => setNotice(e?.response?.data?.message || e?.message || "Unable to record payment.") });
  const poStatusMutation = useMutation({ mutationFn: ({ id, status }) => transitionPurchaseOrder(id, status), onSuccess: () => { setNotice("Purchase order status updated."); refresh(); }, onError: (e) => setNotice(e?.response?.data?.message || e?.message || "Unable to update purchase order.") });
  const reconcileMutation = useMutation({ mutationFn: reconcileCorporateAccount, onSuccess: () => { setNotice("Corporate account reconciled."); refresh(); }, onError: (e) => setNotice(e?.response?.data?.message || e?.message || "Unable to reconcile account.") });

  return <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Operations workspace</p><h2 className="text-xl font-bold">Create, update & settle operational records</h2><p className="mt-1 text-sm text-slate-500">The dashboard is not read-only: supplier, procurement, costing, payable and corporate workflows are available here.</p></div>{notice && <div className="rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-600">{notice}</div>}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">
      <FormCard icon={Handshake} title="Add supplier"><Form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); supplierMutation.mutate({ legalName:f.get("legalName"), tradingName:f.get("tradingName"), category:f.get("category"), kraPin:f.get("kraPin"), paymentTermsDays:Number(f.get("paymentTermsDays")||0), status:"active" }); e.currentTarget.reset(); }} busy={supplierMutation.isPending} submit="Create supplier"><Field name="legalName" label="Legal name" required/><Field name="tradingName" label="Trading name"/><Select name="category" label="Category" options={["accommodation","transport","guide","driver","activity","park","airline","restaurant","equipment","other"]}/><Field name="kraPin" label="KRA PIN"/><Field name="paymentTermsDays" label="Payment terms (days)" type="number" min="0"/></Form></FormCard>
      <FormCard icon={Building2} title="Add corporate account"><Form onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); corporateMutation.mutate({ companyName:f.get("companyName"), kraPin:f.get("kraPin"), paymentTerms:f.get("paymentTerms"), creditLimit:Number(f.get("creditLimit")||0), preferredPaymentMethod:f.get("preferredPaymentMethod"), requiresPurchaseOrder:f.get("requiresPurchaseOrder")==="on", status:"active" }); e.currentTarget.reset(); }} busy={corporateMutation.isPending} submit="Create account"><Field name="companyName" label="Company name" required/><Field name="kraPin" label="KRA PIN"/><Select name="paymentTerms" label="Payment terms" options={["immediate","7_days","14_days","30_days","60_days","90_days","staged"]}/><Field name="creditLimit" label="Credit limit (KES)" type="number" min="0"/><Select name="preferredPaymentMethod" label="Preferred payment" options={["BANK_TRANSFER","MPESA","CARD","CASH"]}/><label className="flex items-center gap-2 text-sm"><input name="requiresPurchaseOrder" type="checkbox"/> Require purchase order</label></Form></FormCard>
      <FormCard icon={FilePlus2} title="Create purchase order"><Form onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); const quantity=Number(f.get("quantity")||1); const unitCost=Number(f.get("unitCost")||0); poMutation.mutate({ supplier:f.get("supplier"), tour:f.get("tour")||null, booking:f.get("booking")||null, expectedDate:f.get("expectedDate")||null, notes:f.get("notes"), lines:[{ description:f.get("description"), quantity, unitCost, taxRate:Number(f.get("taxRate")||0), taxType:"standard" }] }); e.currentTarget.reset(); }} busy={poMutation.isPending} submit="Create PO"><Select name="supplier" label="Supplier" required options={suppliers.map(s=>s._id)} labels={suppliers.reduce((a,s)=>(a[s._id]=s.legalName,a),{})}/><Field name="tour" label="Tour ID (optional)"/><Field name="booking" label="Booking ID (optional)"/><Field name="expectedDate" label="Expected date" type="date"/><Field name="description" label="Line description" required/><div className="grid grid-cols-3 gap-2"><Field name="quantity" label="Qty" type="number" min="0.001" step="0.001" defaultValue="1"/><Field name="unitCost" label="Unit cost" type="number" min="0" step="0.01" required/><Field name="taxRate" label="Tax %" type="number" min="0" max="100" step="0.01" defaultValue="0"/></div><p className="rounded-lg bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600">Total cost is calculated server-side from quantity, unit cost and tax.</p><Field name="notes" label="Notes"/></Form></FormCard>
      <FormCard icon={CircleDollarSign} title="Record tour cost"><Form onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); costMutation.mutate({ tour:f.get("tour"), booking:f.get("booking")||null, category:f.get("category"), description:f.get("description"), supplier:f.get("supplier")||null, quantity:Number(f.get("quantity")||1), unitCost:Number(f.get("unitCost")||0), taxAmount:Number(f.get("taxAmount")||0), costDate:f.get("costDate")||undefined, status:f.get("status") }); e.currentTarget.reset(); }} busy={costMutation.isPending} submit="Record cost"><Field name="tour" label="Tour ID" required/><Field name="booking" label="Booking ID (optional)"/><Select name="category" label="Cost category" options={["accommodation","transport","guide","driver","activity","supplier","park","meals","miscellaneous"]}/><Field name="description" label="Description" required/><Select name="supplier" label="Supplier (optional)" options={["",...suppliers.map(s=>s._id)]} labels={suppliers.reduce((a,s)=>(a[s._id]=s.legalName,a),{})}/><div className="grid grid-cols-3 gap-2"><Field name="quantity" label="Qty" type="number" min="0" step="0.001" defaultValue="1"/><Field name="unitCost" label="Unit cost" type="number" min="0" step="0.01" required/><Field name="taxAmount" label="Tax" type="number" min="0" step="0.01" defaultValue="0"/></div><div className="grid grid-cols-2 gap-2"><Field name="costDate" label="Cost date" type="date"/><Select name="status" label="Status" options={["estimated","committed","actual","cancelled"]}/></div></Form></FormCard>
      <FormCard icon={Receipt} title="Create supplier payable"><Form onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); payableMutation.mutate({ supplier:f.get("supplier"), purchaseOrder:f.get("purchaseOrder")||null, tour:f.get("tour")||null, amount:Number(f.get("amount")||0), dueDate:f.get("dueDate")||null, notes:f.get("notes") }); e.currentTarget.reset(); }} busy={payableMutation.isPending} submit="Create payable"><Select name="supplier" label="Supplier" required options={suppliers.map(s=>s._id)} labels={suppliers.reduce((a,s)=>(a[s._id]=s.legalName,a),{})}/><Field name="purchaseOrder" label="PO ID (optional)"/><Field name="tour" label="Tour ID (optional)"/><Field name="amount" label="Amount (KES)" type="number" min="0" step="0.01" required/><Field name="dueDate" label="Due date" type="date"/><Field name="notes" label="Notes"/></Form></FormCard>
      <FormCard icon={Send} title="Settle payable / PO / corporate"><div className="space-y-4"><PayableAction payables={payables} onPay={(v)=>payMutation.mutate(v)} busy={payMutation.isPending}/><StatusAction rows={purchaseOrders} onChange={(v)=>poStatusMutation.mutate(v)} busy={poStatusMutation.isPending}/><CorporateAction rows={corporate} onReconcile={(id)=>reconcileMutation.mutate(id)} busy={reconcileMutation.isPending}/></div></FormCard>
    </div>
  </section>;
}
function FormCard({icon:Icon,title,children}){return <div className="rounded-2xl border border-slate-200 p-5"><div className="mb-4 flex items-center gap-2"><Icon size={18} className="text-emerald-700"/><h3 className="font-bold">{title}</h3></div>{children}</div>}
function Form({children,onSubmit,busy,submit}){return <form onSubmit={onSubmit} className="space-y-3">{children}<button className={btn} disabled={busy}>{busy?"Saving…":submit}</button></form>}
function Field({name,label,type="text",required,min,step,defaultValue}){return <label className="block text-xs font-semibold text-slate-600">{label}<input className={input} name={name} type={type} required={required} min={min} step={step} defaultValue={defaultValue}/></label>}
function Select({name,label,options,labels={},required}){return <label className="block text-xs font-semibold text-slate-600">{label}<select className={input} name={name} required={required} defaultValue={options[0]}>{options.map(v=><option key={v} value={v}>{labels[v]||v.replaceAll("_"," ")}</option>)}</select></label>}
function PayableAction({payables,onPay,busy}){const [id,setId]=useState(""); const [amount,setAmount]=useState(""); const [ref,setRef]=useState(""); return <div className="rounded-xl bg-slate-50 p-4"><p className="mb-2 text-sm font-bold">Record supplier payment</p><select className={input} value={id} onChange={e=>{setId(e.target.value);const p=payables.find(x=>x._id===e.target.value);setAmount(p?.balance||"")}}><option value="">Select payable</option>{payables.filter(p=>Number(p.balance||0)>0).map(p=><option key={p._id} value={p._id}>{p.payableNumber||p._id.slice(-8)} · {p.supplier?.legalName||"Supplier"} · KES {money(p.balance).toLocaleString()}</option>)}</select><div className="mt-2 grid grid-cols-2 gap-2"><input className={input} type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount"/><input className={input} value={ref} onChange={e=>setRef(e.target.value)} placeholder="Payment reference"/></div><button type="button" className={`mt-2 ${btn}`} disabled={!id||!amount||busy} onClick={()=>onPay({id,amount:Number(amount),paymentReference:ref})}>Record payment</button></div>}
function StatusAction({rows,onChange,busy}){const [id,setId]=useState(""); const [status,setStatus]=useState("submitted"); return <div className="rounded-xl bg-slate-50 p-4"><p className="mb-2 text-sm font-bold">Update purchase order status</p><select className={input} value={id} onChange={e=>setId(e.target.value)}><option value="">Select purchase order</option>{rows.map(x=><option key={x._id} value={x._id}>{x.poNumber||x._id.slice(-8)} · {x.supplier?.legalName||"Supplier"}</option>)}</select><div className="mt-2 flex gap-2"><select className={input} value={status} onChange={e=>setStatus(e.target.value)}>{["draft","submitted","approved","partially_received","received","cancelled"].map(x=><option key={x}>{x}</option>)}</select><button type="button" className={btn} disabled={!id||busy} onClick={()=>onChange({id,status})}>Update</button></div></div>}
function CorporateAction({rows,onReconcile,busy}){const [id,setId]=useState(""); return <div className="rounded-xl bg-slate-50 p-4"><p className="mb-2 text-sm font-bold">Reconcile corporate account</p><select className={input} value={id} onChange={e=>setId(e.target.value)}><option value="">Select corporate account</option>{rows.map(x=><option key={x._id} value={x._id}>{x.companyName} · KES {money(x.currentBalance).toLocaleString()}</option>)}</select><button type="button" className={`mt-2 ${btn}`} disabled={!id||busy} onClick={()=>onReconcile(id)}>Reconcile balance</button></div>}
