import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, CreditCard, EyeOff, KeyRound, Save, ShieldCheck, Smartphone, Trash2 } from "lucide-react";
import { toast } from "react-toastify";
import { disablePaymentGateway, listPaymentGateways, savePaymentGateway } from "../../api/paymentGatewayApi";

const PROVIDERS = [
  { id: "MPESA", name: "M-Pesa", icon: Smartphone, help: "Safaricom Daraja credentials, shortcode and callback configuration." },
  { id: "STRIPE", name: "Stripe", icon: CreditCard, help: "Stripe account and publishable-key configuration." },
  { id: "PAYPAL", name: "PayPal", icon: CreditCard, help: "PayPal merchant configuration." },
  { id: "PESAPAL", name: "Pesapal", icon: CreditCard, help: "Pesapal merchant configuration." },
  { id: "BANK", name: "Bank transfer", icon: CreditCard, help: "Bank settlement instructions for offline payment." },
];
const secretFields = ["consumerKey", "consumerSecret", "passkey", "secretKey", "webhookSecret", "initiatorName", "securityCredential"];

export default function PaymentGatewayCenter() {
  const qc = useQueryClient();
  const [provider, setProvider] = useState("MPESA");
  const [form, setForm] = useState({ environment: "sandbox", enabled: false, accountName: "", shortcode: "", publicKey: "", merchantId: "", callbackUrl: "", consumerKey: "", consumerSecret: "", passkey: "", secretKey: "", webhookSecret: "", initiatorName: "", securityCredential: "" });
  const query = useQuery({ queryKey: ["payment-gateways"], queryFn: listPaymentGateways });
  const configs = query.data?.data || query.data || [];
  const current = useMemo(() => configs.find((x) => x.provider === provider), [configs, provider]);

  const selectProvider = (id) => { setProvider(id); const item = configs.find((x) => x.provider === id); setForm((f) => ({ ...f, environment: item?.environment || "sandbox", enabled: Boolean(item?.enabled), accountName: item?.accountName || "", shortcode: item?.shortcode || "", publicKey: item?.publicKey || "", merchantId: item?.merchantId || "", callbackUrl: item?.callbackUrl || "", ...Object.fromEntries(secretFields.map((k) => [k, ""])) })); };
  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  const save = useMutation({ mutationFn: () => savePaymentGateway(provider, form), onSuccess: () => { qc.invalidateQueries({ queryKey: ["payment-gateways"] }); toast.success(`${provider} gateway configuration saved securely.`); setForm((f) => Object.fromEntries(Object.entries(f).map(([k, v]) => [k, secretFields.includes(k) ? "" : v]))); }, onError: (e) => toast.error(e?.response?.data?.message || "Unable to save payment gateway.") });
  const disable = useMutation({ mutationFn: () => disablePaymentGateway(provider), onSuccess: () => { qc.invalidateQueries({ queryKey: ["payment-gateways"] }); set("enabled", false); toast.success(`${provider} gateway disabled.`); }, onError: (e) => toast.error(e?.response?.data?.message || "Unable to disable gateway.") });

  return <section className="mt-6 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Tenant payment infrastructure</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-bold"><ShieldCheck size={22}/> Payment gateways</h2><p className="mt-1 max-w-3xl text-sm text-slate-500">Configure encrypted, tenant-specific provider credentials. Secret values are never returned to the browser after they are saved.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{current?.enabled ? "Enabled" : "Disabled"}</span></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[230px_1fr]"><div className="space-y-2">{PROVIDERS.map(({ id, name, icon: Icon }) => <button key={id} type="button" onClick={() => selectProvider(id)} className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left font-semibold ${provider === id ? "border-emerald-600 bg-emerald-50 text-emerald-800" : "border-slate-200 hover:bg-slate-50"}`}><Icon size={18}/>{name}{configs.some((x) => x.provider === id && x.enabled) && <CheckCircle2 size={15} className="ml-auto"/>}</button>)}</div>
      <div className="rounded-2xl border border-slate-200 p-5"><div className="mb-5"><h3 className="text-lg font-bold">{PROVIDERS.find((x) => x.id === provider)?.name}</h3><p className="text-sm text-slate-500">{PROVIDERS.find((x) => x.id === provider)?.help}</p></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Environment<select value={form.environment} onChange={(e) => set("environment", e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="sandbox">Sandbox</option><option value="production">Production</option></select></label><label className="flex items-center gap-3 pt-6 text-sm font-semibold"><input type="checkbox" checked={form.enabled} onChange={(e) => set("enabled", e.target.checked)} className="h-4 w-4"/> Enable this gateway</label><label className="text-sm font-semibold">Account / merchant name<input value={form.accountName} onChange={(e) => set("accountName", e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-semibold">Shortcode / merchant code<input value={form.shortcode} onChange={(e) => set("shortcode", e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-semibold">Merchant ID<input value={form.merchantId} onChange={(e) => set("merchantId", e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-semibold">Public key<input value={form.publicKey} onChange={(e) => set("publicKey", e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-semibold md:col-span-2">Callback URL<input type="url" value={form.callbackUrl} onChange={(e) => set("callbackUrl", e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label></div>
        <div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2 font-bold"><KeyRound size={17}/> Secure credentials</div><p className="mt-1 text-xs text-slate-500">Leave an existing secret blank to keep the encrypted value already stored.</p><div className="mt-3 grid gap-4 md:grid-cols-2">{secretFields.map((key) => <label key={key} className="text-sm font-semibold capitalize">{key.replace(/([A-Z])/g, " $1")} {current?.secretsConfigured?.[key] && <span className="text-emerald-700">(configured)</span>}<div className="relative mt-1"><input type="password" autoComplete="new-password" value={form[key]} onChange={(e) => set(key, e.target.value)} className="w-full rounded-xl border px-3 py-2 pr-10"/><EyeOff size={16} className="pointer-events-none absolute right-3 top-3 text-slate-400"/></div></label>)}</div></div>
        <div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={save.isPending} onClick={() => save.mutate()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50"><Save size={17}/> {save.isPending ? "Saving..." : "Save securely"}</button>{current?.configured && <button type="button" disabled={disable.isPending || !current.enabled} onClick={() => disable.mutate()} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-5 py-2.5 font-semibold text-red-700 disabled:opacity-40"><Trash2 size={17}/> Disable gateway</button>}</div>
      </div></div>
  </section>;
}
