import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CalendarClock, Car, ClipboardList, FileText, Hotel, ShieldCheck, Plane } from "lucide-react";
import { createTravelServiceRequest, getTravelServiceRequests, getTravelServiceSummary, updateTravelServiceRequest } from "../../api/travelServiceRequestApi";

const types = [
  ["airport_transfer", "Airport transfer", Plane], ["accommodation", "Accommodation", Hotel], ["rooming_list", "Rooming list", ClipboardList],
  ["travel_document", "Travel documents", FileText], ["insurance", "Travel insurance", ShieldCheck], ["manifest", "Trip manifest", ClipboardList],
  ["incident", "Incident / emergency", AlertTriangle], ["schedule", "Schedule / staffing", CalendarClock], ["cancellation", "Cancellation request", FileText], ["special_service", "Special service", Car],
];
const input = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100";
const btn = "rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-800 disabled:opacity-50";
const labelFor = (value) => types.find(([id]) => id === value)?.[1] || String(value || "").replaceAll("_", " ");

export default function TravelServiceDesk() {
  const qc = useQueryClient();
  const [filter, setFilter] = useState("");
  const [status, setStatus] = useState("");
  const [notice, setNotice] = useState("");
  const { data: listResponse, isLoading } = useQuery({ queryKey: ["travel-service-requests", filter, status], queryFn: () => getTravelServiceRequests({ type: filter || undefined, status: status || undefined }), refetchInterval: 60000 });
  const { data: summaryResponse } = useQuery({ queryKey: ["travel-service-summary"], queryFn: getTravelServiceSummary, refetchInterval: 60000 });
  const rows = useMemo(() => listResponse?.data?.data || listResponse?.data || [], [listResponse]);
  const summary = summaryResponse?.data?.data || {};
  const createMutation = useMutation({ mutationFn: createTravelServiceRequest, onSuccess: () => { setNotice("Service request created."); qc.invalidateQueries({ queryKey: ["travel-service-requests"] }); qc.invalidateQueries({ queryKey: ["travel-service-summary"] }); }, onError: e => setNotice(e?.response?.data?.message || e?.message || "Unable to create request.") });
  const updateMutation = useMutation({ mutationFn: ({ id, payload }) => updateTravelServiceRequest(id, payload), onSuccess: () => { setNotice("Request updated."); qc.invalidateQueries({ queryKey: ["travel-service-requests"] }); qc.invalidateQueries({ queryKey: ["travel-service-summary"] }); }, onError: e => setNotice(e?.response?.data?.message || e?.message || "Unable to update request.") });
  const submit = (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); createMutation.mutate({ type: f.get("type"), title: f.get("title"), description: f.get("description"), requestedDate: f.get("requestedDate") || undefined, dueDate: f.get("dueDate") || undefined, priority: f.get("priority"), location: f.get("location"), contactPhone: f.get("contactPhone"), booking: f.get("booking") || undefined, metadata: { flightNumber: f.get("flightNumber"), pickupTime: f.get("pickupTime"), roomingReference: f.get("roomingReference"), documentType: f.get("documentType"), incidentSeverity: f.get("incidentSeverity") } }); e.currentTarget.reset(); };
  return <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Field & guest services</p><h2 className="text-xl font-bold">Service desk & trip operations</h2><p className="mt-1 text-sm text-slate-500">Manage transfers, accommodation, rooming lists, manifests, documents, insurance, incidents, scheduling and cancellations in one tenant-scoped queue.</p></div>{notice && <div className="rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-600">{notice}</div>}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Open" value={summary.byStatus?.find(x => x._id === "open")?.count || 0}/><Stat label="In progress" value={summary.byStatus?.find(x => x._id === "in_progress")?.count || 0}/><Stat label="Resolved" value={summary.byStatus?.find(x => x._id === "resolved")?.count || 0}/><Stat label="Urgent" value={summary.urgent || 0}/></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]">
      <form onSubmit={submit} className="rounded-2xl border border-slate-200 p-5 space-y-3"><h3 className="font-bold">Create service request</h3><Field name="title" label="Title" required/><Select name="type" label="Service type" options={types.map(x => x[0])} labels={Object.fromEntries(types.map(x => [x[0], x[1]]))}/><Select name="priority" label="Priority" options={["normal","low","high","urgent"]}/><Field name="booking" label="Booking ID (optional)"/><Field name="requestedDate" label="Requested date" type="date"/><Field name="dueDate" label="Due date" type="date"/><Field name="location" label="Location / pickup point"/><Field name="contactPhone" label="Contact phone"/><Field name="flightNumber" label="Flight number (optional)"/><Field name="pickupTime" label="Pickup time (optional)"/><Field name="roomingReference" label="Rooming-list reference (optional)"/><Field name="documentType" label="Document type (optional)"/><Select name="incidentSeverity" label="Incident severity" options={["","low","medium","high","critical"]}/><label className="block text-xs font-semibold text-slate-600">Description<textarea name="description" rows="4" className={input}/></label><button className={btn} disabled={createMutation.isPending}>{createMutation.isPending ? "Saving…" : "Create request"}</button></form>
      <div><div className="flex flex-wrap gap-2"><select className={`${input} max-w-xs`} value={filter} onChange={e => setFilter(e.target.value)}><option value="">All service types</option>{types.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select><select className={`${input} max-w-xs`} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{["open","in_progress","awaiting_customer","resolved","cancelled"].map(x => <option key={x}>{x.replaceAll("_", " ")}</option>)}</select></div><div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Type</th><th className="p-3 text-left">Request</th><th className="p-3 text-left">Date</th><th className="p-3 text-left">Priority</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Action</th></tr></thead><tbody>{isLoading ? <tr><td colSpan="6" className="p-8 text-center">Loading service requests…</td></tr> : rows.map(row => <RequestRow key={row._id} row={row} busy={updateMutation.isPending} onUpdate={(payload) => updateMutation.mutate({ id: row._id, payload })}/>)}{!isLoading && !rows.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">No service requests.</td></tr>}</tbody></table></div></div>
    </div>
  </section>;
}
function RequestRow({ row, onUpdate, busy }) { return <tr className="border-t"><td className="p-3 capitalize">{labelFor(row.type)}</td><td className="p-3"><div className="font-semibold">{row.title}</div><div className="text-xs text-slate-500">{row.description || "No description"}</div></td><td className="p-3">{row.requestedDate ? new Date(row.requestedDate).toLocaleDateString() : "—"}</td><td className="p-3 capitalize">{row.priority}</td><td className="p-3 capitalize">{row.status?.replaceAll("_", " ")}</td><td className="p-3"><select disabled={busy} className="rounded-lg border border-slate-200 px-2 py-1" value={row.status} onChange={e => onUpdate({ status: e.target.value })}>{["open","in_progress","awaiting_customer","resolved","cancelled"].map(x => <option key={x}>{x}</option>)}</select></td></tr>; }
function Stat({ label, value }) { return <div className="rounded-xl border border-slate-200 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>; }
function Field({ name, label, type="text", required }) { return <label className="block text-xs font-semibold text-slate-600">{label}<input name={name} type={type} required={required} className={input}/></label>; }
function Select({ name, label, options, labels={} }) { return <label className="block text-xs font-semibold text-slate-600">{label}<select name={name} className={input}>{options.map(x => <option key={x} value={x}>{labels[x] || x.replaceAll("_", " ") || "Not specified"}</option>)}</select></label>; }
