import "dotenv/config";
import mongoose from "mongoose";
import Booking from "../models/Booking.js";
import Tour from "../models/Tour.js";
import Customer from "../models/Customer.js";
import User from "../models/User.js";
import Organization from "../models/Organization.js";
import { runWithTenant } from "../tenancy/context.js";

const TARGET_COUNT = Math.max(10, Number(process.env.TEST_SEED_COUNT || 10));
const ALLOW_TEST_SEED = String(process.env.ALLOW_TEST_SEED || "false").toLowerCase() === "true";

async function main() {
  if (!ALLOW_TEST_SEED) throw new Error("Refusing to seed without ALLOW_TEST_SEED=true.");
  const mongoUri = process.env.MONGODB_URI;
  if (!mongoUri) throw new Error("MONGODB_URI is missing.");

  await mongoose.connect(mongoUri);

  const tenant = await runWithTenant({ role: "super_admin", bypass: true }, async () =>
    Organization.findOne({ status: "active" }).sort({ createdAt: 1 }).lean()
  );
  if (!tenant?._id) throw new Error("No active test organization is available.");

  const work = async () => {
    const tours = await Tour.find({ isDeleted: false }).sort({ createdAt: 1 }).limit(TARGET_COUNT).lean();
    if (!tours.length) throw new Error("No tours are available for valid booking fixtures.");

    const customers = await Customer.find({}).sort({ createdAt: 1 }).limit(TARGET_COUNT).lean();
    const users = await User.find({ status: "active" }).sort({ createdAt: 1 }).limit(TARGET_COUNT).lean();

    const existing = await Booking.countDocuments({});
    if (existing >= TARGET_COUNT) {
      return { created: 0, count: existing, tours: tours.length };
    }

    let created = 0;
    for (let index = existing; index < TARGET_COUNT; index += 1) {
      const tour = tours[index % tours.length];
      const customer = customers[index % Math.max(1, customers.length)] || null;
      const user = users[index % Math.max(1, users.length)] || null;
      const guests = 1 + (index % 4);
      const total = Number(tour.price || 1500) * guests;
      const deposit = Math.round(total * 0.5);
      const booking = new Booking({
        tour: tour._id,
        customer: customer?._id || undefined,
        user: user?._id || undefined,
        contact: {
          name: customer?.name || user?.name || `Test Traveler ${index + 1}`,
          email: customer?.email || user?.email || `traveler${index + 1}@example.test`,
          phone: customer?.phone || user?.phone || `254700${String(index + 1).padStart(6, "0")}`,
        },
        travelDate: new Date(Date.now() + (10 + index) * 86400000),
        travelers: Array.from({ length: guests }, (_, travelerIndex) => ({
          name: `Traveler ${index + 1}-${travelerIndex + 1}`,
          age: 24 + ((index + travelerIndex) % 30),
          gender: travelerIndex % 2 === 0 ? "male" : "female",
          nationality: "Kenyan",
          passportNumber: `TEST${String(index + 1).padStart(4, "0")}${travelerIndex + 1}`,
          emergencyContactName: "Test Emergency Contact",
          emergencyContactPhone: "254711000000",
          dietaryRequirements: "None",
          medicalConditions: "None",
        })),
        numberOfGuests: guests,
        pickupLocation: "Nairobi CBD",
        hotelName: `Test Hotel ${index + 1}`,
        specialRequests: ["Synthetic test booking for QA"],
        subtotal: total,
        totalAmount: total,
        depositAmount: deposit,
        balanceAmount: total - deposit,
        paymentMethod: index % 2 === 0 ? "MPESA" : "CARD",
        paymentStatus: "partial",
        paymentReference: `TEST-BOOKING-${String(index + 1).padStart(4, "0")}`,
        status: index % 3 === 0 ? "confirmed" : "pending",
        bookingSource: "admin",
        customerNotes: "Synthetic test record generated by comprehensive test data seed.",
        staffNotes: "Safe test fixture.",
        isDeleted: false,
      });
      await booking.save();
      created += 1;
    }

    return { created, count: await Booking.countDocuments({}), tours: tours.length };
  };

  const result = await runWithTenant({ tenantId: tenant._id, role: "admin" }, work);
  console.log(JSON.stringify({
    success: true,
    tenantId: String(tenant._id),
    ...result,
    targetCount: TARGET_COUNT,
    message: "Valid tour-backed booking fixtures are ready for the comprehensive test seed."
  }, null, 2));
}

main()
  .catch((error) => {
    console.error("Booking bootstrap failed:", error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.connection.close().catch(() => {});
  });
