import { useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, CheckCircle2, Eye, RefreshCw, Search, Clock3, CreditCard } from "lucide-react";
import useAgentBookings from "../../hooks/useAgentBookings";

const money = (value) => { const n = Number(value); return Number.isFinite(n) ? `KES ${n.toLocaleString("en-KE")}` : "—"; };
const nameOf = (booking) => booking?.customer?.name || [booking?.customer?.firstName, booking?.customer?.lastName].filter(Boolean).join(" ") || booking?.customerSnapshot?.name || booking?.contact?.name || "Customer unavailable";
const tourOf = (booking) => booking?.tourPackage?.title || booking?.tour?.title || booking?.tour?.name || "Tour unavailable";
const statusOf = (booking) => String(booking?.bookingStatus || booking?.status || "unknown").toLowerCase();
const paymentOf = (booking) => String(booking?.paymentStatus || "unknown").toLowerCase();
const formatDate = (value) => { if (!value) return "—"; const d = new Date(value); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString("en-KE", { day: "2-digit", month: "2-digit", year: "numeric" }); };
const statusTone = (status) => { if (["completed", "confirmed", "paid", "approved"].includes(status)) return "bg-emerald-50 text-emerald-700 ring-emerald-200"; if (["pending", "processing"].includes(status)) return "bg-amber-50 text-amber-700 ring-amber-200"; if (["cancelled", "canceled", "refunded", "failed"].includes(status)) return "bg-rose-50 text-rose-700 ring-rose-200"; return "bg-slate-100 text-slate-600 ring-slate-200"; };
const iconTone = { indigo: "bg-indigo-50 text-indigo-700", emerald: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700", violet: "bg-violet-50 text-violet-700" };
const label = (status) => status.replace(/[_-]/g, " ").replace(/\b\w/g, (x) => x.toUpperCase());

export default function AgentBookings() {
  const query = useAgentBookings({ page: 1, limit: 100 });
  const data = Array.isArray(query.data) ? query.data : [];
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [payment, setPayment] = useState("all");
  const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return data.filter((b) => { const s = statusOf(b); const p = paymentOf(b); const matchesSearch = !term || [nameOf(b), tourOf(b), b?.bookingNumber, b?._id, b?.contact?.phone].some((v) => String(v || "").toLowerCase().includes(term)); return matchesSearch && (status === "all" || s === status) && (payment === "all" || p === payment); }); }, [data, search, status, payment]);
  const stats = useMemo(() => ({ total: data.length, completed: data.filter((b) => statusOf(b) === "completed").length, pending: data.filter((b) => ["pending", "processing"].includes(statusOf(b))).length, paid: data.filter((b) => paymentOf(b) === "paid").length }), [data]);

  if (query.isLoading) return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-32 rounded-3xl bg-slate-200"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map((i)=><div key={i} className="h-28 rounded-2xl bg-white"/>)}</div><div className="h-96 rounded-2xl bg-white"/></div></div>;
  if (query.isError) return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-4xl rounded-3xl border border-rose-200 bg-white p-8"><AlertTriangle className="h-7 w-7 text-rose-600"/><h1 className="mt-4 text-2xl font-bold text-slate-900">Booking data unavailable</h1><p className="mt-2 text-sm text-slate-600">The API request failed, so this page will not present a false empty booking list.</p><p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{query.error?.response?.data?.message || query.error?.message || "Unable to load agent bookings."}</p><button type="button" onClick={() => query.refetch()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/> Retry</button></div></div>;

  return <section className="min-h-full bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-300">Sales operations</p><h1 className="mt-2 text-3xl font-black">My Bookings</h1><p className="mt-2 text-sm text-slate-300">Review bookings attributed to your agent account without hiding unavailable data.</p></div><button type="button" onClick={() => query.refetch()} disabled={query.isFetching} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-bold hover:bg-white/15 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`}/> Refresh</button></div></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Bookings",stats.total,CalendarDays,"indigo"],["Completed",stats.completed,CheckCircle2,"emerald"],["Pending",stats.pending,Clock3,"amber"],["Paid",stats.paid,CreditCard,"violet"]].map(([l,v,I,c])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{l}</p><p className="mt-2 text-3xl font-black text-slate-950">{v}</p></div><div className={`rounded-xl p-3 ${iconTone[c]}`}><I className="h-5 w-5"/></div></div></div>)}</div>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search customer, tour, booking number or phone..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-50"/></label><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="all">All booking statuses</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="refunded">Refunded</option></select><select value={payment} onChange={(e)=>setPayment(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="all">All payment states</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></div><p className="mt-3 text-xs text-slate-500">Showing {filtered.length} of {data.length} bookings</p></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Tour</th><th className="px-4 py-3">Travel date</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"/></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan="7" className="px-4 py-10 text-center text-slate-500">No bookings match the current filters.</td></tr> : filtered.map((booking)=><tr key={booking._id || booking.id} className="border-t border-slate-100 hover:bg-indigo-50/40"><td className="px-4 py-3 font-semibold text-slate-800">{nameOf(booking)}</td><td className="px-4 py-3 text-slate-700">{tourOf(booking)}</td><td className="whitespace-nowrap px-4 py-3 text-slate-600">{formatDate(booking.travelDate)}</td><td className="whitespace-nowrap px-4 py-3 font-bold text-indigo-700">{money(booking.totalAmount ?? booking.amount)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ring-1 ${statusTone(paymentOf(booking))}`}>{label(paymentOf(booking))}</span></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ring-1 ${statusTone(statusOf(booking))}`}>{label(statusOf(booking))}</span></td><td className="px-4 py-3 text-right"><button type="button" onClick={()=>setSelected(booking)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:border-indigo-300 hover:text-indigo-700"><Eye className="h-4 w-4"/> View</button></td></tr>)}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" onClick={(e)=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Booking details</p><h2 className="mt-1 text-xl font-bold text-slate-900">{selected.bookingNumber || selected._id || "Booking"}</h2></div><button type="button" onClick={()=>setSelected(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100">×</button></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Customer</dt><dd className="font-semibold">{nameOf(selected)}</dd></div><div><dt className="text-slate-500">Tour</dt><dd className="font-semibold">{tourOf(selected)}</dd></div><div><dt className="text-slate-500">Travel date</dt><dd className="font-semibold">{formatDate(selected.travelDate)}</dd></div><div><dt className="text-slate-500">Amount</dt><dd className="font-semibold text-indigo-700">{money(selected.totalAmount ?? selected.amount)}</dd></div></dl></div></div>}
  </div></section>;
}
