import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Eye, Package, RefreshCw, X } from "lucide-react";
import { getPackageDetails, getPackages } from "../../api/packageApi";

const normalizePackages = (data) => Array.isArray(data) ? data : data?.packages || data?.data?.packages || data?.data || [];
const packageIdOf = (pkg) => pkg?._id || pkg?.id;

export default function AgentPackages() {
  const { packageId } = useParams();
  const [selected, setSelected] = useState(null);
  const listQuery = useQuery({ queryKey: ["agent-packages"], queryFn: getPackages, enabled: !packageId });
  const detailQuery = useQuery({ queryKey: ["agent-package", packageId], queryFn: () => getPackageDetails(packageId), enabled: Boolean(packageId) });
  const packages = normalizePackages(listQuery.data);
  const detail = detailQuery.data?.package || detailQuery.data?.data?.package || detailQuery.data?.data || detailQuery.data;

  if (packageId) return <div className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-4xl space-y-5"><Link to="/agent/packages" className="inline-flex items-center gap-2 font-semibold text-emerald-700"><ArrowLeft size={17}/> Back to packages</Link>{detailQuery.isLoading ? <div className="rounded-2xl bg-white p-8">Loading package details...</div> : detailQuery.isError || !detail ? <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">Unable to load this package.</div> : <article className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h1 className="text-3xl font-bold">{detail.name || detail.title || "Tour package"}</h1><p className="mt-3 text-slate-600">{detail.description || "No description provided."}</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><Info label="Price" value={detail.price ? `KES ${Number(detail.price).toLocaleString()}` : "Contact for price"}/><Info label="Duration" value={detail.duration || detail.durationDays ? `${detail.duration || detail.durationDays} days` : "Flexible"}/><Info label="Status" value={detail.status || "Published"}/></div><div className="mt-6 rounded-xl bg-slate-50 p-4"><h2 className="font-semibold">Package details</h2><pre className="mt-3 max-h-80 overflow-auto text-xs">{JSON.stringify(detail, null, 2)}</pre></div></article>}</div></div>;

  return <div className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold">Tour Packages</h1><p className="mt-1 text-slate-500">Browse packages available to your agency and use them when preparing quotes.</p></div><button onClick={() => listQuery.refetch()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 font-semibold" disabled={listQuery.isFetching}><RefreshCw className={listQuery.isFetching ? "animate-spin" : ""} size={17}/> {listQuery.isFetching ? "Refreshing..." : "Refresh"}</button></header>
    {listQuery.isLoading && <div className="rounded-2xl bg-white p-8 shadow-sm">Loading packages...</div>}
    {listQuery.isError && <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">Unable to load packages.</div>}
    {!listQuery.isLoading && !listQuery.isError && !packages.length && <div className="rounded-2xl bg-white p-10 text-center shadow-sm"><Package className="mx-auto" size={34}/><h2 className="mt-3 font-bold">No packages available</h2><p className="mt-1 text-slate-500">Published packages will appear here.</p></div>}
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{packages.map((pkg) => <article key={packageIdOf(pkg)} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-lg font-bold">{pkg.name || pkg.title || "Tour package"}</h2><p className="mt-2 line-clamp-3 text-sm text-slate-500">{pkg.description || "Package details are available from the package record."}</p><div className="mt-4 flex justify-between text-sm"><span>{pkg.duration || pkg.durationDays ? `${pkg.duration || pkg.durationDays} days` : "Flexible duration"}</span><strong>{pkg.price ? `KES ${Number(pkg.price).toLocaleString()}` : "Contact for price"}</strong></div><button type="button" onClick={() => setSelected(pkg)} className="mt-4 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50"><Eye size={15}/> View / Details</button></article>)}</div>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-bold">{selected.name || selected.title || "Package Details"}</h2><p className="text-sm text-slate-500">{selected.description || ""}</p></div><button type="button" onClick={() => setSelected(null)} aria-label="Close" className="rounded-lg p-2 hover:bg-slate-100"><X size={20}/></button></div><div className="p-5"><pre className="max-h-96 overflow-auto rounded-lg bg-slate-50 p-4 text-xs">{JSON.stringify(selected, null, 2)}</pre><Link to={`/agent/packages/${packageIdOf(selected)}`} className="mt-4 inline-flex rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Open full details</Link></div></div></div>}
  </div></div>;
}
function Info({ label, value }) { return <div className="rounded-xl bg-slate-50 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 font-semibold">{value || "Not available"}</div></div>; }
