import { useMemo, useState } from "react";
import { AlertTriangle, Eye, Phone, RefreshCw, Search, UserRound, Users } from "lucide-react";
import useAgentCustomers from "../../hooks/useAgentCustomers";

const fullName = (customer) => customer?.name || [customer?.firstName, customer?.lastName].filter(Boolean).join(" ") || customer?.user?.name || "Customer unavailable";
const statusOf = (customer) => String(customer?.status || "active").toLowerCase();
const statusTone = (status) => status === "active" ? "bg-emerald-50 text-emerald-700 ring-emerald-200" : status === "inactive" ? "bg-slate-100 text-slate-600 ring-slate-200" : "bg-amber-50 text-amber-700 ring-amber-200";

export default function AgentCustomers() {
  const query = useAgentCustomers({ page: 1, limit: 100 });
  const data = Array.isArray(query.data) ? query.data : [];
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return data.filter((c) => { const s = statusOf(c); const matches = !term || [fullName(c), c?.phone, c?.email, c?.nationality, c?._id].some((v) => String(v || "").toLowerCase().includes(term)); return matches && (status === "all" || s === status); }); }, [data, search, status]);
  const active = data.filter((c) => statusOf(c) === "active").length;
  const withPhone = data.filter((c) => c?.phone).length;

  if (query.isLoading) return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-32 rounded-3xl bg-slate-200"/><div className="h-96 rounded-2xl bg-white"/></div></div>;
  if (query.isError) return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-4xl rounded-3xl border border-rose-200 bg-white p-8"><AlertTriangle className="h-7 w-7 text-rose-600"/><h1 className="mt-4 text-2xl font-bold">Customer data unavailable</h1><p className="mt-2 text-sm text-slate-600">The API request failed, so the workspace will not show an artificial empty customer list.</p><p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{query.error?.response?.data?.message || query.error?.message || "Unable to load customers."}</p><button type="button" onClick={()=>query.refetch()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/> Retry</button></div></div>;

  return <section className="min-h-full bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-300">Customer relationship management</p><h1 className="mt-2 text-3xl font-black">My Customers</h1><p className="mt-2 text-sm text-slate-300">Customers associated with your agent sales activity.</p></div><button type="button" onClick={()=>query.refetch()} disabled={query.isFetching} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-bold hover:bg-white/15"><RefreshCw className={`h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`}/> Refresh</button></div></header>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Users className="h-5 w-5 text-indigo-600"/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-500">Customers</p><p className="mt-1 text-3xl font-black">{data.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><UserRound className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-500">Active</p><p className="mt-1 text-3xl font-black">{active}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Phone className="h-5 w-5 text-violet-600"/><p className="mt-3 text-xs font-bold uppercase tracking-wider text-slate-500">Phone available</p><p className="mt-1 text-3xl font-black">{withPhone}</p></div></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search name, phone, email, nationality or ID..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-50"/></label><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><p className="mt-3 text-xs text-slate-500">Showing {filtered.length} of {data.length} customers</p></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Nationality</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"/></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan="6" className="px-4 py-10 text-center text-slate-500">No customers match the current view.</td></tr> : filtered.map((customer)=><tr key={customer._id || customer.id} className="border-t border-slate-100 hover:bg-indigo-50/40"><td className="px-4 py-3 font-semibold text-slate-800">{fullName(customer)}</td><td className="px-4 py-3 text-slate-700">{customer.phone || "—"}</td><td className="px-4 py-3 text-slate-600">{customer.email || customer.user?.email || "—"}</td><td className="px-4 py-3 text-slate-600">{customer.nationality || "—"}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ring-1 ${statusTone(statusOf(customer))}`}>{statusOf(customer)}</span></td><td className="px-4 py-3 text-right"><button type="button" onClick={()=>setSelected(customer)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold hover:border-indigo-300 hover:text-indigo-700"><Eye className="h-4 w-4"/> View</button></td></tr>)}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl" onClick={(e)=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Customer profile</p><h2 className="mt-1 text-xl font-bold">{fullName(selected)}</h2></div><button type="button" onClick={()=>setSelected(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100">×</button></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Phone</dt><dd className="font-semibold">{selected.phone || "—"}</dd></div><div><dt className="text-xs text-slate-500">Email</dt><dd className="font-semibold">{selected.email || selected.user?.email || "—"}</dd></div><div><dt className="text-xs text-slate-500">Nationality</dt><dd className="font-semibold">{selected.nationality || "—"}</dd></div><div><dt className="text-xs text-slate-500">Status</dt><dd className="font-semibold capitalize">{statusOf(selected)}</dd></div></dl></div></div>}
  </div></section>;
}
