import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Calculator, FileText, Plus, RefreshCw, Send, Trash2 } from "lucide-react";
import api from "../../api/axios";
import { getAgentQuotations, createQuotation, updateQuotationStatus } from "../../api/quotationApi";

const emptyItem = { name: "", category: "Other", description: "", quantity: 1, unitPrice: "" };
const money = (value) => { const n = Number(value); return Number.isFinite(n) ? `KES ${n.toLocaleString("en-KE")}` : "—"; };
const statusTone = (status) => { const s = String(status || "unknown").toLowerCase(); if (["accepted","approved","sent"].includes(s)) return "bg-emerald-50 text-emerald-700 ring-emerald-200"; if (["draft","pending"].includes(s)) return "bg-amber-50 text-amber-700 ring-amber-200"; if (["rejected","expired","cancelled"].includes(s)) return "bg-rose-50 text-rose-700 ring-rose-200"; return "bg-slate-100 text-slate-600 ring-slate-200"; };

export default function AgentQuotes() {
  const qc = useQueryClient();
  const quotesQuery = useQuery({ queryKey: ["agent-quotes"], queryFn: getAgentQuotations, staleTime: 30000, refetchOnMount: "always" });
  const customersQuery = useQuery({ queryKey: ["agent-customers"], queryFn: async () => (await api.get("/agent/customers")).data, staleTime: 30000 });
  const packagesQuery = useQuery({ queryKey: ["agent-packages"], queryFn: async () => (await api.get("/agent/packages")).data, staleTime: 30000 });
  const [open, setOpen] = useState(false);
  const [customer, setCustomer] = useState("");
  const [tourPackage, setTourPackage] = useState("");
  const [validUntil, setValidUntil] = useState("");
  const [notes, setNotes] = useState("");
  const [taxRate, setTaxRate] = useState(0);
  const [discount, setDiscount] = useState(0);
  const [items, setItems] = useState([{ ...emptyItem, name: "Safari package" }]);
  const quotes = Array.isArray(quotesQuery.data?.quotations) ? quotesQuery.data.quotations : Array.isArray(quotesQuery.data?.data) ? quotesQuery.data.data : Array.isArray(quotesQuery.data?.quotes) ? quotesQuery.data.quotes : [];
  const customers = Array.isArray(customersQuery.data?.customers) ? customersQuery.data.customers : Array.isArray(customersQuery.data?.data) ? customersQuery.data.data : [];
  const packages = Array.isArray(packagesQuery.data?.packages) ? packagesQuery.data.packages : Array.isArray(packagesQuery.data?.data) ? packagesQuery.data.data : [];
  const subtotal = useMemo(() => items.reduce((sum, i) => sum + Number(i.quantity || 0) * Number(i.unitPrice || 0), 0), [items]);
  const discountAmount = Math.min(subtotal, Math.max(0, Number(discount) || 0));
  const taxable = Math.max(0, subtotal - discountAmount);
  const taxAmount = taxable * (Math.max(0, Number(taxRate) || 0) / 100);
  const estimatedTotal = taxable + taxAmount;

  const createMutation = useMutation({ mutationFn: createQuotation, onSuccess: () => { setOpen(false); setItems([{ ...emptyItem, name: "Safari package" }]); setCustomer(""); setTourPackage(""); setValidUntil(""); setNotes(""); setDiscount(0); setTaxRate(0); qc.invalidateQueries({ queryKey: ["agent-quotes"] }); } });
  const statusMutation = useMutation({ mutationFn: updateQuotationStatus, onSuccess: () => qc.invalidateQueries({ queryKey: ["agent-quotes"] }) });
  const submit = (e) => { e.preventDefault(); const validItems = items.filter(i => i.name.trim() && Number(i.quantity) > 0 && Number(i.unitPrice) >= 0); if (!customer || !tourPackage || !validUntil || !validItems.length) return; createMutation.mutate({ customer, tourPackage, items: validItems.map(i => ({ ...i, quantity: Number(i.quantity), unitPrice: Number(i.unitPrice), total: Number(i.quantity) * Number(i.unitPrice) })), discount: Number(discount), taxRate: Number(taxRate), notes, validUntil }); };
  const updateItem = (index, patch) => setItems((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item));

  return <section className="min-h-full bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Sales workflow</p><h1 className="mt-2 text-3xl font-black">Quotation Builder</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Turn customer requests into priced, trackable proposals with clear commercial totals.</p></div><button type="button" onClick={()=>setOpen(v=>!v)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-emerald-400"><Plus className="h-4 w-4"/> {open ? "Close builder" : "New quotation"}</button></div></header>
    {(customersQuery.isError || packagesQuery.isError) && <div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle className="mt-0.5 h-5 w-5"/><div><p className="font-bold">Quotation dependencies are incomplete</p><p className="mt-1 text-sm">Customer or package data could not be fully loaded. Do not create a quotation using missing dependency data.</p></div></div>}
    {open && <form onSubmit={submit} className="space-y-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div><h2 className="text-lg font-bold text-slate-900">Proposal details</h2><p className="mt-1 text-sm text-slate-500">Select an existing customer and published package, then define the commercial validity period.</p></div><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold text-slate-700">Customer<select required value={customer} onChange={e=>setCustomer(e.target.value)} disabled={customersQuery.isLoading || !customers.length} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"><option value="">{customersQuery.isLoading ? "Loading customers..." : customers.length ? "Select customer" : "No customer data"}</option>{customers.map(c=><option key={c._id} value={c._id}>{c.name || [c.firstName,c.lastName].filter(Boolean).join(" ") || c.email || "Customer"}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Tour package<select required value={tourPackage} onChange={e=>setTourPackage(e.target.value)} disabled={packagesQuery.isLoading || !packages.length} className="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"><option value="">{packagesQuery.isLoading ? "Loading packages..." : packages.length ? "Select package" : "No package data"}</option>{packages.map(p=><option key={p._id} value={p._id}>{p.title || p.name || "Package"}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Valid until<input required type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)} min={new Date().toISOString().slice(0,10)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"/></label></div>
    <div><div className="mb-3 flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Line items</h3><p className="text-xs text-slate-500">Use KES amounts. Taxes and discounts are estimated for the builder.</p></div><button type="button" onClick={()=>setItems(xs=>[...xs,{...emptyItem}])} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold hover:border-indigo-300 hover:text-indigo-700"><Plus className="mr-1 inline h-4 w-4"/> Add item</button></div><div className="space-y-3">{items.map((item,idx)=><div key={idx} className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-12"><input value={item.name} onChange={e=>updateItem(idx,{name:e.target.value})} placeholder="Item / service" className="rounded-xl border border-slate-200 bg-white p-3 md:col-span-4"/><select value={item.category} onChange={e=>updateItem(idx,{category:e.target.value})} className="rounded-xl border border-slate-200 bg-white p-3 md:col-span-2"><option>Accommodation</option><option>Transport</option><option>Activity</option><option>Meal</option><option>Guide</option><option>Park Fee</option><option>Insurance</option><option>Visa</option><option>Other</option></select><input type="number" min="1" value={item.quantity} onChange={e=>updateItem(idx,{quantity:e.target.value})} className="rounded-xl border border-slate-200 bg-white p-3 md:col-span-2"/><input type="number" min="0" value={item.unitPrice} onChange={e=>updateItem(idx,{unitPrice:e.target.value})} placeholder="Unit price" className="rounded-xl border border-slate-200 bg-white p-3 md:col-span-3"/>{items.length>1 && <button type="button" onClick={()=>setItems(xs=>xs.filter((_,i)=>i!==idx))} className="rounded-xl border border-rose-200 bg-white p-3 text-rose-600 hover:bg-rose-50"><Trash2 className="mx-auto h-5 w-5"/></button>}</div>)}</div></div>
    <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold text-slate-700">Discount (KES)<input type="number" min="0" value={discount} onChange={e=>setDiscount(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label><label className="text-sm font-semibold text-slate-700">Tax rate (%)<input type="number" min="0" step="0.01" value={taxRate} onChange={e=>setTaxRate(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label><label className="text-sm font-semibold text-slate-700">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Customer follow-up or proposal notes" className="mt-2 min-h-12 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label></div>
    <div className="grid gap-3 rounded-2xl bg-slate-950 p-5 text-white sm:grid-cols-4"><div><p className="text-xs text-slate-400">Subtotal</p><p className="mt-1 font-bold">{money(subtotal)}</p></div><div><p className="text-xs text-slate-400">Discount</p><p className="mt-1 font-bold">{money(discountAmount)}</p></div><div><p className="text-xs text-slate-400">Estimated tax</p><p className="mt-1 font-bold">{money(taxAmount)}</p></div><div><p className="text-xs text-emerald-300">Estimated total</p><p className="mt-1 text-xl font-black">{money(estimatedTotal)}</p></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-500">Final tax treatment and totals remain subject to the quotation backend rules.</span><button type="submit" disabled={createMutation.isPending || customersQuery.isError || packagesQuery.isError} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"><Calculator className="h-4 w-4"/>{createMutation.isPending ? "Creating..." : "Create quotation"}</button></div>{createMutation.isError && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{createMutation.error?.response?.data?.message || createMutation.error?.message || "Unable to create quotation."}</p>}</form>}
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><h2 className="font-bold text-slate-900">Saved quotations</h2><p className="mt-1 text-xs text-slate-500">Track proposal state and send draft quotations when ready.</p></div><button type="button" onClick={()=>quotesQuery.refetch()} disabled={quotesQuery.isFetching} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><RefreshCw className={`h-4 w-4 ${quotesQuery.isFetching ? "animate-spin" : ""}`}/></button></div>{quotesQuery.isLoading ? <div className="py-10 text-center text-slate-500">Loading quotations...</div> : quotesQuery.isError ? <div className="py-10 text-center"><AlertTriangle className="mx-auto h-7 w-7 text-rose-500"/><p className="mt-2 font-semibold text-slate-800">Quotation data unavailable</p><p className="mt-1 text-sm text-slate-500">{quotesQuery.error?.response?.data?.message || quotesQuery.error?.message || "Unable to load quotations."}</p></div> : !quotes.length ? <div className="py-10 text-center"><FileText className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 font-semibold text-slate-700">No quotations returned</p><p className="mt-1 text-sm text-slate-500">Create a quotation to begin tracking proposals.</p></div> : <div className="mt-4 space-y-3">{quotes.map(q=><article key={q._id || q.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-bold text-slate-900">{q.quotationNumber || q._id || "Quotation"}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ring-1 ${statusTone(q.status)}`}>{q.status || "Unknown"}</span></div><p className="mt-1 text-sm text-slate-500">{q.customer?.name || "Customer unavailable"} · {q.tourPackage?.title || q.tourPackage?.name || "Package unavailable"}</p></div><div className="flex items-center gap-3"><span className="font-bold text-indigo-700">{money(q.grandTotal)}</span>{q.status === "draft" && <button type="button" disabled={statusMutation.isPending} onClick={()=>statusMutation.mutate({id:q._id,status:"sent"})} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white hover:bg-emerald-700 disabled:opacity-50"><Send className="h-3.5 w-3.5"/> Send</button>}</div></article>)}</div>}</section>
  </div></section>;
}
