import { useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, Package, RefreshCw, Search, Wallet } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { getPackages } from "../../api/packageApi";

const price = (value) => { const n = Number(value); return Number.isFinite(n) && n > 0 ? `KES ${n.toLocaleString("en-KE")}` : "Price unavailable"; };
const duration = (pkg) => { const value = pkg?.duration ?? pkg?.durationDays; return value === undefined || value === null || value === "" ? "Flexible duration" : `${value} ${Number(value) === 1 ? "day" : "days"}`; };

export default function AgentPackages() {
  const query = useQuery({ queryKey: ["agent-packages"], queryFn: getPackages, staleTime: 30000, refetchOnMount: "always" });
  const packages = Array.isArray(query.data) ? query.data : query.data?.packages || query.data?.data?.packages || query.data?.data || [];
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return packages.filter((pkg) => !term || [pkg?.name, pkg?.title, pkg?.description, pkg?.destination?.name].some((v) => String(v || "").toLowerCase().includes(term))); }, [packages, search]);

  if (query.isLoading) return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-32 rounded-3xl bg-slate-200"/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map((i)=><div key={i} className="h-56 rounded-2xl bg-white"/>)}</div></div></div>;
  if (query.isError) return <div className="min-h-full bg-slate-50 p-6"><div className="mx-auto max-w-4xl rounded-3xl border border-rose-200 bg-white p-8"><AlertTriangle className="h-7 w-7 text-rose-600"/><h1 className="mt-4 text-2xl font-bold">Package data unavailable</h1><p className="mt-2 text-sm text-slate-600">Published package data could not be retrieved. The workspace will not imply that the agency has no packages.</p><p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{query.error?.response?.data?.message || query.error?.message || "Unable to load packages."}</p><button type="button" onClick={()=>query.refetch()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/> Retry</button></div></div>;

  return <section className="min-h-full bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="rounded-3xl bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-300">Sales catalogue</p><h1 className="mt-2 text-3xl font-black">Tour Packages</h1><p className="mt-2 text-sm text-slate-300">Browse published packages available to your agency for customer proposals.</p></div><button type="button" onClick={()=>query.refetch()} disabled={query.isFetching} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-bold hover:bg-white/15"><RefreshCw className={`h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`}/> Refresh</button></div></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search packages, destinations or descriptions..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-indigo-400 focus:bg-white focus:ring-4 focus:ring-indigo-50"/></div><p className="mt-3 text-xs text-slate-500">Showing {filtered.length} of {packages.length} published packages</p></section>
    {filtered.length === 0 ? <section className="rounded-3xl border border-slate-200 bg-white p-10 text-center shadow-sm"><Package className="mx-auto h-8 w-8 text-slate-400"/><h2 className="mt-3 font-bold text-slate-900">{packages.length ? "No packages match" : "No published packages available"}</h2><p className="mt-1 text-sm text-slate-500">{packages.length ? "Adjust your search to view other packages." : "Published packages will appear here when the API provides them."}</p></section> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((pkg)=><article key={pkg._id || pkg.id} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700"><Package className="h-5 w-5"/></div>{pkg.status && <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold capitalize text-emerald-700">{pkg.status}</span>}</div><h2 className="mt-5 text-lg font-bold text-slate-900">{pkg.name || pkg.title || "Tour package"}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{pkg.description || "Package details are available from the package record."}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4 text-sm"><div className="flex items-center gap-2 text-slate-600"><CalendarDays className="h-4 w-4 text-indigo-500"/>{duration(pkg)}</div><div className="flex items-center justify-end gap-2 font-bold text-indigo-700"><Wallet className="h-4 w-4"/>{price(pkg.price)}</div></div></article>)}</div>}
  </div></section>;
}
