import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ChevronDown, FilePlus2, Plus, RefreshCw, Scale, ShieldCheck, XCircle } from "lucide-react";
import { createAccount, createJournalEntry, getAccounts, getJournalEntries, getLedgerSummary, postJournalEntry, voidJournalEntry } from "../../api/accountingApi";

const money = (n) => `KSh ${Number(n || 0).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const unwrap = (v) => v?.data?.data ?? v?.data ?? v ?? {};
const blankLine = () => ({ account: "", description: "", debit: "", credit: "" });

export default function AccountingLedger() {
  const qc = useQueryClient();
  const [description, setDescription] = useState(""); const [reference, setReference] = useState(""); const [entryDate, setEntryDate] = useState(new Date().toISOString().slice(0, 10)); const [lines, setLines] = useState([blankLine(), blankLine()]);
  const [showAccountForm, setShowAccountForm] = useState(false); const [account, setAccount] = useState({ code: "", name: "", type: "asset", subtype: "", description: "" });
  const accountsQ = useQuery({ queryKey: ["accounting-accounts"], queryFn: getAccounts, staleTime: 30000, retry: 2 });
  const journalQ = useQuery({ queryKey: ["accounting-journal"], queryFn: () => getJournalEntries({ limit: 200 }), staleTime: 30000, retry: 2 });
  const summaryQ = useQuery({ queryKey: ["accounting-summary"], queryFn: getLedgerSummary, staleTime: 30000, retry: 2 });
  const refresh = () => { accountsQ.refetch(); journalQ.refetch(); summaryQ.refetch(); };
  const createM = useMutation({ mutationFn: createJournalEntry, onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounting-journal"] }); qc.invalidateQueries({ queryKey: ["accounting-summary"] }); setDescription(""); setReference(""); setLines([blankLine(), blankLine()]); } });
  const accountM = useMutation({ mutationFn: createAccount, onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounting-accounts"] }); setAccount({ code: "", name: "", type: "asset", subtype: "", description: "" }); setShowAccountForm(false); } });
  const postM = useMutation({ mutationFn: postJournalEntry, onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounting-journal"] }); qc.invalidateQueries({ queryKey: ["accounting-summary"] }); } });
  const voidM = useMutation({ mutationFn: voidJournalEntry, onSuccess: () => qc.invalidateQueries({ queryKey: ["accounting-journal"] }) });
  const accounts = Array.isArray(accountsQ.data) ? accountsQ.data : unwrap(accountsQ.data).items || [];
  const rows = unwrap(summaryQ.data).accounts || []; const journal = Array.isArray(journalQ.data) ? journalQ.data : unwrap(journalQ.data).items || [];
  const totals = useMemo(() => lines.reduce((a, l) => ({ debit: a.debit + Number(l.debit || 0), credit: a.credit + Number(l.credit || 0) }), { debit: 0, credit: 0 }), [lines]);
  const balanced = lines.length >= 2 && totals.debit > 0 && Math.abs(totals.debit - totals.credit) < 0.01 && lines.every((l) => l.account && !(Number(l.debit || 0) > 0 && Number(l.credit || 0)));
  const ps = unwrap(summaryQ.data).profitLoss || {}; const bs = unwrap(summaryQ.data).balanceSheet || {}; const ledgerBalanced = Math.abs(Number(unwrap(summaryQ.data).totals?.debit || 0) - Number(unwrap(summaryQ.data).totals?.credit || 0)) < 0.01;
  const updateLine = (index, field, value) => setLines((prev) => prev.map((line, i) => i === index ? { ...line, [field]: value } : line));
  const submit = (e) => { e.preventDefault(); if (!balanced || !description.trim()) return; createM.mutate({ entryDate, description: description.trim(), reference: reference.trim(), lines: lines.map((l) => ({ account: l.account, description: l.description.trim() || description.trim(), debit: Number(l.debit || 0), credit: Number(l.credit || 0) })) }); };
  const submitAccount = (e) => { e.preventDefault(); if (!account.code.trim() || !account.name.trim()) return; accountM.mutate(account); };

  return <div className="space-y-6">
    <div className="rounded-2xl bg-gradient-to-r from-slate-950 via-emerald-950 to-slate-900 p-6 text-white shadow-lg"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sky-300">Core accounting</p><h2 className="mt-1 text-2xl font-black">General Ledger</h2><p className="mt-1 text-sm text-slate-300">Tenant-scoped double-entry accounting, trial balance, journal controls and chart of accounts.</p></div><button onClick={refresh} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold hover:bg-indigo-500"><RefreshCw size={16} className={summaryQ.isFetching ? "animate-spin" : ""}/> Refresh</button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Posted debits" value={money(unwrap(summaryQ.data).totals?.debit)} /><Stat label="Posted credits" value={money(unwrap(summaryQ.data).totals?.credit)} /><Stat label="Net profit" value={money(ps.netProfit)} tone={Number(ps.netProfit) >= 0 ? "positive" : "negative"} /><Stat label="Ledger status" value={ledgerBalanced ? "Balanced" : "Review required"} icon={ledgerBalanced ? CheckCircle2 : Scale} tone={ledgerBalanced ? "positive" : "negative"}/></div>
    <div className="grid gap-4 md:grid-cols-3"><Summary label="Revenue" value={money(ps.revenue)}/><Summary label="Expenses" value={money(ps.expenses)}/><Summary label="Assets" value={money(bs.assets)}/></div>

    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Journal workspace</p><h3 className="text-xl font-black text-slate-950">Create balanced journal entry</h3><p className="mt-1 text-sm text-slate-500">Use multiple lines for real-world adjustments, accruals and allocations. Entries remain drafts until explicitly posted.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${balanced ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{balanced ? "Balanced" : `Difference ${money(Math.abs(totals.debit - totals.credit))}`}</span></div>
      <form onSubmit={submit} className="mt-5 space-y-4"><div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Entry date<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-900 focus:border-indigo-500 focus:outline-none" type="date" value={entryDate} onChange={(e)=>setEntryDate(e.target.value)}/></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Description *<input required className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-900 focus:border-indigo-500 focus:outline-none" placeholder="e.g. Supplier accrual" value={description} onChange={(e)=>setDescription(e.target.value)}/></label><label className="text-xs font-bold uppercase tracking-wide text-slate-500">Reference<input className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal text-slate-900 focus:border-indigo-500 focus:outline-none" placeholder="Invoice / receipt / adjustment" value={reference} onChange={(e)=>setReference(e.target.value)}/></label></div>
        <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[760px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Account</th><th className="p-3">Line description</th><th className="p-3 text-right">Debit</th><th className="p-3 text-right">Credit</th><th className="p-3"></th></tr></thead><tbody>{lines.map((line, index)=><tr key={index} className="border-t border-slate-100"><td className="p-3"><select required value={line.account} onChange={(e)=>updateLine(index,"account",e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2"><option value="">Select account</option>{accounts.map((a)=><option key={a._id} value={a._id}>{a.code} — {a.name}</option>)}</select></td><td className="p-3"><input value={line.description} onChange={(e)=>updateLine(index,"description",e.target.value)} placeholder="Optional" className="w-full rounded-lg border border-slate-200 px-3 py-2"/></td><td className="p-3"><input value={line.debit} onChange={(e)=>updateLine(index,"debit",e.target.value)} type="number" min="0" step="0.01" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-right"/></td><td className="p-3"><input value={line.credit} onChange={(e)=>updateLine(index,"credit",e.target.value)} type="number" min="0" step="0.01" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-right"/></td><td className="p-3 text-right">{lines.length > 2 && <button type="button" onClick={()=>setLines((prev)=>prev.filter((_,i)=>i!==index))} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><XCircle size={16}/></button>}</td></tr>)}</tbody><tfoot className="bg-slate-50 font-bold"><tr><td colSpan="2" className="p-3 text-right">Totals</td><td className="p-3 text-right">{money(totals.debit)}</td><td className="p-3 text-right">{money(totals.credit)}</td><td/></tr></tfoot></table></div>
        <div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setLines((prev)=>[...prev, blankLine()])} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50"><Plus size={16}/> Add line</button><button disabled={!balanced || !description.trim() || createM.isPending} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-50"><FilePlus2 size={16}/>{createM.isPending ? "Saving…" : "Save draft"}</button></div>{createM.isError && <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{createM.error?.response?.data?.message || createM.error?.message || "Unable to save journal entry."}</p>}</form>
    </section>

    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-sky-600">Account structure</p><h3 className="text-xl font-black text-slate-950">Chart of Accounts</h3><p className="mt-1 text-sm text-slate-500">System accounts are provisioned automatically; custom tenant accounts can be added without changing application code.</p></div><button onClick={()=>setShowAccountForm((v)=>!v)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800"><Plus size={16}/> {showAccountForm ? "Close" : "Add account"}</button></div>
      {showAccountForm && <form onSubmit={submitAccount} className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-2 lg:grid-cols-5"><input required placeholder="Code *" value={account.code} onChange={(e)=>setAccount({...account,code:e.target.value})} className="rounded-lg border px-3 py-2"/><input required placeholder="Account name *" value={account.name} onChange={(e)=>setAccount({...account,name:e.target.value})} className="rounded-lg border px-3 py-2"/><select value={account.type} onChange={(e)=>setAccount({...account,type:e.target.value})} className="rounded-lg border px-3 py-2"><option value="asset">Asset</option><option value="liability">Liability</option><option value="equity">Equity</option><option value="revenue">Revenue</option><option value="expense">Expense</option></select><input placeholder="Subtype" value={account.subtype} onChange={(e)=>setAccount({...account,subtype:e.target.value})} className="rounded-lg border px-3 py-2"/><button disabled={accountM.isPending} className="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white disabled:opacity-50">{accountM.isPending ? "Creating…" : "Create account"}</button>{accountM.isError && <p className="md:col-span-2 lg:col-span-5 text-sm text-rose-600">{accountM.error?.response?.data?.message || accountM.error?.message || "Unable to create account."}</p>}</form>}
      <div className="mt-5 overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Code</th><th className="p-3">Account</th><th className="p-3">Type</th><th className="p-3 text-right">Debit</th><th className="p-3 text-right">Credit</th><th className="p-3 text-right">Balance</th></tr></thead><tbody>{rows.map((r)=><tr className="border-t border-slate-100" key={r.account._id}><td className="p-3 font-mono text-xs text-slate-500">{r.account.code}</td><td className="p-3 font-semibold text-slate-900">{r.account.name}</td><td className="p-3 capitalize text-slate-500">{r.account.type}</td><td className="p-3 text-right">{money(r.debit)}</td><td className="p-3 text-right">{money(r.credit)}</td><td className="p-3 text-right font-bold">{money(r.balance)}</td></tr>)}{!rows.length && <tr><td colSpan="6" className="p-8 text-center text-slate-400">No posted balances yet.</td></tr>}</tbody></table></div></section>

    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-indigo-50 p-2 text-indigo-700"><ShieldCheck size={18}/></div><div><h3 className="text-xl font-black text-slate-950">Journal control</h3><p className="text-sm text-slate-500">Drafts can be posted or voided. Posted entries are immutable and require a reversing entry for correction.</p></div></div><div className="mt-5 overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Date</th><th className="p-3">Entry</th><th className="p-3">Description</th><th className="p-3">Status</th><th className="p-3 text-right">Amount</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{journal.map((e)=>{const total=(e.lines||[]).reduce((s,l)=>s+Number(l.debit||0),0); return <tr className="border-t border-slate-100" key={e._id}><td className="p-3">{new Date(e.entryDate).toLocaleDateString("en-KE")}</td><td className="p-3 font-mono text-xs">{e.entryNumber}</td><td className="p-3 font-medium">{e.description}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${e.status === "posted" ? "bg-emerald-50 text-emerald-700" : e.status === "void" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{e.status}</span></td><td className="p-3 text-right font-semibold">{money(total)}</td><td className="p-3 text-right">{e.status === "draft" && <span className="inline-flex gap-2"><button onClick={()=>postM.mutate(e._id)} disabled={postM.isPending} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-2.5 py-1.5 text-xs font-bold text-white disabled:opacity-50"><CheckCircle2 size={14}/>Post</button><button onClick={()=>voidM.mutate(e._id)} disabled={voidM.isPending} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-bold text-slate-600"><XCircle size={14}/>Void</button></span>}</td></tr>})}{!journal.length && <tr><td colSpan="6" className="p-8 text-center text-slate-400">No journal entries yet.</td></tr>}</tbody></table></div></section>
  </div>;
}

function Stat({ label, value, icon: Icon, tone }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><div className={`mt-2 flex items-center gap-2 text-xl font-black ${tone === "positive" ? "text-emerald-700" : tone === "negative" ? "text-rose-600" : "text-slate-950"}`}>{Icon && <Icon size={18}/>} {value}</div></div>; }
function Summary({ label, value }) { return <div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-slate-950">{value}</p></div>; }
