import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, FileCheck2, Save, ShieldCheck } from "lucide-react";
import { getComplianceRecords, getComplianceSummary, saveComplianceRecord } from "../../api/complianceApi";

const labels = { TRA_LICENSE: "TRA licence", ODPC_REGISTRATION: "ODPC registration", PRIVACY_POLICY: "Privacy policy", DATA_RETENTION: "Data retention", DPA_REVIEW: "DPA review", BREACH_RESPONSE: "Breach response", KRA_TAX_PROFILE: "KRA tax profile", ETIMS_ONBOARDING: "eTIMS onboarding" };
const types = Object.keys(labels); const statuses = ["not_started", "in_progress", "submitted", "approved", "expired", "action_required", "closed"];

export default function AdminCompliance() {
  const qc = useQueryClient(); const summary = useQuery({ queryKey: ["compliance-summary"], queryFn: getComplianceSummary, refetchInterval: 60000 }); const records = useQuery({ queryKey: ["compliance-records"], queryFn: getComplianceRecords, refetchInterval: 60000 });
  const [editing, setEditing] = useState(null);
  const saveM = useMutation({ mutationFn: ({ type, data }) => saveComplianceRecord(type, data), onSuccess: () => { setEditing(null); qc.invalidateQueries({ queryKey: ["compliance-records"] }); qc.invalidateQueries({ queryKey: ["compliance-summary"] }); } });
  const initM = useMutation({ mutationFn: () => Promise.all(types.map((type) => saveComplianceRecord(type, { status: "not_started" }))), onSuccess: () => { qc.invalidateQueries({ queryKey: ["compliance-records"] }); qc.invalidateQueries({ queryKey: ["compliance-summary"] }); } });
  const rows = records.data?.data || []; const metrics = summary.data?.data || {};
  const cards = useMemo(() => [["Tracked controls", metrics.total || 0, ShieldCheck], ["Expiring in 30 days", metrics.expiringSoon || 0, AlertTriangle], ["Action required", metrics.actionRequired || 0, FileCheck2]], [metrics]);
  const begin = (row) => setEditing({ ...row, issueDate: row.issueDate ? String(row.issueDate).slice(0, 10) : "", expiryDate: row.expiryDate ? String(row.expiryDate).slice(0, 10) : "", nextReviewAt: row.nextReviewAt ? String(row.nextReviewAt).slice(0, 10) : "" });
  const update = (key, value) => setEditing((x) => ({ ...x, [key]: value }));

  return <div className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-7xl">
    <div className="mb-8"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Governance</p><h1 className="text-3xl font-bold">Compliance Centre</h1><p className="mt-1 text-slate-500">Manage tenant regulatory records, review dates and eTIMS readiness. Regulatory approval remains with the relevant authority/provider.</p></div>
    <div className="grid gap-4 sm:grid-cols-3">{cards.map(([label,value,Icon]) => <div key={label} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between"><span className="text-sm text-slate-500">{label}</span><Icon size={19}/></div><div className="mt-3 text-2xl font-bold">{value}</div></div>)}</div>
    {!rows.length && <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="font-bold text-emerald-900">Initialize compliance controls</h2><p className="mt-1 text-sm text-emerald-800">Create the tenant's TRA, ODPC, privacy, tax and eTIMS control records so they can be maintained from this centre.</p><button disabled={initM.isPending} onClick={() => initM.mutate()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{initM.isPending ? "Initializing…" : "Initialize controls"}</button></div>}
    <div className="mt-6 overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Control</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Authority</th><th className="p-3 text-left">Expiry</th><th className="p-3 text-left">Reference</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row._id} className="border-t"><td className="p-3 font-semibold">{labels[row.type] || row.type}</td><td className="p-3 capitalize">{String(row.status || "not_started").replaceAll("_", " ")}</td><td className="p-3">{row.authority || "—"}</td><td className="p-3">{row.expiryDate ? new Date(row.expiryDate).toLocaleDateString() : "—"}</td><td className="p-3">{row.referenceNumber || "—"}</td><td className="p-3 text-right"><button onClick={() => begin(row)} className="rounded-lg border px-3 py-1.5 text-xs font-semibold">Edit</button></td></tr>)}{!rows.length && <tr><td colSpan="6" className="p-10 text-center text-slate-500">No compliance records configured.</td></tr>}</tbody></table></div>
    {editing && <div className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Update control</p><h2 className="text-xl font-bold">{labels[editing.type] || editing.type}</h2></div><button onClick={() => setEditing(null)} className="text-sm text-slate-500">Cancel</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3"><select className="rounded-lg border px-3 py-2" value={editing.status || "not_started"} onChange={(e) => update("status", e.target.value)}>{statuses.map((s) => <option key={s} value={s}>{s.replaceAll("_", " ")}</option>)}</select><input className="rounded-lg border px-3 py-2" placeholder="Authority" value={editing.authority || ""} onChange={(e) => update("authority", e.target.value)} /><input className="rounded-lg border px-3 py-2" placeholder="Reference number" value={editing.referenceNumber || ""} onChange={(e) => update("referenceNumber", e.target.value)} /><input className="rounded-lg border px-3 py-2" type="date" value={editing.issueDate || ""} onChange={(e) => update("issueDate", e.target.value)} /><input className="rounded-lg border px-3 py-2" type="date" value={editing.expiryDate || ""} onChange={(e) => update("expiryDate", e.target.value)} /><input className="rounded-lg border px-3 py-2" type="date" value={editing.nextReviewAt || ""} onChange={(e) => update("nextReviewAt", e.target.value)} /><textarea className="min-h-24 rounded-lg border px-3 py-2 md:col-span-2 lg:col-span-3" placeholder="Notes" value={editing.notes || ""} onChange={(e) => update("notes", e.target.value)} /></div><button disabled={saveM.isPending} onClick={() => saveM.mutate({ type: editing.type, data: { status: editing.status, authority: editing.authority, referenceNumber: editing.referenceNumber, issueDate: editing.issueDate || null, expiryDate: editing.expiryDate || null, nextReviewAt: editing.nextReviewAt || null, notes: editing.notes || "", documents: editing.documents || [] } })} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-50"><Save size={16}/>{saveM.isPending ? "Saving…" : "Save control"}</button>{saveM.isError && <p className="mt-2 text-sm text-red-600">{saveM.error?.response?.data?.message || "Unable to save compliance record."}</p>}</div>}
  </div></div>;
}
