import { useSettings } from "../../context/SettingsContext";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Globe2, Palette, Phone, Save, ShieldCheck, WalletCards, LayoutDashboard } from "lucide-react";
import { toast } from "react-toastify";
import { getSettings, updateSettings } from "../../api/settingsApi";
import TenantHeroManager from "../../components/admin/TenantHeroManager";

const SECTIONS = { stats: true, tours: true, destinations: true, experiences: true, services: true, testimonials: true, gallery: true, whyChooseUs: true, newsletter: true };
const THEME = { primaryColor: "#047857", secondaryColor: "#064e3b", accentColor: "#10b981", backgroundColor: "#f8fafc", surfaceColor: "#ffffff", textColor: "#0f172a", fontFamily: "Inter", borderRadius: "xl", buttonStyle: "rounded", heroOverlayOpacity: 50 };

export default function AdminSettings() {
  const qc = useQueryClient(); const { settings: globalSettings = {} } = useSettings();
  const [settings, setSettings] = useState({ companyName: globalSettings.companyName || "", supportEmail: "", supportPhone: "+254 733 439 362", address: "", city: "Nairobi", country: "Kenya", currency: "KES", currencySymbol: "KSh", timezone: "Africa/Nairobi", websiteUrl: "", taxRate: 0, bookingDepositPercentage: 30, defaultCommissionRate: 10, maintenanceMode: false, allowRegistrations: true, allowAgentRegistrations: true, requireEmailVerification: true, requirePhoneVerification: false, enableMpesa: true, enableStripe: false, enablePaypal: false, enableBankTransfer: true, emailFromName: "", emailFromAddress: "", facebook: "", instagram: "", twitter: "", youtube: "", seoTitle: "", seoDescription: "", seoKeywords: "", bookingNotifications: true, paymentNotifications: true, ...THEME, homepageSections: SECTIONS });
  const [logoFile, setLogoFile] = useState(null);
  const { data, isLoading, isError } = useQuery({ queryKey: ["admin-settings"], queryFn: getSettings });
  useEffect(() => { const incoming = data?.data || data?.settings; if (incoming) setSettings(s => ({ ...s, ...incoming, homepageSections: { ...SECTIONS, ...(incoming.homepageSections || {}) } })); }, [data]);
  useEffect(() => { if (globalSettings.companyName && !settings.companyName) setSettings(s => ({ ...s, companyName: globalSettings.companyName, emailFromName: s.emailFromName || globalSettings.companyName })); }, [globalSettings.companyName]);
  const mutation = useMutation({ mutationFn: updateSettings, onSuccess: r => { const saved = r?.data || r?.settings; if (saved) setSettings(s => ({ ...s, ...saved })); setLogoFile(null); qc.invalidateQueries({ queryKey: ["admin-settings"] }); toast.success("System settings saved."); }, onError: e => toast.error(e?.response?.data?.message || "Failed to save settings.") });
  const update = (key, value) => setSettings(s => ({ ...s, [key]: value }));
  const section = (key, value) => setSettings(s => ({ ...s, homepageSections: { ...(s.homepageSections || {}), [key]: value } }));
  if (isLoading) return <div className="p-8">Loading system settings...</div>; if (isError) return <div className="p-8 text-red-600">Failed to load system settings.</div>;
  return <div className="min-h-screen bg-slate-50 p-4 md:p-6"><div className="mx-auto max-w-7xl"><header className="mb-6 rounded-3xl bg-gradient-to-r from-slate-950 via-emerald-950 to-slate-900 p-6 text-white shadow-xl"><p className="text-sm font-semibold uppercase tracking-widest text-emerald-300">Administration</p><h1 className="mt-2 text-3xl font-bold">System & Tenant Settings</h1><p className="mt-2 text-slate-300">Control this tenant's public homepage, hero slider, colors, layout, payments and business settings.</p></header>
    <form onSubmit={e=>{e.preventDefault(); mutation.mutate({ ...settings, logoFile });}} className="space-y-6">
      <TenantHeroManager />
      <Section icon={<Palette size={20}/>} title="Tenant system color & visual theme"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["primaryColor","Primary color"],["secondaryColor","Secondary color"],["accentColor","Accent color"],["backgroundColor","Page background"],["surfaceColor","Surface color"],["textColor","Text color"]].map(([key,label])=><Field key={key} label={label}><div className="flex gap-2"><input type="color" value={settings[key]} onChange={e=>update(key,e.target.value)} className="h-11 w-14 rounded border p-1"/><input value={settings[key]} onChange={e=>update(key,e.target.value)}/></div></Field>)}</div><div className="grid gap-4 md:grid-cols-4"><Field label="Font"><select value={settings.fontFamily} onChange={e=>update("fontFamily",e.target.value)}><option>Inter</option><option>Poppins</option><option>Roboto</option><option>Arial</option><option>Georgia</option><option>system-ui</option></select></Field><Field label="Corner radius"><select value={settings.borderRadius} onChange={e=>update("borderRadius",e.target.value)}><option value="sm">Small</option><option value="md">Medium</option><option value="lg">Large</option><option value="xl">XL</option><option value="2xl">2XL</option></select></Field><Field label="Button style"><select value={settings.buttonStyle} onChange={e=>update("buttonStyle",e.target.value)}><option value="solid">Solid</option><option value="rounded">Rounded</option><option value="pill">Pill</option><option value="outline">Outline</option></select></Field><Field label="Hero overlay %"><input type="number" min="0" max="100" value={settings.heroOverlayOpacity} onChange={e=>update("heroOverlayOpacity",e.target.value)}/></Field></div></Section>
      <Section icon={<LayoutDashboard size={20}/>} title="Homepage modules"><div className="grid gap-3 md:grid-cols-3">{Object.keys(SECTIONS).map(key=><Toggle key={key} label={key.replace(/([A-Z])/g," $1")} value={settings.homepageSections?.[key] !== false} onChange={v=>section(key,v)}/>)}</div></Section>
      <Section icon={<Building2 size={20}/>} title="Company identity"><div className="grid gap-4 md:grid-cols-2"><Field label="Company name"><input value={settings.companyName} onChange={e=>update("companyName",e.target.value)}/></Field><Field label="Website URL"><input value={settings.websiteUrl} onChange={e=>update("websiteUrl",e.target.value)}/></Field><Field label="Logo"><input type="file" accept="image/*" onChange={e=>setLogoFile(e.target.files?.[0] || null)} /></Field><Field label="Address"><input value={settings.address} onChange={e=>update("address",e.target.value)}/></Field></div></Section>
      <Section icon={<Phone size={20}/>} title="Contact"><div className="grid gap-4 md:grid-cols-2"><Field label="Support phone"><input value={settings.supportPhone} onChange={e=>update("supportPhone",e.target.value)}/></Field><Field label="Support email"><input type="email" value={settings.supportEmail} onChange={e=>update("supportEmail",e.target.value)}/></Field><Field label="Email sender name"><input value={settings.emailFromName} onChange={e=>update("emailFromName",e.target.value)}/></Field><Field label="Email sender address"><input value={settings.emailFromAddress} onChange={e=>update("emailFromAddress",e.target.value)}/></Field></div></Section>
      <Section icon={<WalletCards size={20}/>} title="Regional & payment rules"><div className="grid gap-4 md:grid-cols-3"><Field label="Currency"><input value={settings.currency} onChange={e=>update("currency",e.target.value.toUpperCase())}/></Field><Field label="Currency symbol"><input value={settings.currencySymbol} onChange={e=>update("currencySymbol",e.target.value)}/></Field><Field label="Timezone"><input value={settings.timezone} onChange={e=>update("timezone",e.target.value)}/></Field><Field label="Tax %"><input type="number" min="0" max="100" value={settings.taxRate} onChange={e=>update("taxRate",e.target.value)}/></Field><Field label="Booking deposit %"><input type="number" min="0" max="100" value={settings.bookingDepositPercentage} onChange={e=>update("bookingDepositPercentage",e.target.value)}/></Field><Field label="Agent commission %"><input type="number" min="0" max="100" value={settings.defaultCommissionRate} onChange={e=>update("defaultCommissionRate",e.target.value)}/></Field></div></Section>
      <Section icon={<ShieldCheck size={20}/>} title="Access & security"><div className="grid gap-3 md:grid-cols-2"><Toggle label="Customer registrations" value={settings.allowRegistrations} onChange={v=>update("allowRegistrations",v)}/><Toggle label="Agent registrations" value={settings.allowAgentRegistrations} onChange={v=>update("allowAgentRegistrations",v)}/><Toggle label="Email verification" value={settings.requireEmailVerification} onChange={v=>update("requireEmailVerification",v)}/><Toggle label="Maintenance mode" value={settings.maintenanceMode} onChange={v=>update("maintenanceMode",v)}/></div></Section>
      <Section icon={<Globe2 size={20}/>} title="Social & SEO"><div className="grid gap-4 md:grid-cols-2"><Field label="Facebook"><input value={settings.facebook} onChange={e=>update("facebook",e.target.value)}/></Field><Field label="Instagram"><input value={settings.instagram} onChange={e=>update("instagram",e.target.value)}/></Field><Field label="X / Twitter"><input value={settings.twitter} onChange={e=>update("twitter",e.target.value)}/></Field><Field label="YouTube"><input value={settings.youtube} onChange={e=>update("youtube",e.target.value)}/></Field></div></Section>
      <div className="sticky bottom-4 flex justify-end"><button disabled={mutation.isPending} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white shadow-lg"><Save size={18}/>{mutation.isPending ? "Saving..." : "Save tenant settings"}</button></div>
    </form></div></div>;
}
function Section({icon,title,children}) { return <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 md:p-7"><div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700">{icon}</span><h2 className="text-xl font-bold">{title}</h2></div>{children}</section>; }
function Field({label,children}) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>; }
function Toggle({label,value,onChange}) { return <label className="flex cursor-pointer items-center justify-between rounded-xl border p-4"><span className="font-medium capitalize">{label}</span><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)} className="h-5 w-5"/></label>; }
