import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, Check, ChevronLeft, ChevronRight, Loader2, RefreshCw, Search, Send, Users, X } from "lucide-react";
import api from "../../api/axios";
import { toast } from "react-toastify";

const groups = [["guide", "Guides"], ["driver", "Drivers"], ["agent", "Agents"], ["manager", "Managers"], ["admin", "Administrators"]];
const types = [["system", "System"], ["assignment", "Assignment"], ["tour_update", "Tour Update"], ["alert", "Alert"], ["promotion", "Promotion"]];
const priorities = [["normal", "Normal"], ["low", "Low"], ["high", "High"], ["urgent", "Urgent"]];

const roleLabel = (user) => user?.roleId?.displayName || user?.role || user?.legacyRole || "Staff";
const userLabel = (user) => user?.name || `${user?.firstName || ""} ${user?.lastName || ""}`.trim() || user?.email || "Unnamed user";
const typeClass = { system: "bg-sky-50 text-sky-700 ring-sky-200", assignment: "bg-violet-50 text-violet-700 ring-violet-200", tour_update: "bg-emerald-50 text-emerald-700 ring-emerald-200", alert: "bg-orange-50 text-orange-700 ring-orange-200", promotion: "bg-pink-50 text-pink-700 ring-pink-200" };
const priorityClass = { low: "bg-slate-100 text-slate-600 ring-slate-200", normal: "bg-blue-50 text-blue-700 ring-blue-200", high: "bg-amber-50 text-amber-700 ring-amber-200", urgent: "bg-red-50 text-red-700 ring-red-200" };

export default function AdminNotifications() {
  const queryClient = useQueryClient();
  const [roles, setRoles] = useState([]);
  const [recipientIds, setRecipientIds] = useState([]);
  const [recipientSearch, setRecipientSearch] = useState("");
  const [title, setTitle] = useState("");
  const [message, setMessage] = useState("");
  const [type, setType] = useState("system");
  const [priority, setPriority] = useState("normal");
  const [actionUrl, setActionUrl] = useState("");
  const [page, setPage] = useState(1);

  const recipientsQuery = useQuery({ queryKey: ["notification-recipients"], queryFn: async () => (await api.get("/notifications/recipients", { params: { roles: "guide,driver,agent,manager,admin" } })).data });
  const notificationsQuery = useQuery({ queryKey: ["admin-notifications", page], queryFn: async () => (await api.get("/notifications", { params: { page, limit: 5 } })).data });
  const recipients = recipientsQuery.data?.recipients || [];
  const notifications = notificationsQuery.data?.notifications || notificationsQuery.data?.data || [];
  const totalPages = Math.max(1, Number(notificationsQuery.data?.pages || notificationsQuery.data?.totalPages || 1));
  const filteredRecipients = useMemo(() => { const term = recipientSearch.trim().toLowerCase(); if (!term) return recipients; return recipients.filter((user) => `${userLabel(user)} ${user?.email || ""} ${roleLabel(user)}`.toLowerCase().includes(term)); }, [recipients, recipientSearch]);
  const selectedCount = recipientIds.length;
  const canSend = Boolean(title.trim() && message.trim() && (roles.length || recipientIds.length));

  const sendMutation = useMutation({
    mutationFn: async (payload) => (await api.post("/notifications/internal", payload)).data,
    onSuccess: (data) => { toast.success(data?.message || "Notification sent successfully."); setTitle(""); setMessage(""); setActionUrl(""); setRecipientIds([]); setRoles([]); queryClient.invalidateQueries({ queryKey: ["admin-notifications"] }); },
    onError: (error) => toast.error(error?.response?.data?.message || "Failed to send notification."),
  });
  const toggleRole = (role) => setRoles((current) => current.includes(role) ? current.filter((item) => item !== role) : [...current, role]);
  const toggleRecipient = (id) => setRecipientIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleVisibleRecipients = () => { const visibleIds = filteredRecipients.map((user) => user._id).filter(Boolean); const allSelected = visibleIds.length > 0 && visibleIds.every((id) => recipientIds.includes(id)); setRecipientIds((current) => allSelected ? current.filter((id) => !visibleIds.includes(id)) : [...new Set([...current, ...visibleIds])]); };
  const clearComposer = () => { setTitle(""); setMessage(""); setActionUrl(""); setRecipientIds([]); setRoles([]); };
  const submit = (event) => { event.preventDefault(); if (!title.trim() || !message.trim()) return toast.error("Enter a notification title and message."); if (!roles.length && !recipientIds.length) return toast.error("Select at least one recipient group or specific recipient."); if (actionUrl && !actionUrl.startsWith("/") && !/^https?:\/\//i.test(actionUrl)) return toast.error("Action URL must be a relative path or a valid http(s) URL."); sendMutation.mutate({ roles, recipientIds, title: title.trim(), message: message.trim(), type, priority, actionUrl: actionUrl.trim() }); };
  const formatDate = (value) => { if (!value) return "Date unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Date unavailable" : date.toLocaleString(); };

  return <div className="min-h-screen bg-gradient-to-br from-emerald-50/70 via-slate-50 to-sky-50/50 p-4 sm:p-6">
    <div className="mx-auto max-w-7xl space-y-6">
      <header className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-emerald-800 via-emerald-700 to-teal-700 p-6 text-white shadow-xl shadow-emerald-900/10 sm:p-7">
        <div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-white/10 blur-2xl" /><div className="absolute -bottom-24 left-1/3 h-48 w-48 rounded-full bg-teal-300/10 blur-2xl" />
        <div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="rounded-2xl bg-white/15 p-3.5 ring-1 ring-white/20 backdrop-blur"><Bell size={24} /></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-100">Administration</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Notifications</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-emerald-50/90">Send targeted operational messages to internal teams with clear recipient context and delivery visibility.</p></div></div><div className="inline-flex w-fit items-center gap-2 rounded-2xl bg-white/10 px-4 py-3 text-sm font-bold ring-1 ring-white/20 backdrop-blur"><Users size={17} /> {recipients.length} eligible recipients</div></div>
      </header>

      <form onSubmit={submit} className="overflow-hidden rounded-3xl bg-white shadow-lg shadow-slate-900/5 ring-1 ring-slate-200/80">
        <div className="flex items-center justify-between gap-3 border-b border-emerald-100 bg-gradient-to-r from-emerald-50/80 to-white px-5 py-5 sm:px-6"><div><h2 className="font-extrabold text-slate-900">Send internal notification</h2><p className="mt-1 text-xs text-slate-500">Choose groups, individuals, or both.</p></div><button type="button" onClick={clearComposer} className="inline-flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-bold text-slate-500 transition hover:bg-red-50 hover:text-red-600"><X size={14} /> Clear</button></div>
        <div className="space-y-6 p-5 sm:p-6">
          <div className="grid gap-6 lg:grid-cols-2">
            <div className="rounded-2xl bg-slate-50/70 p-4 ring-1 ring-slate-200/70"><label className="text-sm font-bold text-slate-800">Recipient groups</label><p className="mt-1 text-xs text-slate-500">Broadcast to operational teams by role.</p><div className="mt-3 flex flex-wrap gap-2">{groups.map(([value, label]) => { const selected = roles.includes(value); return <button key={value} type="button" onClick={() => toggleRole(value)} aria-pressed={selected} className={`rounded-xl border px-3.5 py-2 text-sm font-bold transition ${selected ? "border-emerald-600 bg-emerald-600 text-white shadow-md shadow-emerald-600/20" : "border-slate-200 bg-white text-slate-700 hover:-translate-y-0.5 hover:border-emerald-300 hover:bg-emerald-50 hover:text-emerald-800"}`}>{selected && <Check className="mr-1 inline" size={14} />}{label}</button>; })}</div>{roles.length > 0 && <p className="mt-3 rounded-lg bg-emerald-100 px-3 py-2 text-xs font-bold text-emerald-800">{roles.length} group{roles.length === 1 ? "" : "s"} selected</p>}</div>
            <div className="rounded-2xl bg-sky-50/50 p-4 ring-1 ring-sky-100"><div className="flex items-center justify-between gap-2"><div><label className="text-sm font-bold text-slate-800">Specific recipients</label><p className="mt-1 text-xs text-slate-500">Target individual staff members.</p></div><button type="button" onClick={toggleVisibleRecipients} disabled={!filteredRecipients.length} className="rounded-lg px-2 py-1.5 text-xs font-bold text-emerald-700 hover:bg-emerald-100 disabled:text-slate-300">Select / clear visible</button></div><div className="relative mt-3"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input value={recipientSearch} onChange={(event) => setRecipientSearch(event.target.value)} placeholder="Search name, email or role" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" /></div><div className="mt-2 max-h-52 overflow-y-auto rounded-xl border border-slate-200 bg-white">{recipientsQuery.isLoading ? <div className="flex items-center gap-2 p-4 text-sm text-slate-500"><Loader2 className="animate-spin text-emerald-600" size={16} /> Loading recipients...</div> : filteredRecipients.map((user) => { const selected = recipientIds.includes(user._id); return <label key={user._id} className={`flex cursor-pointer items-center gap-3 border-b border-slate-100 p-3 last:border-0 transition ${selected ? "bg-emerald-50" : "hover:bg-slate-50"}`}><input type="checkbox" checked={selected} onChange={() => toggleRecipient(user._id)} className="h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-slate-800">{userLabel(user)}</span><span className="block truncate text-xs text-slate-500">{roleLabel(user)}{user?.email ? ` · ${user.email}` : ""}</span></span>{selected && <Check size={16} className="shrink-0 text-emerald-600" />}</label>; })}{!recipientsQuery.isLoading && !filteredRecipients.length && <p className="p-4 text-sm text-slate-500">No matching active recipients.</p>}</div><p className="mt-2 text-xs font-semibold text-slate-500"><span className="text-emerald-700">{selectedCount}</span> specific recipient{selectedCount === 1 ? "" : "s"} selected</p></div>
          </div>

          <div className="grid gap-4 md:grid-cols-3"><div className="md:col-span-2"><div className="flex items-center justify-between"><label className="text-xs font-bold uppercase tracking-wide text-slate-600">Title</label><span className="text-[11px] font-semibold text-slate-400">{title.length}/120</span></div><input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} placeholder="Notification title" className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" /></div><div><label className="text-xs font-bold uppercase tracking-wide text-slate-600">Type</label><select value={type} onChange={(event) => setType(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm font-semibold outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100">{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div>
          <div className="grid gap-4 md:grid-cols-2"><div><label className="text-xs font-bold uppercase tracking-wide text-slate-600">Priority</label><select value={priority} onChange={(event) => setPriority(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm font-semibold outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100">{priorities.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><label className="text-xs font-bold uppercase tracking-wide text-slate-600">Action URL <span className="font-normal normal-case text-slate-400">(optional)</span></label><input value={actionUrl} onChange={(event) => setActionUrl(event.target.value)} placeholder="/admin/bookings or https://..." className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" /></div></div>
          <div><div className="flex items-center justify-between"><label className="text-xs font-bold uppercase tracking-wide text-slate-600">Message</label><span className="text-[11px] font-semibold text-slate-400">{message.length}/2000</span></div><textarea value={message} maxLength={2000} onChange={(event) => setMessage(event.target.value)} rows={5} placeholder="Write the operational message..." className="mt-1.5 w-full resize-y rounded-xl border border-slate-200 bg-white p-3 text-sm leading-6 outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" /></div>
          <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-slate-50/70 p-4 sm:flex-row sm:items-center sm:justify-between"><p className={`text-xs font-bold ${canSend ? "text-emerald-700" : "text-amber-700"}`}>{canSend ? "✓ Ready to send." : "Add a title, message and at least one recipient."}</p><button disabled={sendMutation.isPending || !canSend} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 px-5 py-3 text-sm font-extrabold text-white shadow-lg shadow-emerald-600/20 transition hover:-translate-y-0.5 hover:from-emerald-700 hover:to-teal-700 disabled:cursor-not-allowed disabled:opacity-50 disabled:shadow-none"><Send size={16} />{sendMutation.isPending ? "Sending..." : "Send notification"}</button></div>
        </div>
      </form>

      <section className="overflow-hidden rounded-3xl bg-white shadow-lg shadow-slate-900/5 ring-1 ring-slate-200/80"><div className="flex flex-col gap-3 border-b border-emerald-100 bg-gradient-to-r from-white to-emerald-50/60 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h2 className="font-extrabold text-slate-900">Recent notification activity</h2><p className="mt-1 text-xs text-slate-500">Notifications currently visible to this administrator account.</p></div><button type="button" onClick={() => notificationsQuery.refetch()} disabled={notificationsQuery.isFetching} className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-200 bg-white px-3.5 py-2 text-xs font-bold text-emerald-700 shadow-sm transition hover:bg-emerald-50 disabled:opacity-50"><RefreshCw className={notificationsQuery.isFetching ? "animate-spin" : ""} size={14} /> Refresh</button></div>
        <div className="divide-y divide-slate-100">{notificationsQuery.isLoading && <div className="flex items-center gap-2 p-6 text-sm text-slate-500"><Loader2 className="animate-spin text-emerald-600" size={17} /> Loading notification activity...</div>}{notificationsQuery.isError && <div className="m-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">Unable to load notification activity. Refresh and try again.</div>}{!notificationsQuery.isLoading && !notificationsQuery.isError && notifications.map((item) => <article key={item._id} className="p-5 transition hover:bg-emerald-50/30 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-emerald-100 p-1.5 text-emerald-700"><Bell size={13} /></span><h3 className="font-bold text-slate-900">{item.title || "Untitled notification"}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ring-1 ${typeClass[item.type] || typeClass.system}`}>{item.type || "system"}</span>{item.priority && <span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wide ring-1 ${priorityClass[item.priority] || priorityClass.normal}`}>{item.priority}</span>}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.message || "No message"}</p></div><time className="shrink-0 rounded-lg bg-slate-100 px-2.5 py-1.5 text-[11px] font-semibold text-slate-500">{formatDate(item.createdAt || item.updatedAt)}</time></div></article>)}{!notificationsQuery.isLoading && !notificationsQuery.isError && !notifications.length && <div className="m-5 rounded-2xl border border-dashed border-emerald-200 bg-emerald-50/40 p-10 text-center"><Bell className="mx-auto text-emerald-400" size={28} /><p className="mt-3 text-sm font-bold text-slate-700">No notification activity yet</p><p className="mt-1 text-xs text-slate-500">Sent internal notifications will appear here.</p></div>}</div>
        <div className="flex items-center justify-between border-t border-slate-100 bg-slate-50/60 px-5 py-4 sm:px-6"><button disabled={page <= 1 || notificationsQuery.isFetching} onClick={() => setPage((current) => Math.max(1, current - 1))} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-600 transition hover:border-emerald-300 hover:text-emerald-700 disabled:cursor-not-allowed disabled:opacity-40"><ChevronLeft size={16} /> Previous</button><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-extrabold text-emerald-800">Page {page} of {totalPages}</span><button disabled={page >= totalPages || notificationsQuery.isFetching} onClick={() => setPage((current) => Math.min(totalPages, current + 1))} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-600 transition hover:border-emerald-300 hover:text-emerald-700 disabled:cursor-not-allowed disabled:opacity-40">Next <ChevronRight size={16} /></button></div>
      </section>
    </div>
  </div>;
}
