import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Pencil, Trash2, Save, X } from "lucide-react";
import { toast } from "react-toastify";
import { getAdminHeroSlides, createAdminHeroSlide, updateAdminHeroSlide, deleteAdminHeroSlide } from "../../api/adminHeroApi";

const empty = { title: "", subtitle: "", badge: "Discover Africa", imageUrl: "", videoUrl: "", buttonOneText: "Explore Tours", buttonOneLink: "/tours", buttonTwoText: "Book Now", buttonTwoLink: "/contact", active: true, order: 0 };

export default function AdminHeroSlider() {
  const qc = useQueryClient(); const [editing, setEditing] = useState(null);
  const { data, isLoading } = useQuery({ queryKey: ["admin-hero-slides"], queryFn: getAdminHeroSlides });
  const slides = data?.slides || data?.data || [];
  const save = useMutation({ mutationFn: (payload) => payload._id ? updateAdminHeroSlide({ id: payload._id, ...payload }) : createAdminHeroSlide(payload), onSuccess: () => { qc.invalidateQueries({ queryKey: ["admin-hero-slides"] }); qc.invalidateQueries({ queryKey: ["heroSlides"] }); setEditing(null); toast.success("Hero slider saved."); }, onError: e => toast.error(e?.response?.data?.message || "Failed to save hero slide") });
  const remove = useMutation({ mutationFn: deleteAdminHeroSlide, onSuccess: () => { qc.invalidateQueries({ queryKey: ["admin-hero-slides"] }); qc.invalidateQueries({ queryKey: ["heroSlides"] }); toast.success("Hero slide deleted."); }, onError: e => toast.error(e?.response?.data?.message || "Failed to delete hero slide") });
  const submit = e => { e.preventDefault(); save.mutate(editing); };
  return <div className="min-h-screen bg-slate-50 p-4 md:p-6"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-emerald-700">Tenant Homepage</p><h1 className="text-3xl font-bold text-slate-950">Hero Slider</h1><p className="mt-1 text-slate-600">Only this tenant's slides are shown on its public homepage.</p></div><button onClick={() => setEditing({ ...empty })} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white"><Plus size={18}/> Add slide</button></div>
    {editing && <form onSubmit={submit} className="mb-6 rounded-2xl bg-white p-6 shadow ring-1 ring-slate-200"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{editing._id ? "Edit hero slide" : "Create hero slide"}</h2><button type="button" onClick={() => setEditing(null)}><X/></button></div><div className="grid gap-4 md:grid-cols-2"><Field label="Title"><input required value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></Field><Field label="Badge"><input value={editing.badge} onChange={e=>setEditing({...editing,badge:e.target.value})}/></Field><Field label="Description"><textarea rows="3" value={editing.subtitle} onChange={e=>setEditing({...editing,subtitle:e.target.value})}/></Field><Field label="Image URL"><input required value={editing.imageUrl} onChange={e=>setEditing({...editing,imageUrl:e.target.value})} placeholder="https://..."/></Field><Field label="Video URL (optional)"><input value={editing.videoUrl} onChange={e=>setEditing({...editing,videoUrl:e.target.value})}/></Field><Field label="Display order"><input type="number" value={editing.order} onChange={e=>setEditing({...editing,order:e.target.value})}/></Field><Field label="Primary button text"><input value={editing.buttonOneText} onChange={e=>setEditing({...editing,buttonOneText:e.target.value})}/></Field><Field label="Primary button link"><input value={editing.buttonOneLink} onChange={e=>setEditing({...editing,buttonOneLink:e.target.value})}/></Field><Field label="Secondary button text"><input value={editing.buttonTwoText} onChange={e=>setEditing({...editing,buttonTwoText:e.target.value})}/></Field><Field label="Secondary button link"><input value={editing.buttonTwoLink} onChange={e=>setEditing({...editing,buttonTwoLink:e.target.value})}/></Field></div><label className="mt-4 flex items-center gap-3"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/><span className="font-semibold">Publish this slide</span></label><div className="mt-5 flex justify-end"><button disabled={save.isPending} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white"><Save size={18}/>{save.isPending ? "Saving..." : "Save slide"}</button></div></form>}
    {isLoading ? <p>Loading hero slides...</p> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{slides.map(slide=><article key={slide._id} className="overflow-hidden rounded-2xl bg-white shadow ring-1 ring-slate-200"><img src={slide.image?.url || slide.image} alt={slide.title} className="h-52 w-full object-cover"/><div className="p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-bold text-lg">{slide.title}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${slide.active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{slide.active ? "Published" : "Draft"}</span></div><p className="mt-2 text-sm text-slate-600 line-clamp-2">{slide.subtitle}</p><div className="mt-4 flex gap-2"><button onClick={()=>setEditing({...empty,_id:slide._id,title:slide.title,subtitle:slide.subtitle,badge:slide.badge,imageUrl:slide.image?.url||"",videoUrl:slide.video?.url||"",buttonOneText:slide.buttonOne?.text,buttonOneLink:slide.buttonOne?.link,buttonTwoText:slide.buttonTwo?.text,buttonTwoLink:slide.buttonTwo?.link,active:slide.active,order:slide.order})} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 font-semibold"><Pencil size={15}/> Edit</button><button onClick={()=>window.confirm("Delete this hero slide?") && remove.mutate(slide._id)} className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-3 py-2 font-semibold text-red-600"><Trash2 size={15}/> Delete</button></div></div></article>)}</div>}</div></div>;
}
function Field({label,children}) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span>{children}</label>; }
