import { useEffect, useMemo, useState } from "react";
import { Search, Plus, RefreshCw, Pencil, Trash2, Tag, CheckCircle2, Clock3, XCircle, TicketPercent } from "lucide-react";
import { getCoupons, createCoupon, updateCoupon, deleteCoupon } from "../../api/couponApi";

const EMPTY={code:"",description:"",discountType:"percentage",amount:"",startDate:"",expiresAt:"",usageLimit:1,minimumBookingAmount:0,maximumDiscount:"",active:true};
const money=v=>`KES ${Number(v||0).toLocaleString("en-KE",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=v=>v?new Date(v).toLocaleDateString("en-KE",{day:"2-digit",month:"short",year:"numeric"}):"—";
const status=c=>{const n=new Date(),s=c.startDate&&new Date(c.startDate),e=c.expiresAt&&new Date(c.expiresAt);if(c.active===false)return"inactive";if(e&&e<n)return"expired";if(s&&s>n)return"scheduled";if(Number(c.usedCount||0)>=Number(c.usageLimit||0))return"used";return"active"};
const META={active:["Active","bg-emerald-50 text-emerald-700 border-emerald-200",CheckCircle2],scheduled:["Scheduled","bg-amber-50 text-amber-700 border-amber-200",Clock3],expired:["Expired","bg-red-50 text-red-700 border-red-200",XCircle],inactive:["Inactive","bg-slate-100 text-slate-600 border-slate-200",XCircle],used:["Limit reached","bg-blue-50 text-blue-700 border-blue-200",TicketPercent]};
function Badge({coupon}){const [label,cls,Icon]=META[status(coupon)];return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${cls}`}><Icon size={13}/>{label}</span>}

export default function AdminCoupons(){
 const[coupons,setCoupons]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[show,setShow]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[page,setPage]=useState(1);
 const load=async()=>{try{setLoading(true);setError("");const r=await getCoupons();setCoupons(Array.isArray(r?.coupons)?r.coupons:[])}catch(e){setError(e?.response?.data?.message||"Failed to load coupons. Please try again.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const field=(k,v)=>setForm(x=>({...x,[k]:v}));
 const create=()=>{setEditing(null);setForm({...EMPTY,startDate:new Date().toISOString().slice(0,10)});setShow(true);setError("")};
 const edit=c=>{setEditing(c);setForm({code:c.code||"",description:c.description||"",discountType:c.discountType||"percentage",amount:c.amount??"",startDate:c.startDate?new Date(c.startDate).toISOString().slice(0,10):"",expiresAt:c.expiresAt?new Date(c.expiresAt).toISOString().slice(0,10):"",usageLimit:c.usageLimit??1,minimumBookingAmount:c.minimumBookingAmount??0,maximumDiscount:c.maximumDiscount??"",active:c.active!==false});setShow(true);setError("")};
 const submit=async e=>{e.preventDefault();const amount=Number(form.amount),limit=Number(form.usageLimit),min=Number(form.minimumBookingAmount||0),max=form.maximumDiscount===""?null:Number(form.maximumDiscount);if(!form.code.trim())return setError("Coupon code is required.");if(!Number.isFinite(amount)||amount<0)return setError("Enter a valid discount amount.");if(form.discountType==="percentage"&&amount>100)return setError("Percentage discount cannot exceed 100%.");if(!Number.isInteger(limit)||limit<1)return setError("Usage limit must be at least 1.");if(!form.expiresAt)return setError("Expiry date is required.");if(form.startDate&&new Date(form.expiresAt)<=new Date(form.startDate))return setError("Expiry date must be after the start date.");if(max!==null&&(!Number.isFinite(max)||max<0))return setError("Enter a valid maximum discount.");try{setSaving(true);const p={code:form.code.trim().toUpperCase(),description:form.description.trim(),discountType:form.discountType,amount,startDate:form.startDate||undefined,expiresAt:form.expiresAt,usageLimit:limit,minimumBookingAmount:min,maximumDiscount:max,active:Boolean(form.active)};if(editing)await updateCoupon(editing._id,p);else await createCoupon(p);setShow(false);setEditing(null);setForm(EMPTY);await load()}catch(e){setError(e?.response?.data?.message||"Coupon operation failed.")}finally{setSaving(false)}};
 const remove=async c=>{if(!window.confirm(`Delete coupon ${c.code}? This cannot be undone.`))return;try{await deleteCoupon(c._id);await load()}catch(e){setError(e?.response?.data?.message||"Delete failed.")}};
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return coupons.filter(c=>(!q||`${c.code||""} ${c.description||""}`.toLowerCase().includes(q))&&(filter==="all"||status(c)===filter))},[coupons,search,filter]);
 useEffect(()=>setPage(1),[search,filter]);const pages=Math.max(1,Math.ceil(filtered.length/10)),p=Math.min(page,pages),rows=filtered.slice((p-1)*10,p*10);const active=coupons.filter(c=>status(c)==="active").length,expired=coupons.filter(c=>status(c)==="expired").length,usage=coupons.reduce((a,c)=>a+Number(c.usedCount||0),0);
 return <div className="min-h-full bg-slate-50 p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <header className="rounded-2xl bg-gradient-to-r from-emerald-800 via-emerald-700 to-green-600 p-6 text-white shadow-lg sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-emerald-100"><Tag size={17}/>Marketing & Sales</div><h1 className="text-2xl font-bold sm:text-3xl">Coupon Management</h1><p className="mt-2 text-sm text-emerald-50 sm:text-base">Create, schedule and manage promotional discounts for customers.</p></div><button onClick={create} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-semibold text-emerald-800 hover:bg-emerald-50"><Plus size={18}/>Create Coupon</button></div></header>
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Total Coupons",coupons.length,Tag,"text-slate-900"],["Active",active,CheckCircle2,"text-emerald-700"],["Expired",expired,XCircle,"text-red-700"],["Total Usage",usage,TicketPercent,"text-blue-700"]].map(([l,v,I,c])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><span className="text-sm font-medium text-slate-500">{l}</span><I size={18} className="text-slate-400"/></div><p className={`mt-2 text-2xl font-bold ${c}`}>{v.toLocaleString()}</p></div>)}</div>
  {error&&<div className="flex justify-between gap-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button onClick={()=>setError("")} className="font-semibold">Dismiss</button></div>}
  {show&&<form onSubmit={submit} className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-bold">{editing?"Edit coupon":"Create coupon"}</h2><p className="text-sm text-slate-500">Configure discount, validity and usage rules.</p></div><button type="button" onClick={()=>setShow(false)} className="text-sm font-semibold text-slate-500">Cancel</button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
   {["code","description"].map(k=><label key={k} className="text-sm font-medium text-slate-700">{k==="code"?"Code":"Description"}<input required={k==="code"} value={form[k]} onChange={e=>field(k,k==="code"?e.target.value.toUpperCase():e.target.value)} placeholder={k==="code"?"e.g. SUMMER20":"Optional description"} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-500"/></label>)}
   <label className="text-sm font-medium text-slate-700">Discount type<select value={form.discountType} onChange={e=>field("discountType",e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (KES)</option></select></label>
   <label className="text-sm font-medium text-slate-700">Discount amount<input required type="number" min="0" max={form.discountType==="percentage"?100:undefined} step="0.01" value={form.amount} onChange={e=>field("amount",e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>
   {[["startDate","Start date"],["expiresAt","Expiry date"]].map(([k,l])=><label key={k} className="text-sm font-medium text-slate-700">{l}<input required={k==="expiresAt"} type="date" value={form[k]} onChange={e=>field(k,e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"/></label>)}
   <label className="text-sm font-medium text-slate-700">Usage limit<input required type="number" min="1" step="1" value={form.usageLimit} onChange={e=>field("usageLimit",e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>
   <label className="text-sm font-medium text-slate-700">Minimum booking (KES)<input type="number" min="0" step="0.01" value={form.minimumBookingAmount} onChange={e=>field("minimumBookingAmount",e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>
   <label className="text-sm font-medium text-slate-700">Maximum discount (KES)<input type="number" min="0" step="0.01" value={form.maximumDiscount} onChange={e=>field("maximumDiscount",e.target.value)} placeholder="No cap" className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label>
  </div><label className="mt-4 flex items-center gap-3 text-sm font-medium"><input type="checkbox" checked={form.active} onChange={e=>field("active",e.target.checked)} className="h-4 w-4"/>Coupon is active</label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setShow(false)} className="rounded-xl border px-5 py-2.5 font-semibold">Cancel</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-2.5 font-semibold text-white disabled:opacity-60">{saving&&<RefreshCw size={16} className="animate-spin"/>}{editing?"Update Coupon":"Save Coupon"}</button></div></form>}
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:p-5 lg:flex-row lg:justify-between"><div className="relative w-full lg:max-w-md"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search coupon code or description..." className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-3"/></div><div className="flex gap-2"><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="all">All statuses</option><option value="active">Active</option><option value="scheduled">Scheduled</option><option value="expired">Expired</option><option value="inactive">Inactive</option><option value="used">Limit reached</option></select><button onClick={load} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm font-semibold"><RefreshCw size={16} className={loading?"animate-spin":""}/>Refresh</button></div></div>
   {loading?<div className="p-10 text-center text-sm text-slate-500">Loading coupons...</div>:rows.length===0?<div className="p-12 text-center"><TicketPercent className="mx-auto text-slate-300" size={42}/><h3 className="mt-3 font-semibold">{coupons.length?"No matching coupons":"No coupons yet"}</h3><p className="mt-1 text-sm text-slate-500">{coupons.length?"Try another search or status filter.":"Create your first promotional coupon to get started."}</p></div>:<div className="overflow-x-auto"><table className="min-w-[900px] w-full"><thead className="bg-slate-50 text-left text-xs font-bold uppercase text-slate-500"><tr><th className="px-5 py-4">Coupon</th><th>Discount</th><th>Validity</th><th>Status</th><th>Usage</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y">{rows.map(c=>{const used=Number(c.usedCount||0),lim=Number(c.usageLimit||0),remaining=Math.max(lim-used,0);return <tr key={c._id} className="hover:bg-emerald-50/30"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-2 text-emerald-700"><Tag size={17}/></div><div><p className="font-bold tracking-wide">{c.code}</p><p className="max-w-xs truncate text-xs text-slate-500">{c.description||"No description"}</p></div></div></td><td className="font-semibold">{c.discountType==="percentage"?`${Number(c.amount||0)}%`:money(c.amount)}{c.maximumDiscount!=null&&c.discountType==="percentage"&&<span className="block text-xs font-normal text-slate-500">Max {money(c.maximumDiscount)}</span>}</td><td className="text-sm text-slate-600">{date(c.startDate)}<span className="block text-xs text-slate-400">to {date(c.expiresAt)}</span></td><td><Badge coupon={c}/></td><td><div className="min-w-28 text-xs"><div className="flex justify-between"><span>{used} used</span><span>{lim} limit</span></div><div className="mt-1 h-1.5 rounded bg-slate-100"><div className="h-full rounded bg-emerald-600" style={{width:`${Math.min(100,used/Math.max(1,lim)*100)}%`}}/></div><span className="text-slate-400">{remaining} remaining</span></div></td><td className="px-5 text-right"><button onClick={()=>edit(c)} className="rounded-lg p-2 text-emerald-700 hover:bg-emerald-50"><Pencil size={17}/></button><button onClick={()=>remove(c)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></td></tr>})}</tbody></table></div>}
   {pages>1&&<div className="flex justify-between border-t px-5 py-4 text-sm"><span>Page {p} of {pages}</span><div className="flex gap-2"><button disabled={p===1} onClick={()=>setPage(x=>x-1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={p===pages} onClick={()=>setPage(x=>x+1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Next</button></div></div>}
  </section>
 </div></div>
}
