import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, CircleDollarSign, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { getCorporateAccounts, createCorporateAccount, reconcileCorporateAccount } from "../../api/operationsModuleApi";

const input="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";
const money=v=>`KES ${Number(v||0).toLocaleString("en-KE",{maximumFractionDigits:2})}`;
const unwrap=v=>Array.isArray(v)?v:(v?.items||v?.data||[]);
export default function CorporateAccounts(){
 const qc=useQueryClient(); const [open,setOpen]=useState(false); const q=useQuery({queryKey:["operations-corporate"],queryFn:getCorporateAccounts,staleTime:10000});
 const refresh=async()=>{await qc.invalidateQueries({queryKey:["operations-corporate"],refetchType:"active"});await q.refetch();};
 const create=useMutation({mutationFn:createCorporateAccount,onSuccess:async()=>{setOpen(false);await refresh();},onError:e=>alert(e?.response?.data?.message||e?.message||"Unable to create corporate account.")});
 const reconcile=useMutation({mutationFn:reconcileCorporateAccount,onSuccess:refresh,onError:e=>alert(e?.response?.data?.message||e?.message||"Unable to reconcile account.")});
 const rows=unwrap(q.data); const active=rows.filter(x=>x.status==="active"); const exposure=active.reduce((s,x)=>s+Number(x.currentBalance||0),0); const limits=active.reduce((s,x)=>s+Number(x.creditLimit||0),0);
 return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-[1450px] px-4 py-6 sm:px-6 lg:px-8"><header className="rounded-[28px] bg-slate-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Commercial credit</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Corporate accounts</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Manage business customers, credit exposure, payment terms and purchase-order controls separately from day-to-day procurement.</p></div><div className="flex gap-2"><button type="button" onClick={refresh} disabled={q.isFetching} aria-label="Refresh corporate accounts" className="rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm font-black disabled:cursor-wait disabled:opacity-60"><RefreshCw size={16} className={`mr-2 inline ${q.isFetching?"animate-spin":""}`}/>{q.isFetching?"Refreshing…":"Refresh"}</button><button type="button" onClick={()=>setOpen(true)} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black"><Plus size={16} className="mr-2 inline"/>Add corporate account</button></div></div></header>
 <section className="mt-5 grid gap-4 sm:grid-cols-3"><Kpi icon={Building2} label="Active accounts" value={active.length}/><Kpi icon={CircleDollarSign} label="Current exposure" value={money(exposure)}/><Kpi icon={ShieldCheck} label="Approved credit" value={money(limits)}/></section>
 <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-black">Account register</h2><p className="mt-1 text-sm text-slate-500">Tenant-scoped corporate customers and their live credit position.</p></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead><tr className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-400"><th className="p-4">Account</th><th className="p-4">KRA PIN</th><th className="p-4">Terms</th><th className="p-4">Credit limit</th><th className="p-4">Balance</th><th className="p-4">PO control</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(r=>{const over=Number(r.creditLimit||0)>0&&Number(r.currentBalance||0)>Number(r.creditLimit||0);return <tr key={r._id} className="border-b border-slate-100"><td className="p-4"><div className="font-black">{r.companyName}</div><div className="text-xs text-slate-400">{r.accountNumber||"Account number pending"}</div></td><td className="p-4">{r.kraPin||"—"}</td><td className="p-4 capitalize">{String(r.paymentTerms||"immediate").replaceAll("_"," ")}</td><td className="p-4">{money(r.creditLimit)}</td><td className={`p-4 font-black ${over?"text-red-600":""}`}>{money(r.currentBalance)}</td><td className="p-4">{r.requiresPurchaseOrder?<span className="font-bold text-emerald-700">Required</span>:"Optional"}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold capitalize">{r.status||"active"}</span></td><td className="p-4"><button type="button" onClick={()=>reconcile.mutate(r._id)} disabled={reconcile.isPending} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black hover:bg-slate-50 disabled:opacity-50">Reconcile</button></td></tr>})}{!rows.length&&<tr><td colSpan="8" className="p-12 text-center text-slate-500">{q.isLoading?"Loading corporate accounts…":"No corporate accounts have been created for this tenant."}</td></tr>}</tbody></table></div></section>
 {open&&<Modal onClose={()=>setOpen(false)} onSubmit={f=>create.mutate({companyName:f.get("companyName"),kraPin:f.get("kraPin"),paymentTerms:f.get("paymentTerms"),creditLimit:Number(f.get("creditLimit")||0),preferredPaymentMethod:f.get("preferredPaymentMethod"),requiresPurchaseOrder:f.get("requiresPurchaseOrder")==="on",status:"active",notes:f.get("notes")})} busy={create.isPending}/>}</div></main>;
}
const Kpi=({icon:Icon,label,value})=><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon size={18} className="text-emerald-600"/><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-[11px] font-black uppercase tracking-wider text-slate-400">{label}</p></div>;
function Modal({onClose,onSubmit,busy}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">New account</p><h2 className="mt-1 text-2xl font-black">Corporate customer</h2></div><button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-slate-500 hover:bg-slate-100">✕</button></div><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));}}><Field name="companyName" label="Company name" required/><Field name="kraPin" label="KRA PIN"/><Select name="paymentTerms" label="Payment terms" options={["immediate","7_days","14_days","30_days","60_days","90_days","staged"]}/><Field name="creditLimit" label="Credit limit (KES)" type="number" min="0" step="0.01"/><Select name="preferredPaymentMethod" label="Preferred payment" options={["BANK_TRANSFER","MPESA","CARD","CASH"]}/><label className="flex items-center gap-2 self-end text-sm font-semibold"><input name="requiresPurchaseOrder" type="checkbox"/> Require purchase order</label><label className="sm:col-span-2 text-xs font-semibold text-slate-600">Notes<textarea name="notes" className={input+" min-h-24"}/></label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">Cancel</button><button disabled={busy} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy?"Creating…":"Create account"}</button></div></form></div></div>}
const Field=({name,label,type="text",required,min,step})=><label className="text-xs font-semibold text-slate-600">{label}<input className={input} name={name} type={type} required={required} min={min} step={step}/></label>;
const Select=({name,label,options})=><label className="text-xs font-semibold text-slate-600">{label}<select className={input} name={name} defaultValue={options[0]}>{options.map(x=><option key={x}>{x}</option>)}</select></label>;
