import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, BedDouble, CalendarDays, Car, CheckCircle2, ClipboardList, Gauge, Plane, RefreshCw, WalletCards } from "lucide-react";
import { getHospitalityDashboard, getHotelCalendar, getHotelPerformance, getTransferDispatch, assignTransfer, updateTransferStatus, getHospitalityDrivers, getHospitalityVehicles, getHospitalityPaymentReconciliation } from "../../api/hospitalityOperationsApi";
import { getAdminHotels } from "../../api/hotelApi";

const money=(v,c="KES")=>`${c} ${Number(v||0).toLocaleString("en-KE",{maximumFractionDigits:2})}`;
const fmt=v=>v?new Date(v).toLocaleString("en-KE",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
const input="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";
const unwrap=v=>Array.isArray(v)?v:(v?.items||v?.data||[]);
export default function HospitalityOperations(){
 const qc=useQueryClient();const [tab,setTab]=useState("overview"),[hotelId,setHotelId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const dashboard=useQuery({queryKey:["hospitality-ops-dashboard"],queryFn:getHospitalityDashboard,staleTime:15000});
 const hotels=useQuery({queryKey:["admin-hotels"],queryFn:getAdminHotels,staleTime:30000});
 const perf=useQuery({queryKey:["hospitality-performance",hotelId],queryFn:()=>getHotelPerformance({hotelId:hotelId||undefined}),staleTime:15000});
 const calendar=useQuery({queryKey:["hospitality-calendar",hotelId,date],queryFn:()=>getHotelCalendar({hotelId,from:date,to:new Date(new Date(`${date}T00:00:00`).getTime()+14*86400000).toISOString()}),enabled:!!hotelId});
 const dispatch=useQuery({queryKey:["transfer-dispatch",date],queryFn:()=>getTransferDispatch({from:`${date}T00:00:00`,to:new Date(new Date(`${date}T00:00:00`).getTime()+86400000).toISOString()}),enabled:tab==="dispatch"});
 const drivers=useQuery({queryKey:["hospitality-drivers"],queryFn:getHospitalityDrivers,enabled:tab==="dispatch"});const vehicles=useQuery({queryKey:["hospitality-vehicles"],queryFn:getHospitalityVehicles,enabled:tab==="dispatch"});
 const reconciliation=useQuery({queryKey:["hospitality-reconciliation"],queryFn:()=>getHospitalityPaymentReconciliation({from:new Date(Date.now()-30*86400000).toISOString()}),enabled:tab==="reconciliation"});
 const assign=useMutation({mutationFn:({id,payload})=>assignTransfer(id,payload),onSuccess:()=>qc.invalidateQueries({queryKey:["transfer-dispatch"]})});
 const status=useMutation({mutationFn:({id,payload})=>updateTransferStatus(id,payload),onSuccess:()=>qc.invalidateQueries({queryKey:["transfer-dispatch"]})});
 const refreshQueries=[dashboard,hotels,perf,calendar,dispatch,drivers,vehicles,reconciliation];
 const isRefreshing=refreshQueries.some(q=>q.isFetching);
 const refresh=async()=>{await Promise.all(refreshQueries.filter(q=>q.isEnabled!==false).map(q=>q.refetch()));};
 const rooms=dashboard.data?.inventory||0;const p=perf.data||{};const days=calendar.data?.days||[];const transfers=unwrap(dispatch.data);const driversList=unwrap(drivers.data);const vehicleList=unwrap(vehicles.data);const reconc=reconciliation.data||{};
 return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-[1550px] px-4 py-6 sm:px-6 lg:px-8"><header className="rounded-[28px] bg-slate-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Production operations</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Hospitality command centre</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Run rooms, reservations, revenue, transfers, dispatch and payment reconciliation from one operations surface.</p></div><button type="button" onClick={refresh} disabled={isRefreshing} className="rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm font-black disabled:cursor-wait disabled:opacity-60"><RefreshCw size={16} className={`mr-2 inline ${isRefreshing?"animate-spin":""}`}/>{isRefreshing?"Refreshing…":"Refresh"}</button></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-5"><Kpi icon={BedDouble} label="Room inventory" value={rooms}/><Kpi icon={Plane} label="Today's transfers" value={dashboard.data?.todayTransfers??"—"}/><Kpi icon={ClipboardList} label="Today's check-ins" value={dashboard.data?.todayBookings??"—"}/><Kpi icon={WalletCards} label="30-day paid" value={money(dashboard.data?.last30DaysPaid)}/><Kpi icon={Gauge} label="Occupancy" value={`${p.occupancyPercent??0}%`}/></div></header><nav className="mt-5 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{[["overview","Performance",Gauge],["calendar","Occupancy calendar",CalendarDays],["dispatch","Transfer dispatch",Car],["reconciliation","M-Pesa reconciliation",WalletCards]].map(([id,label,Icon])=><button type="button" key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-black ${tab===id?"bg-slate-950 text-white":"text-slate-500 hover:bg-slate-50"}`}><Icon size={16} className="mr-2 inline"/>{label}</button>)}</nav>
 {tab==="overview"&&<section className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="Revenue & occupancy" icon={Activity}><div className="grid grid-cols-2 gap-3"><Metric label="ADR" value={money(p.adr)}/><Metric label="Revenue" value={money(p.revenue)}/><Metric label="Occupied room nights" value={p.occupiedRoomNights||0}/><Metric label="Bookings" value={p.bookings||0}/></div><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">Use ADR and occupancy together: ADR shows realised room revenue per occupied room night while occupancy shows inventory utilisation. Filter by property below when a portfolio view is required.</div></Panel><Panel title="Property performance scope" icon={BedDouble}><select className={input} value={hotelId} onChange={e=>setHotelId(e.target.value)}><option value="">All active properties</option>{unwrap(hotels.data).map(h=><option key={h._id} value={h._id}>{h.name} — {h.city}</option>)}</select><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Inventory room nights" value={p.inventoryRoomNights||0}/><Metric label="Occupancy" value={`${p.occupancyPercent||0}%`}/></div></Panel></section>}
 {tab==="calendar"&&<section className="mt-5"><Panel title="14-day room occupancy calendar" icon={CalendarDays}><div className="mb-5 flex flex-col gap-3 sm:flex-row"><select className={input} value={hotelId} onChange={e=>setHotelId(e.target.value)}><option value="">Select a hotel</option>{unwrap(hotels.data).map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select><input className={input} type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{!hotelId?<Empty text="Select a hotel to load daily sellable inventory."/>:<div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wider text-slate-400"><th className="p-3">Date</th><th className="p-3">Inventory</th><th className="p-3">Sold</th><th className="p-3">Blocked</th><th className="p-3">Available</th><th className="p-3">Occupancy</th></tr></thead><tbody>{days.map(d=><tr key={d.date} className="border-b border-slate-100"><td className="p-3 font-black">{d.date}</td><td className="p-3">{d.totalRooms}</td><td className="p-3">{d.soldRooms}</td><td className="p-3">{d.blockedRooms}</td><td className="p-3 font-black text-emerald-700">{d.availableRooms}</td><td className="p-3"><div className="flex items-center gap-3"><div className="h-2 w-28 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{width:`${Math.min(100,d.occupancyPercent)}%`}}/></div>{d.occupancyPercent}%</div></td></tr>)}</tbody></table></div>}</Panel></section>}
 {tab==="dispatch"&&<section className="mt-5"><Panel title={`Transfer dispatch — ${date}`} icon={Car}><div className="mb-5 flex gap-3"><input className={input} type="date" value={date} onChange={e=>setDate(e.target.value)}/><button type="button" onClick={()=>dispatch.refetch()} disabled={dispatch.isFetching} className="rounded-xl bg-slate-950 px-4 text-sm font-black text-white disabled:opacity-60">{dispatch.isFetching?"Loading…":"Load pickups"}</button></div><div className="space-y-3">{transfers.length?transfers.map(b=><DispatchCard key={b._id} booking={b} drivers={driversList} vehicles={vehicleList} assign={assign} status={status}/>):<Empty text="No transfer pickups for this date."/>}</div></Panel></section>}
 {tab==="reconciliation"&&<section className="mt-5"><Panel title="M-Pesa reconciliation" icon={WalletCards}><div className="grid gap-3 sm:grid-cols-3"><Metric label="Matched" value={reconc.matched||0}/><Metric label="Unmatched" value={reconc.unmatched||0}/><Metric label="Completed value" value={money(reconc.summary?.completed||0)}/></div><div className="mt-5 overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr className="border-b border-slate-200 text-left text-xs uppercase text-slate-400"><th className="p-3">Date</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Reference</th><th className="p-3">Receipt</th></tr></thead><tbody>{(reconc.rows||[]).map(r=><tr key={r._id} className="border-b border-slate-100"><td className="p-3">{fmt(r.createdAt)}</td><td className="p-3 font-black">{money(r.amount,r.currency)}</td><td className="p-3">{r.status}</td><td className="p-3">{r.transactionReference||r.transactionId||"—"}</td><td className="p-3">{r.mpesaReceiptNumber||"—"}</td></tr>)}</tbody></table></div></Panel></section>}</div></main>
}
function DispatchCard({booking,drivers,vehicles,assign,status}){const [driver,setDriver]=useState(booking.assignedDriver?._id||booking.assignedDriver||"");const [vehicle,setVehicle]=useState(booking.assignedVehicle?._id||booking.assignedVehicle||"");return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 lg:grid-cols-[1.2fr_1fr_1fr_auto]"><div><div className="flex items-center gap-2"><b>{booking.reference}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold">{String(booking.status||"").replaceAll("_"," ")}</span></div><p className="mt-2 text-sm font-bold text-slate-900">{booking.passengerName} · {booking.passengers} pax · {booking.luggage} bags</p><p className="mt-1 text-xs text-slate-500">{fmt(booking.pickupDateTime)} · {booking.pickupLocation} → {booking.dropoffLocation}</p><p className="mt-1 text-xs text-slate-500">Flight {booking.flightNumber||"—"} · {booking.airline||""} · {booking.terminal||""} · WhatsApp {booking.whatsappContact||booking.passengerPhone}</p></div><select className={input} value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Unassigned driver</option>{drivers.map(d=><option key={d._id} value={d._id}>{d.name||`${d.firstName||""} ${d.lastName||""}`.trim()} · {d.phone||""}</option>)}</select><select className={input} value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Unassigned vehicle</option>{vehicles.map(v=><option key={v._id} value={v._id}>{v.registration||v.registrationNumber||v.model||v.type||v._id}</option>)}</select><div className="flex flex-wrap gap-2"><button type="button" disabled={assign.isPending||!driver||!vehicle} onClick={()=>assign.mutate({id:booking._id,payload:{driverId:driver,vehicleId:vehicle,status:"assigned"}})} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-40">Assign</button><select className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold" value="" onChange={e=>e.target.value&&status.mutate({id:booking._id,payload:{status:e.target.value}})}><option value="">Update status</option>{["confirmed","assigned","driver_en_route","picked_up","completed","no_show","cancelled"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div></div></article>}
const Kpi=({icon:Icon,label,value})=><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><Icon size={17} className="text-emerald-300"/><p className="mt-3 text-xl font-black">{value}</p><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">{label}</p></div>;
const Panel=({title,icon:Icon,children})=><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="mb-5 flex items-center gap-2 text-lg font-black text-slate-900"><Icon size={19} className="text-emerald-600"/>{title}</h2>{children}</div>;
const Metric=({label,value})=><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black text-slate-900">{value}</p></div>;
const Empty=({text})=><div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">{text}</div>;
