import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BedDouble, CalendarClock, CheckCircle2, FileText, RefreshCw, Search, WalletCards, XCircle } from "lucide-react";
import { getAdminHotels, getHotelBookings } from "../../api/hotelApi";
import { getTransferBookings } from "../../api/airportTransferApi";
import { amendHotelBooking, cancelHotelBooking, blockRooms, getHospitalityDeposits, updateHospitalityDeposit } from "../../api/hospitalityOperationsApi";

const input="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";
const list=v=>Array.isArray(v)?v:(v?.items||v?.data||v?.bookings||v?.hotels||[]);
const money=(v,c="KES")=>`${c} ${Number(v||0).toLocaleString("en-KE",{maximumFractionDigits:2})}`;
const date=v=>v?new Date(v).toLocaleDateString("en-KE",{day:"2-digit",month:"short",year:"numeric"}):"—";
const dateTime=v=>v?new Date(v).toLocaleString("en-KE",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"—";
const title=v=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const error=e=>e?.response?.data?.message||e?.message||"The operation could not be completed.";

export default function HospitalityReservationOperations(){
 const qc=useQueryClient();
 const [tab,setTab]=useState("reservations");
 const [search,setSearch]=useState("");
 const [status,setStatus]=useState("all");
 const [type,setType]=useState("all");
 const [edit,setEdit]=useState(null);
 const [block,setBlock]=useState({hotelId:"",roomTypeId:"",startDate:"",endDate:"",quantity:1,reason:"Maintenance"});
 const [depositEdit,setDepositEdit]=useState(null);
 const hotelsQ=useQuery({queryKey:["admin-hotels"],queryFn:getAdminHotels,staleTime:30000});
 const hotelBookingsQ=useQuery({queryKey:["hotel-bookings"],queryFn:getHotelBookings,staleTime:15000});
 const transferBookingsQ=useQuery({queryKey:["transfer-bookings"],queryFn:getTransferBookings,staleTime:15000});
 const depositsQ=useQuery({queryKey:["hospitality-deposits"],queryFn:getHospitalityDeposits,staleTime:15000});
 const hotels=list(hotelsQ.data), hotelBookings=list(hotelBookingsQ.data), transferBookings=list(transferBookingsQ.data), deposits=list(depositsQ.data);
 const rows=useMemo(()=>[...hotelBookings.map(b=>({...b,_type:"hotel",_name:b.hotel?.name||"Hotel reservation",_guest:b.customer?.name||b.guests?.[0]?.firstName||b.passengerName||"Guest",_date:b.checkIn})),...transferBookings.map(b=>({...b,_type:"transfer",_name:b.transfer?.name||"Airport transfer",_guest:b.passengerName||b.customer?.name||"Passenger",_date:b.pickupDateTime}))].filter(b=>type==="all"||b._type===type).filter(b=>status==="all"||b.status===status).filter(b=>`${b.reference} ${b._name} ${b._guest}`.toLowerCase().includes(search.toLowerCase())),[hotelBookings,transferBookings,type,status,search]);
 const refresh=()=>[hotelsQ,hotelBookingsQ,transferBookingsQ,depositsQ].forEach(q=>q.refetch());
 const amend=useMutation({mutationFn:({id,payload})=>amendHotelBooking(id,payload),onSuccess:()=>{setEdit(null);qc.invalidateQueries({queryKey:["hotel-bookings"]});qc.invalidateQueries({queryKey:["hospitality-calendar"]})}});
 const cancel=useMutation({mutationFn:({id,reason})=>cancelHotelBooking(id,{reason}),onSuccess:()=>{qc.invalidateQueries({queryKey:["hotel-bookings"]});qc.invalidateQueries({queryKey:["hospitality-calendar"]})}});
 const blockM=useMutation({mutationFn:blockRooms,onSuccess:()=>{setBlock({...block,startDate:"",endDate:"",quantity:1});qc.invalidateQueries({queryKey:["hospitality-calendar"]})}});
 const depositM=useMutation({mutationFn:({id,payload})=>updateHospitalityDeposit(id,payload),onSuccess:()=>{setDepositEdit(null);qc.invalidateQueries({queryKey:["hospitality-deposits"]})}});
 const selectedHotel=hotels.find(h=>String(h._id)===String(block.hotelId));
 const rooms=selectedHotel?.roomTypes||[];
 return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8">
  <header className="rounded-[28px] bg-slate-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Reservation operations</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Bookings, room controls & deposits</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Amend stays, cancel eligible reservations, block room inventory and keep hospitality deposits aligned with the reservation lifecycle.</p></div><button onClick={refresh} className="rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm font-black"><RefreshCw size={16} className="mr-2 inline"/>Refresh</button></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4"><Kpi label="Reservations" value={rows.length}/><Kpi label="Hotel bookings" value={hotelBookings.length}/><Kpi label="Transfers" value={transferBookings.length}/><Kpi label="Deposits" value={deposits.length}/></div></header>
  <nav className="mt-5 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{[["reservations","Reservations",CalendarClock],["rooms","Room controls",BedDouble],["deposits","Deposits",WalletCards]].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-black ${tab===id?"bg-slate-950 text-white":"text-slate-500 hover:bg-slate-50"}`}><Icon size={16} className="mr-2 inline"/>{label}</button>)}</nav>
  {tab==="reservations"&&<section className="mt-5"><div className="mb-4 grid gap-3 md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className={`${input} pl-10`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Reference, guest or service…"/></div><select className={input} value={type} onChange={e=>setType(e.target.value)}><option value="all">All products</option><option value="hotel">Hotels</option><option value="transfer">Transfers</option></select><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{["pending","confirmed","assigned","driver_en_route","picked_up","checked_in","checked_out","completed","cancelled","no_show"].map(s=><option key={s} value={s}>{title(s)}</option>)}</select></div>{rows.length?<div className="space-y-3">{rows.map(b=><ReservationCard key={`${b._type}-${b._id}`} booking={b} edit={edit} setEdit={setEdit} amend={amend} cancel={cancel}/>)}</div>:<Empty text="No reservations match the selected filters."/>}</section>}
  {tab==="rooms"&&<section className="mt-5 grid gap-5 lg:grid-cols-[420px_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Block room inventory</h2><p className="mt-1 text-sm text-slate-500">Use blocks for maintenance, owner use, out-of-order rooms or operational holds. Blocks immediately reduce sellable availability.</p><div className="mt-5 space-y-4"><Field label="Hotel"><select className={input} value={block.hotelId} onChange={e=>setBlock({...block,hotelId:e.target.value,roomTypeId:""})}><option value="">Select hotel</option>{hotels.map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select></Field><Field label="Room type"><select className={input} value={block.roomTypeId} onChange={e=>setBlock({...block,roomTypeId:e.target.value})}><option value="">Select room type</option>{rooms.map(r=><option key={r._id} value={r._id}>{r.name} · {r.totalRooms} rooms</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Start"><input className={input} type="date" value={block.startDate} onChange={e=>setBlock({...block,startDate:e.target.value})}/></Field><Field label="End"><input className={input} type="date" value={block.endDate} onChange={e=>setBlock({...block,endDate:e.target.value})}/></Field></div><Field label="Quantity"><input className={input} type="number" min="1" value={block.quantity} onChange={e=>setBlock({...block,quantity:Number(e.target.value)})}/></Field><Field label="Reason"><select className={input} value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})}><option>Maintenance</option><option>Out of order</option><option>Owner use</option><option>Group hold</option><option>Operational hold</option></select></Field>{blockM.isError&&<Alert message={error(blockM.error)}/>}<button disabled={blockM.isPending||!block.roomTypeId||!block.startDate||!block.endDate} onClick={()=>blockM.mutate(block)} className="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40">{blockM.isPending?"Blocking inventory…":"Block rooms"}</button></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Availability workflow</h2><div className="mt-4 space-y-3"><Info title="Calendar impact" text="Blocked rooms are excluded from daily sellable inventory and occupancy availability."/><Info title="Stop-sell" text="Rate plans marked stop-sell return zero availability even when physical rooms remain."/><Info title="Booking safety" text="New and amended hotel bookings recheck overlapping reservations and room blocks before confirmation."/><Info title="Operational handover" text="Use the occupancy calendar in Hospitality Operations to verify the resulting inventory."/></div></div></section>}
  {tab==="deposits"&&<section className="mt-5"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">Hospitality deposits</h2><p className="text-sm text-slate-500">Track deposit obligations and paid amounts against hotel or transfer reservations.</p></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead><tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wider text-slate-400"><th className="p-3">Booking</th><th className="p-3">Type</th><th className="p-3">Amount</th><th className="p-3">Paid</th><th className="p-3">Due</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{deposits.map(d=><tr key={d._id} className="border-b border-slate-100"><td className="p-3 font-bold">{d.booking||d.bookingId||"—"}</td><td className="p-3">{title(d.bookingType||"hotel")}</td><td className="p-3 font-black">{money(d.amount,d.currency)}</td><td className="p-3">{money(d.paidAmount,d.currency)}</td><td className="p-3">{date(d.dueDate)}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{title(d.status)}</span></td><td className="p-3"><button onClick={()=>setDepositEdit(d)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black">Record payment</button></td></tr>)}</tbody></table>{!deposits.length&&<Empty text="No hospitality deposits have been created yet."/>}</div></div></section>}
  {edit&&<AmendModal booking={edit} close={()=>setEdit(null)} save={payload=>amend.mutate({id:edit._id,payload})} busy={amend.isPending}/>} {depositEdit&&<DepositModal deposit={depositEdit} close={()=>setDepositEdit(null)} save={payload=>depositM.mutate({id:depositEdit._id,payload})} busy={depositM.isPending}/>} 
 </div></main>;
}
function ReservationCard({booking,edit,setEdit,amend,cancel}){const hotel=booking._type==="hotel";return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{booking.reference||booking._id}</b><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase">{title(booking.status)}</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black uppercase text-emerald-700">{hotel?"Hotel":"Transfer"}</span></div><h3 className="mt-2 text-lg font-black">{booking._name}</h3><p className="mt-1 text-sm text-slate-600">{booking._guest} · {dateTime(booking._date)}</p><p className="mt-1 text-xs text-slate-500">{hotel?`${date(booking.checkIn)} → ${date(booking.checkOut)} · ${booking.rooms||1} room(s)`: `${booking.pickupLocation||"Pickup"} → ${booking.dropoffLocation||"Drop-off"} · ${booking.passengers||1} passenger(s)`}</p></div><div className="flex flex-wrap items-center gap-2"><span className="text-base font-black">{money(booking.totalAmount,booking.currency)}</span>{hotel&&["pending","confirmed"].includes(booking.status)&&<button onClick={()=>setEdit(booking)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black">Amend</button>}{hotel&&!['cancelled','checked_in','checked_out'].includes(booking.status)&&<button disabled={cancel.isPending} onClick={()=>{const reason=window.prompt("Cancellation reason","Cancelled by operations");if(reason!==null)cancel.mutate({id:booking._id,reason})}} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-black text-red-600">Cancel</button>}</div></div></article>}
function AmendModal({booking,close,save,busy}){const [form,setForm]=useState({checkIn:booking.checkIn?.slice(0,10)||"",checkOut:booking.checkOut?.slice(0,10)||"",rooms:booking.rooms||1,adults:booking.adults||1,children:booking.children||0,mealPlan:booking.mealPlan||"room_only",specialRequests:booking.specialRequests||""});return <Modal title={`Amend ${booking.reference||"reservation"}`} close={close}><div className="grid gap-4 sm:grid-cols-2"><Field label="Check-in"><input className={input} type="date" value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/></Field><Field label="Check-out"><input className={input} type="date" value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/></Field><Field label="Rooms"><input className={input} type="number" min="1" value={form.rooms} onChange={e=>setForm({...form,rooms:Number(e.target.value)})}/></Field><Field label="Adults"><input className={input} type="number" min="1" value={form.adults} onChange={e=>setForm({...form,adults:Number(e.target.value)})}/></Field><Field label="Children"><input className={input} type="number" min="0" value={form.children} onChange={e=>setForm({...form,children:Number(e.target.value)})}/></Field><Field label="Meal plan"><select className={input} value={form.mealPlan} onChange={e=>setForm({...form,mealPlan:e.target.value})}><option value="room_only">Room only</option><option value="bed_breakfast">Bed & breakfast</option><option value="half_board">Half board</option><option value="full_board">Full board</option></select></Field></div><Field label="Special requests"><textarea className={input} rows="3" value={form.specialRequests} onChange={e=>setForm({...form,specialRequests:e.target.value})}/></Field><div className="mt-5 flex justify-end gap-2"><button onClick={close} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black">Close</button><button disabled={busy} onClick={()=>save(form)} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">{busy?"Saving…":"Save amendment"}</button></div></Modal>}
function DepositModal({deposit,close,save,busy}){const [amount,setAmount]=useState(deposit.paidAmount||0);return <Modal title="Record deposit payment" close={close}><p className="text-sm text-slate-500">Deposit obligation: <b>{money(deposit.amount,deposit.currency)}</b>. Enter the cumulative amount received.</p><div className="mt-4"><Field label="Paid amount"><input className={input} type="number" min="0" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field></div><div className="mt-5 flex justify-end gap-2"><button onClick={close} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black">Close</button><button disabled={busy} onClick={()=>save({paidAmount:Number(amount||0)})} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">{busy?"Saving…":"Update deposit"}</button></div></Modal>}
const Modal=({title,close,children})=><div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={close} className="rounded-lg p-2 text-slate-500">×</button></div><div className="mt-5">{children}</div></div></div>;
const Field=({label,children})=><label className="block text-xs font-black uppercase tracking-wider text-slate-500">{label}<div className="mt-1">{children}</div></label>;
const Kpi=({label,value})=><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p></div>;
const Empty=({text})=><div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">{text}</div>;
const Alert=({message})=><div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{message}</div>;
const Info=({title,text})=><div className="rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="font-black text-slate-900">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p></div>;
