import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, Handshake, Plus, RefreshCw, WalletCards } from "lucide-react";
import { getAdminHotels } from "../../api/hotelApi";
import { createRatePlan, getRatePlans, createSupplierContract, getSupplierContracts, createHospitalityDeposit, getHospitalityDeposits } from "../../api/hospitalityOperationsApi";

const input="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10";
const money=v=>`KES ${Number(v||0).toLocaleString("en-KE",{maximumFractionDigits:2})}`;
export default function HospitalityCommercial(){
 const qc=useQueryClient();const [tab,setTab]=useState("rates");const hotels=useQuery({queryKey:["admin-hotels"],queryFn:getAdminHotels});const rates=useQuery({queryKey:["hospitality-rate-plans"],queryFn:getRatePlans});const suppliers=useQuery({queryKey:["hospitality-suppliers"],queryFn:getSupplierContracts});const deposits=useQuery({queryKey:["hospitality-deposits"],queryFn:getHospitalityDeposits});
 const [rate,setRate]=useState({hotel:"",roomType:"",name:"",price:"",currency:"KES",validFrom:"",validTo:"",stopSell:false});const [supplier,setSupplier]=useState({supplierName:"",supplierType:"hotel",hotel:"",contractReference:"",validFrom:"",validTo:"",rate:"",currency:"KES",depositRequired:false});const [deposit,setDeposit]=useState({booking:"",bookingType:"hotel",amount:"",dueDate:"",notes:""});
 const refresh=()=>[hotels,rates,suppliers,deposits].forEach(q=>q.refetch());
 const saveRate=useMutation({mutationFn:()=>createRatePlan({...rate,price:Number(rate.price||0)}),onSuccess:()=>{setRate({...rate,name:"",price:""});qc.invalidateQueries({queryKey:["hospitality-rate-plans"]})}});const saveSupplier=useMutation({mutationFn:()=>createSupplierContract({...supplier,rate:Number(supplier.rate||0)}),onSuccess:()=>qc.invalidateQueries({queryKey:["hospitality-suppliers"]})});const saveDeposit=useMutation({mutationFn:()=>createHospitalityDeposit({...deposit,amount:Number(deposit.amount||0)}),onSuccess:()=>{setDeposit({...deposit,booking:"",amount:"",notes:""});qc.invalidateQueries({queryKey:["hospitality-deposits"]})}});
 const hotelList=rates.data||[], supplierList=suppliers.data||[], depositList=deposits.data||[], allHotels=hotels.data||[];
 return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-[1450px] px-4 py-6 sm:px-6 lg:px-8"><header className="rounded-[28px] bg-slate-950 p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Hospitality commercial control</p><h1 className="mt-2 text-3xl font-black">Rates, suppliers & deposits</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Control contracted hotel rates, selling plans and reservation deposits without leaving the operations workspace.</p></div><button onClick={refresh} className="rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-sm font-black"><RefreshCw size={16} className="mr-2 inline"/>Refresh</button></div></header><nav className="mt-5 flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm">{[["rates","Rate plans",FileText],["suppliers","Supplier contracts",Handshake],["deposits","Deposits",WalletCards]].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-black ${tab===id?"bg-slate-950 text-white":"text-slate-500 hover:bg-slate-50"}`}><Icon size={16} className="mr-2 inline"/>{label}</button>)}</nav>
 {tab==="rates"&&<section className="mt-5 grid gap-5 lg:grid-cols-[390px_1fr]"><Form title="Create rate plan"><Field label="Hotel"><select className={input} value={rate.hotel} onChange={e=>setRate({...rate,hotel:e.target.value})}><option value="">Select hotel</option>{allHotels.map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select></Field><Field label="Room type ID"><input className={input} value={rate.roomType} onChange={e=>setRate({...rate,roomType:e.target.value})} placeholder="Room type ID"/></Field><Field label="Plan name"><input className={input} value={rate.name} onChange={e=>setRate({...rate,name:e.target.value})} placeholder="Flexible / Non-refundable / Corporate"/></Field><Field label="Selling price"><input className={input} type="number" min="0" value={rate.price} onChange={e=>setRate({...rate,price:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Valid from"><input className={input} type="date" value={rate.validFrom} onChange={e=>setRate({...rate,validFrom:e.target.value})}/></Field><Field label="Valid to"><input className={input} type="date" value={rate.validTo} onChange={e=>setRate({...rate,validTo:e.target.value})}/></Field></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={rate.stopSell} onChange={e=>setRate({...rate,stopSell:e.target.checked})}/> Stop sell</label><button disabled={saveRate.isPending||!rate.hotel||!rate.roomType||!rate.name||!rate.price} onClick={()=>saveRate.mutate()} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40"><Plus size={16} className="mr-2 inline"/>Save rate plan</button></Form><List title="Published rate plans">{hotelList.map(r=><Row key={r._id} title={r.name} meta={`${r.hotel?.name||"Hotel"} · ${r.roomType?.name||"Room"}`} value={money(r.price)} badge={r.stopSell?"STOP SELL":"SELLABLE"}/>)}</List></section>}
 {tab==="suppliers"&&<section className="mt-5 grid gap-5 lg:grid-cols-[390px_1fr]"><Form title="Supplier contract"><Field label="Supplier name"><input className={input} value={supplier.supplierName} onChange={e=>setSupplier({...supplier,supplierName:e.target.value})}/></Field><Field label="Hotel"><select className={input} value={supplier.hotel} onChange={e=>setSupplier({...supplier,hotel:e.target.value})}><option value="">Select hotel</option>{allHotels.map(h=><option key={h._id} value={h._id}>{h.name}</option>)}</select></Field><Field label="Contract reference"><input className={input} value={supplier.contractReference} onChange={e=>setSupplier({...supplier,contractReference:e.target.value})}/></Field><Field label="Contracted rate"><input className={input} type="number" value={supplier.rate} onChange={e=>setSupplier({...supplier,rate:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Valid from"><input className={input} type="date" value={supplier.validFrom} onChange={e=>setSupplier({...supplier,validFrom:e.target.value})}/></Field><Field label="Valid to"><input className={input} type="date" value={supplier.validTo} onChange={e=>setSupplier({...supplier,validTo:e.target.value})}/></Field></div><button disabled={saveSupplier.isPending||!supplier.supplierName} onClick={()=>saveSupplier.mutate()} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40"><Plus size={16} className="mr-2 inline"/>Save contract</button></Form><List title="Supplier contracts">{supplierList.map(s=><Row key={s._id} title={s.supplierName} meta={`${s.contractReference||"No reference"} · ${s.hotel?.name||"Portfolio"}`} value={money(s.rate,s.currency)} badge={s.status||"active"}/>)}</List></section>}
 {tab==="deposits"&&<section className="mt-5 grid gap-5 lg:grid-cols-[390px_1fr]"><Form title="Reservation deposit"><Field label="Booking ID"><input className={input} value={deposit.booking} onChange={e=>setDeposit({...deposit,booking:e.target.value})} placeholder="Hotel/transfer booking ID"/></Field><Field label="Amount"><input className={input} type="number" min="0" value={deposit.amount} onChange={e=>setDeposit({...deposit,amount:e.target.value})}/></Field><Field label="Due date"><input className={input} type="date" value={deposit.dueDate} onChange={e=>setDeposit({...deposit,dueDate:e.target.value})}/></Field><Field label="Notes"><textarea className={input} rows="4" value={deposit.notes} onChange={e=>setDeposit({...deposit,notes:e.target.value})}/></Field><button disabled={saveDeposit.isPending||!deposit.booking||!deposit.amount} onClick={()=>saveDeposit.mutate()} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40"><Plus size={16} className="mr-2 inline"/>Create deposit</button></Form><List title="Outstanding and received deposits">{depositList.map(d=><Row key={d._id} title={money(d.amount,d.currency)} meta={`Booking ${d.booking||d.bookingId||"—"} · Due ${d.dueDate?new Date(d.dueDate).toLocaleDateString("en-KE"):"—"}`} value={money(d.paidAmount,d.currency)} badge={d.status||"pending"}/>)}</List></section>}
 </div></main>;
}
const Field=({label,children})=><label className="block text-xs font-black uppercase tracking-wider text-slate-500">{label}<div className="mt-1">{children}</div></label>;
const Form=({title,children})=><div className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black text-slate-900">{title}</h2>{children}</div>;
const List=({title,children})=><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="mb-4 text-lg font-black text-slate-900">{title}</h2><div className="space-y-2">{children.length?children:<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No records yet.</div>}</div></div>;
const Row=({title,meta,value,badge})=><div className="flex flex-col gap-2 rounded-xl border border-slate-100 bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-sm text-slate-900">{title}</b><p className="mt-1 text-xs text-slate-500">{meta}</p></div><div className="flex items-center gap-3"><span className="text-sm font-black">{value}</span><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-black uppercase">{badge}</span></div></div>;
