import { useQuery, useQueries } from "@tanstack/react-query";
import { CalendarDays, Car, CheckCircle2, Users, UserRound, Wallet, Building2, Handshake, FileCheck2, Receipt, ShieldAlert, CircleDollarSign } from "lucide-react";
import { getOperationsOverview } from "../../api/operationsApi";
import { getCorporateAccounts, getPurchaseOrders, getResourceConflicts, getSupplierPayables, getSuppliers, getTourCosts } from "../../api/operationsModuleApi";
const asList=(value)=>Array.isArray(value)?value:value?.items||value?.data||[]; const money=(value)=>`KES ${Number(value||0).toLocaleString()}`;
export default function OperationsDashboard(){
 const {data,isLoading,isError}=useQuery({queryKey:["operations-overview"],queryFn:getOperationsOverview,refetchInterval:60000}); const moduleQueries=useQueries({queries:[
  {queryKey:["operations-suppliers"],queryFn:getSuppliers,staleTime:30000},{queryKey:["operations-purchase-orders"],queryFn:getPurchaseOrders,staleTime:30000},{queryKey:["operations-tour-costs"],queryFn:getTourCosts,staleTime:30000},{queryKey:["operations-payables"],queryFn:getSupplierPayables,staleTime:30000},{queryKey:["operations-corporate"],queryFn:getCorporateAccounts,staleTime:30000},{queryKey:["operations-conflicts"],queryFn:getResourceConflicts,staleTime:30000}]});
 const p=data?.data||{}; const s=p.stats||{}; const procurement=p.procurement||{}; const [suppliersQ,poQ,costsQ,payablesQ,corporateQ,conflictsQ]=moduleQueries; const suppliers=asList(suppliersQ.data),purchaseOrders=asList(poQ.data),tourCosts=asList(costsQ.data),payables=asList(payablesQ.data),corporate=asList(corporateQ.data),conflicts=asList(conflictsQ.data); if(isLoading)return <div className="p-8">Loading operations dashboard...</div>; if(isError)return <div className="p-8 text-red-600">Unable to load operations data.</div>;
 const cards=[["Today trips",s.todayTrips||0,CalendarDays],["Available vehicles",s.availableVehicles||0,Car],["Available guides",s.availableGuides||0,Users],["Available drivers",s.availableDrivers||0,UserRound],["Resource coverage",`${s.resourceCoverage||0}%`,CheckCircle2],["Outstanding payables",money(procurement.outstandingPayables),Wallet],["Corporate exposure",money(procurement.corporateExposure),Building2]];
 const moduleCards=[["Suppliers",suppliers.length,Handshake,"Active supplier records"],["Purchase Orders",purchaseOrders.length,FileCheck2,"Procurement documents"],["Tour Costs",money(tourCosts.reduce((sum,x)=>sum+Number(x.amount??x.totalCost??0),0)),CircleDollarSign,"Recorded operational costs"],["Supplier Payables",money(payables.reduce((sum,x)=>sum+Number(x.balance??x.outstanding??x.amount??0),0)),Receipt,"Supplier liability records"],["Corporate Accounts",corporate.length,Building2,"B2B customer accounts"],["Resource Conflicts",conflicts.length,ShieldAlert,"Detected scheduling conflicts"]];
 return <div className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-7xl"><div className="mb-8"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Tour delivery</p><h1 className="text-3xl font-bold">Operations & Procurement</h1><p className="mt-1 text-slate-500">Coordinate bookings, resources, suppliers, procurement, costing, payables and corporate exposure from one tenant-scoped workspace.</p></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between"><span className="text-sm text-slate-500">{label}</span><Icon size={19} className="text-emerald-700"/></div><div className="mt-3 text-2xl font-bold">{value}</div></div>)}</div>
 <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">ERP modules</p><h2 className="text-xl font-bold">Live operational records</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{moduleCards.map(([label,value,Icon,caption])=><div key={label} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><span className="font-semibold text-slate-800">{label}</span><Icon size={18} className="text-emerald-700"/></div><div className="mt-3 text-2xl font-black">{value}</div><p className="mt-1 text-xs text-slate-500">{caption}</p></div>)}</div></section>
 <div className="mt-6 grid gap-6 md:grid-cols-3"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Procurement</h2><p className="mt-2 text-sm text-slate-500">{procurement.activeSuppliers||0} active suppliers · {procurement.purchaseOrderCount||0} purchase orders</p><p className="mt-3 text-xl font-bold">KES {Number(procurement.purchaseOrderValue||0).toLocaleString()}</p><p className="text-xs text-slate-500">Purchase order value</p></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Tour costs</h2><p className="mt-3 text-xl font-bold">KES {Number(procurement.totalTourCost||0).toLocaleString()}</p><p className="text-xs text-slate-500">Active recorded tour costs</p></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">Corporate accounts</h2><p className="mt-3 text-xl font-bold">KES {Number(procurement.corporateExposure||0).toLocaleString()}</p><p className="text-xs text-slate-500">Current outstanding corporate exposure</p></div></div>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><RecordTable title="Suppliers" rows={suppliers} columns={[["Name",x=>x.name||x.companyName||x.businessName||"Supplier"],["Category",x=>x.category||x.type||"—"],["Phone",x=>x.phone||x.contactPhone||"—"],["Status",x=>x.status||"active"]]}/><RecordTable title="Purchase Orders" rows={purchaseOrders} columns={[["PO",x=>x.poNumber||x.number||x.reference||x._id?.slice(-8)||"—"],["Supplier",x=>x.supplier?.name||x.supplierName||"—"],["Value",x=>money(x.totalAmount??x.amount??x.total)], ["Status",x=>x.status||"draft"]]}/><RecordTable title="Supplier Payables" rows={payables} columns={[["Supplier",x=>x.supplier?.name||x.supplierName||"—"],["Reference",x=>x.reference||x.invoiceNumber||x._id?.slice(-8)||"—"],["Balance",x=>money(x.balance??x.outstanding??x.amount)],["Status",x=>x.status||"open"]]}/><RecordTable title="Corporate Accounts" rows={corporate} columns={[["Company",x=>x.companyName||x.name||"Corporate account"],["Credit limit",x=>money(x.creditLimit)],["Exposure",x=>money(x.outstandingBalance??x.currentBalance??x.balance)],["Status",x=>x.status||"active"]]}/></section>
 <div className="mt-6 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Upcoming trip schedule</h2><span className="text-sm text-slate-500">{p.schedule?.length||0} trips</span></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Tour</th><th className="p-3 text-left">Customer</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Payment</th></tr></thead><tbody>{(p.schedule||[]).map(b=><tr key={b._id} className="border-t"><td className="p-3">{b.travelDate?new Date(b.travelDate).toLocaleDateString():"—"}</td><td className="p-3 font-semibold">{b.tour?.title||"Tour"}</td><td className="p-3">{b.user?.name||b.customerSnapshot?.name||b.contact?.name||"Customer"}</td><td className="p-3 capitalize">{b.status||"pending"}</td><td className="p-3 capitalize">{b.paymentStatus||"pending"}</td></tr>)}{!(p.schedule||[]).length&&<tr><td colSpan="5" className="p-8 text-center text-slate-500">No upcoming trips.</td></tr>}</tbody></table></div></div>
 <div className="mt-6 grid gap-6 md:grid-cols-3">{[["Vehicles",p.vehicles||[]],["Guides",p.guides||[]],["Drivers",p.drivers||[]]].map(([title,list])=><div key={title} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-bold">{title}</h2><div className="mt-4 space-y-2">{list.slice(0,8).map(x=><div key={x._id} className="flex justify-between rounded-lg bg-slate-50 p-3"><span>{x.name||x.registrationNumber||x.plateNumber||x.email}</span><span className="text-xs capitalize text-slate-500">{x.status||x.availability||"ready"}</span></div>)}{!list.length&&<p className="text-sm text-slate-500">No resources found.</p>}</div></div>)}</div>
 </div></div>;
}
function RecordTable({title,rows,columns}){return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><h2 className="font-bold">{title}</h2><span className="text-xs text-slate-500">{rows.length} records</span></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{columns.map(([name])=><th key={name} className="p-2 text-left">{name}</th>)}</tr></thead><tbody>{rows.slice(0,10).map((row,i)=><tr key={row._id||i} className="border-t">{columns.map(([name,get])=><td key={name} className="p-2">{get(row)}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length} className="p-6 text-center text-slate-500">No records.</td></tr>}</tbody></table></div></div>}
