import { useQuery } from "@tanstack/react-query";
import api from "../../../api/axios";

const money = (n) => n == null ? "—" : `KES ${Number(n).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (v) => v ? new Date(v).toLocaleDateString("en-KE", { day: "2-digit", month: "2-digit", year: "numeric" }) : "—";
const label = (v) => String(v || "tour").replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const statusClass = (status) => status === "review_required" || status === "reviewable" || status === "uncollected_or_unlinked" ? "border-amber-200 bg-amber-50 text-amber-900" : "border-emerald-200 bg-emerald-50 text-emerald-900";

function ErrorBox({ query, name }) {
  return query.isError ? <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><b>{name} unavailable.</b> The API request failed, so fallback zeros are not presented as accounting values.</div> : null;
}
function Empty({ name }) {
  return <div className="px-4 py-10 text-center"><p className="font-semibold text-slate-700">No posted {name.toLowerCase()} activity</p><p className="mt-1 text-sm text-slate-500">No qualifying records exist for this reporting period.</p></div>;
}
function Metric({ title, value }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-slate-900">{money(value)}</p></div>;
}
function ReconciliationBadge({ status, children }) {
  return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${statusClass(status)}`}>{children}</span>;
}
function LedgerSummary({ data }) {
  if (!data) return null;
  return <div className="grid gap-3 border-t border-slate-100 bg-slate-50/70 p-4 sm:grid-cols-4">
    <div><p className="text-xs text-slate-500">Opening balance</p><p className="mt-1 font-bold text-slate-900">{money(data.openingBalance)}</p></div>
    <div><p className="text-xs text-slate-500">Period debit</p><p className="mt-1 font-semibold text-slate-800">{money(data.periodDebit)}</p></div>
    <div><p className="text-xs text-slate-500">Period credit</p><p className="mt-1 font-semibold text-slate-800">{money(data.periodCredit)}</p></div>
    <div><p className="text-xs text-slate-500">Closing balance</p><p className="mt-1 font-bold text-emerald-800">{money(data.closingBalance)}</p></div>
  </div>;
}

export default function AccountingControlReports() {
  const year = new Date().getFullYear();
  const from = `${year}-01-01`, to = `${year}-12-31`;
  const tax = useQuery({ queryKey: ["tax-control", year], queryFn: async () => (await api.get(`/admin/finance/accounting/tax-control?from=${from}&to=${to}`)).data, staleTime: 15000 });
  const customer = useQuery({ queryKey: ["customer-ledger", year], queryFn: async () => (await api.get(`/admin/finance/accounting/customer-ledger?from=${from}&to=${to}`)).data, staleTime: 15000 });
  const supplier = useQuery({ queryKey: ["supplier-ledger", year], queryFn: async () => (await api.get(`/admin/finance/accounting/supplier-ledger?from=${from}&to=${to}`)).data, staleTime: 15000 });
  const profitability = useQuery({ queryKey: ["profitability", year], queryFn: async () => (await api.get(`/admin/finance/accounting/profitability?from=${from}&to=${to}`)).data, staleTime: 15000 });
  const loading = [tax, customer, supplier, profitability].some(q => q.isLoading);
  const td = tax.data?.data, cd = customer.data?.data, sd = supplier.data?.data;
  const taxRows = td?.rows || [], customerRows = cd?.rows || [], supplierRows = sd?.rows || [], serviceRows = profitability.data?.data || [];
  const reconciliation = profitability.data?.reconciliation;

  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-gradient-to-br from-emerald-950 via-emerald-900 to-slate-900 p-6 text-white shadow-lg sm:p-8"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-300">Accounting controls</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Tax, Ledgers &amp; Profitability</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/80">Read-only controls from tenant-scoped posted journals, qualifying invoices and completed payments. Zeros are shown only when the corresponding report successfully confirms no qualifying activity.</p><p className="mt-4 inline-flex rounded-full bg-white/10 px-3 py-1.5 text-xs">Reporting period: {from} — {to}</p></header>
    <ErrorBox query={tax} name="Tax control report"/><ErrorBox query={customer} name="Customer ledger"/><ErrorBox query={supplier} name="Supplier ledger"/><ErrorBox query={profitability} name="Service billing report"/>
    {loading && <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">Loading accounting controls…</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Output VAT" value={tax.isError ? null : td?.outputVat}/><Metric title="Input VAT" value={tax.isError ? null : td?.inputVat}/><Metric title="Net VAT" value={tax.isError ? null : td?.netVat}/><Metric title="WHT payable" value={tax.isError ? null : td?.withholdingTaxPayable}/></section>
    {td?.reconciliation && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Tax reconciliation check</h2><p className="mt-1 text-sm text-slate-500">Invoice tax is a supporting basis; posted tax journals remain the accounting control source.</p></div><ReconciliationBadge status={td.reconciliation.status}>{td.reconciliation.status === "no_activity" ? "No qualifying activity" : "Reviewable control"}</ReconciliationBadge></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Qualifying invoices</p><p className="mt-1 text-lg font-bold text-slate-900">{td.reconciliation.invoiceCount}</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Invoice VAT basis</p><p className="mt-1 text-lg font-bold text-slate-900">{money(td.reconciliation.invoiceVatBasis)}</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Posted tax journal activity</p><p className="mt-1 text-lg font-bold text-slate-900">{money(td.reconciliation.postedTaxActivity)}</p></div></div><p className="mt-3 text-xs leading-5 text-slate-500">{td.reconciliation.note}</p></section>}
    <div className="grid gap-6 xl:grid-cols-2">
      {[["Customer ledger","Accounts receivable control account 1100",cd,customerRows,"customer",true],["Supplier ledger","Accounts payable control account 2000",sd,supplierRows,"supplier",false]].map(([title,sub,data,rows,type,normalDebit]) => <section key={title} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{sub}</p></div><div className="rounded-xl bg-emerald-50 px-3 py-2 text-right"><p className="text-xs text-emerald-700">Closing balance</p><p className="font-bold text-emerald-900">{customer.isError || supplier.isError ? "—" : money(data?.closingBalance)}</p></div></div></div><LedgerSummary data={customer.isError || supplier.isError ? null : data}/><div className="overflow-x-auto">{rows.length ? <table className="min-w-[980px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Date","Reference","Source","Debit","Credit","Balance"].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r._id||r.entryNumber||r.reference||"entry"}-${i}`} className="border-t border-slate-100 hover:bg-emerald-50/40"><td className="px-4 py-3 whitespace-nowrap">{date(r.entryDate)}</td><td className="px-4 py-3"><div className="font-medium text-slate-900">{r.reference||r.entryNumber||"Journal entry"}</div>{r.isDemoReference && <span className="mt-1 inline-flex rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-800">TEST / DEMO REFERENCE</span>}</td><td className="px-4 py-3"><div className="font-medium text-slate-700">{label(r.sourceType)}</div>{r.sourceId && <div className="max-w-[180px] truncate text-xs text-slate-400" title={String(r.sourceId)}>{String(r.sourceId)}</div>}</td><td className="px-4 py-3 text-right">{money(r.debit)}</td><td className="px-4 py-3 text-right">{money(r.credit)}</td><td className="px-4 py-3 text-right font-semibold">{money(r.balance)}</td></tr>)}</tbody></table> : <Empty name={type}/>}</div></section>)}
    </div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-bold text-slate-900">Service billing &amp; collection</h2><p className="mt-1 text-sm text-slate-500">Invoiced amounts are matched to qualifying payments through invoice number, tour booking or hospitality booking. This is not presented as profitability because service costs are not calculated here.</p></div>{reconciliation && <ReconciliationBadge status={reconciliation.status}>{reconciliation.status === "reconciled" ? "Payment links reconciled" : `${reconciliation.unmatchedPaymentCount} payment link${reconciliation.unmatchedPaymentCount === 1 ? "" : "s"} need review`}</ReconciliationBadge>}</div></div><div className="overflow-x-auto">{serviceRows.length ? <table className="min-w-[1120px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Service","Invoices","Invoiced","Collected","Refunded","Net collected","Outstanding","Net collection rate","Control"].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{serviceRows.map(r=><tr key={r.serviceType} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{label(r.serviceType)}</td><td className="px-4 py-3 text-center">{r.invoiceCount}</td><td className="px-4 py-3 text-right">{money(r.invoiced)}</td><td className="px-4 py-3 text-right">{money(r.collected)}</td><td className="px-4 py-3 text-right">{money(r.refunded)}</td><td className="px-4 py-3 text-right font-semibold">{money(r.netCollected)}</td><td className="px-4 py-3 text-right">{money(r.outstanding)}</td><td className="px-4 py-3 text-right font-semibold text-emerald-700">{r.collectionRate == null ? "—" : `${r.collectionRate}%`}</td><td className="px-4 py-3"><ReconciliationBadge status={r.reconciliationStatus}>{r.reconciliationStatus === "linked" ? `${r.linkedPaymentCount} linked payment${r.linkedPaymentCount === 1 ? "" : "s"}` : "No linked collection"}</ReconciliationBadge></td></tr>)}</tbody></table> : <Empty name="service billing"/>}</div>{reconciliation?.unmatchedPaymentCount > 0 && <div className="border-t border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-900"><b>Reconciliation review required:</b> {reconciliation.unmatchedPaymentCount} qualifying payment(s), totalling {money(reconciliation.unmatchedPaymentAmount)}, could not be linked to a qualifying invoice and were excluded from service totals to prevent misclassification. {reconciliation.note}</div>}</section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="text-lg font-bold text-slate-900">Tax control accounts</h2><p className="mt-1 text-sm text-slate-500">Posted journal balances for tax and statutory liability accounts only. No operational invoice value is silently substituted for a ledger balance.</p></div><div className="p-5">{taxRows.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{taxRows.map(r=><div key={r.code} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-semibold text-slate-900">{r.code} — {r.name}</p><p className="mt-2 text-xs text-slate-500">Debit {money(r.debit)} · Credit {money(r.credit)}</p><p className="mt-1 font-bold text-emerald-800">Balance {money(r.balance)}</p></div>)}</div> : <Empty name="tax"/>}</div></section>
  </div></main>;
}
