import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import api from "../../../api/axios";

const money = (n) => `KES ${Number(n || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const call = (method, url, data) => api({ method, url, data }).then((r) => r.data);

export default function AccountingCompletionCenter() {
  const qc = useQueryClient();
  const [year, setYear] = useState(new Date().getFullYear());
  const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7));
  const [asset, setAsset] = useState({ assetNumber: "", name: "", acquisitionDate: new Date().toISOString().slice(0, 10), acquisitionCost: "", residualValue: "0", usefulLifeMonths: "60" });
  const [budget, setBudget] = useState({ name: "", accountCode: "5200", fiscalYear: String(new Date().getFullYear()), month: "", amount: "" });
  const statements = useQuery({ queryKey: ["accounting-statements", year], queryFn: async () => (await api.get(`/admin/finance/accounting/statements?from=${year}-01-01&to=${year}-12-31`)).data });
  const ar = useQuery({ queryKey: ["accounting-ar"], queryFn: async () => (await api.get("/admin/finance/accounting/ar-aging")).data });
  const ap = useQuery({ queryKey: ["accounting-ap"], queryFn: async () => (await api.get("/admin/finance/accounting/ap-aging")).data });
  const cash = useQuery({ queryKey: ["accounting-cash", year], queryFn: async () => (await api.get(`/admin/finance/accounting/cash-flow?from=${year}-01-01&to=${year}-12-31`)).data });
  const assets = useQuery({ queryKey: ["accounting-assets"], queryFn: async () => (await api.get("/admin/finance/accounting/assets")).data });
  const budgets = useQuery({ queryKey: ["accounting-budgets", year], queryFn: async () => (await api.get(`/admin/finance/accounting/budgets?fiscalYear=${year}`)).data });
  const variance = useQuery({ queryKey: ["accounting-variance", year], queryFn: async () => (await api.get(`/admin/finance/accounting/budgets-vs-actual?fiscalYear=${year}`)).data });
  const periods = useQuery({ queryKey: ["accounting-periods"], queryFn: async () => (await api.get("/admin/finance/accounting/periods")).data });
  const wht = useQuery({ queryKey: ["accounting-wht"], queryFn: async () => (await api.get("/admin/finance/withholding-tax")).data });
  const reconciliation = useQuery({ queryKey: ["accounting-reconciliation"], queryFn: async () => (await api.get("/admin/payments/reconciliation")).data });
  const createAsset = useMutation({ mutationFn: () => call("post", "/admin/finance/accounting/assets", { ...asset, acquisitionCost: Number(asset.acquisitionCost), residualValue: Number(asset.residualValue), usefulLifeMonths: Number(asset.usefulLifeMonths) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounting-assets"] }); setAsset({ ...asset, assetNumber: "", name: "", acquisitionCost: "" }); } });
  const createBudget = useMutation({ mutationFn: () => call("post", "/admin/finance/accounting/budgets", { ...budget, fiscalYear: Number(budget.fiscalYear), month: budget.month ? Number(budget.month) : null, amount: Number(budget.amount) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounting-budgets", year] }); qc.invalidateQueries({ queryKey: ["accounting-variance", year] }); setBudget({ ...budget, name: "", amount: "" }); } });
  const close = useMutation({ mutationFn: () => call("post", `/admin/finance/accounting/periods/${period}/close`, { note: "Closed from Accounting Control Center" }), onSuccess: () => qc.invalidateQueries({ queryKey: ["accounting-periods"] }) });
  const reopen = useMutation({ mutationFn: (p) => call("post", `/admin/finance/accounting/periods/${p}/reopen`, {}), onSuccess: () => qc.invalidateQueries({ queryKey: ["accounting-periods"] }) });
  const summary = useMemo(() => ({ revenue: statements.data?.data?.profitAndLoss?.revenue ?? statements.data?.data?.revenue ?? 0, expenses: statements.data?.data?.profitAndLoss?.expenses ?? statements.data?.data?.expenses ?? 0, ar: ar.data?.data?.total ?? ar.data?.total ?? 0, ap: ap.data?.data?.total ?? ap.data?.total ?? 0, cash: cash.data?.data?.netCashFlow ?? cash.data?.netCashFlow ?? 0, wht: wht.data?.totals?.taxAmount ?? 0, unmatched: reconciliation.data?.data?.summary?.duplicateReferences ?? 0 }), [statements.data, ar.data, ap.data, cash.data, wht.data, reconciliation.data]);
  return <div className="min-h-screen bg-slate-50 p-6 space-y-6"><header><p className="text-sm font-semibold text-emerald-700">Production accounting</p><h1 className="text-3xl font-bold text-slate-900">Complete Accounting Control Center</h1><p className="mt-1 text-sm text-slate-600">Tenant-scoped financial control surface for the GL, tax, subledgers, reconciliation, management accounting and period close.</p></header>
    <div className="flex flex-wrap gap-2 items-end"><label className="text-xs text-slate-500">Reporting year<input type="number" value={year} onChange={(e) => setYear(e.target.value)} className="mt-1 block rounded border p-2 text-sm text-slate-900" /></label><a href="/admin/finance/reports" className="rounded border bg-white px-3 py-2 text-sm font-semibold">Financial reports</a><a href="/admin/finance/reconciliation" className="rounded border bg-white px-3 py-2 text-sm font-semibold">Reconciliation</a><a href="/admin/finance/withholding-tax" className="rounded border bg-white px-3 py-2 text-sm font-semibold">Withholding Tax</a><a href="/admin/finance/management" className="rounded border bg-white px-3 py-2 text-sm font-semibold">Management accounting</a></div>
    <section className="grid gap-4 md:grid-cols-3 lg:grid-cols-6">{[["Revenue", summary.revenue],["Expenses", summary.expenses],["AR", summary.ar],["AP", summary.ap],["Net cash flow", summary.cash],["WHT accrued", summary.wht]].map(([t,v]) => <div key={t} className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{t}</p><p className="mt-1 font-bold">{money(v)}</p></div>)}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Fixed assets</h2><div className="grid gap-2 md:grid-cols-2 mt-4">{[["assetNumber","Asset number"],["name","Name"],["acquisitionDate","Acquisition date"],["acquisitionCost","Cost"],["residualValue","Residual value"],["usefulLifeMonths","Useful life months"]].map(([k,l]) => <label key={k} className="text-xs text-slate-500">{l}<input type={k.includes("Cost")||k.includes("Months")||k==="residualValue"?"number":k==="acquisitionDate"?"date":"text"} value={asset[k]} onChange={(e) => setAsset({ ...asset, [k]: e.target.value })} className="mt-1 w-full rounded border p-2 text-sm text-slate-900" /></label>)}</div><button onClick={() => createAsset.mutate()} disabled={createAsset.isPending} className="mt-3 rounded bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Add asset</button><div className="mt-4 text-sm text-slate-600">Register: {assets.data?.data?.length ?? 0} assets</div></section>
      <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Budgets</h2><div className="grid gap-2 md:grid-cols-2 mt-4">{[["name","Budget name"],["accountCode","Account code"],["fiscalYear","Fiscal year"],["month","Month 1–12 optional"],["amount","Amount"]].map(([k,l]) => <label key={k} className="text-xs text-slate-500">{l}<input type={k==="amount"||k==="fiscalYear"||k==="month"?"number":"text"} value={budget[k]} onChange={(e) => setBudget({ ...budget, [k]: e.target.value })} className="mt-1 w-full rounded border p-2 text-sm text-slate-900" /></label>)}</div><button onClick={() => createBudget.mutate()} disabled={createBudget.isPending} className="mt-3 rounded bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Save budget</button><div className="mt-4 text-sm text-slate-600">Approved/planned rows: {budgets.data?.data?.length ?? 0} · variance rows: {variance.data?.data?.rows?.length ?? 0}</div></section></div>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Accounting periods</h2><p className="text-sm text-slate-500">Close only after draft journals are cleared. Reopening is explicitly recorded.</p></div><div className="flex gap-2 items-end"><label className="text-xs text-slate-500">Period<input type="month" value={period} onChange={(e) => setPeriod(e.target.value)} className="mt-1 rounded border p-2 text-sm text-slate-900" /></label><button onClick={() => close.mutate()} disabled={close.isPending} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Close period</button></div></div><div className="mt-4 grid gap-2 md:grid-cols-3">{(periods.data?.data || []).map((p) => <div key={p._id || p.period} className="rounded border p-3"><div className="flex justify-between"><b>{p.period}</b><span>{p.status}</span></div>{p.status === "closed" && <button onClick={() => reopen.mutate(p.period)} className="mt-2 text-xs font-semibold text-red-700">Reopen with authorization</button>}</div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Tax controls</h2><p className="mt-2 text-sm text-slate-600">WHT records: {wht.data?.data?.length ?? 0}. Accrued: {money(wht.data?.totals?.taxAmount)} · Remitted: {money(wht.data?.totals?.remittedAmount)}.</p><a href="/admin/compliance" className="mt-3 inline-block text-sm font-semibold text-emerald-700">Open KRA/eTIMS compliance</a></div><div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Reconciliation posture</h2><p className="mt-2 text-sm text-slate-600">Payments: {reconciliation.data?.data?.summary?.totalPayments ?? 0} · duplicate references: {reconciliation.data?.data?.summary?.duplicateReferences ?? 0} · missing receipts: {reconciliation.data?.data?.summary?.missingReceipts ?? 0} · orphan payments: {reconciliation.data?.data?.summary?.orphanPayments ?? 0}.</p><a href="/admin/finance/reconciliation" className="mt-3 inline-block text-sm font-semibold text-emerald-700">Review reconciliation exceptions</a></div></section>
  </div>;
}
