import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import api from "../../../api/axios";
import Pagination from "../../../components/admin/Pagination";

const PAGE_SIZE = 25;
const money = (n) => n == null ? "—" : `KES ${Number(n).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (v) => v ? new Date(v).toLocaleDateString("en-KE", { day: "2-digit", month: "2-digit", year: "numeric" }) : "—";
const label = (v) => String(v || "tour").replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const statusClass = (status) => ["review_required", "reviewable", "uncollected_or_unlinked", "typed_payment_unlinked"].includes(status) ? "border-amber-200 bg-amber-50 text-amber-900" : "border-emerald-200 bg-emerald-50 text-emerald-900";

function ErrorBox({ query, name }) { return query.isError ? <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><b>{name} unavailable.</b> The API request failed, so no fallback accounting values are displayed.</div> : null; }
function Empty({ name }) { return <div className="px-4 py-10 text-center"><p className="font-semibold text-slate-700">No posted {name.toLowerCase()} activity</p><p className="mt-1 text-sm text-slate-500">No qualifying records exist for this reporting period.</p></div>; }
function MissingAccount({ code, name }) { return <div className="px-4 py-8 text-center"><p className="font-semibold text-amber-800">Control account {code} is not configured</p><p className="mt-1 text-sm text-slate-500">{name} cannot be reported until the tenant chart of accounts contains an active {code} account. This is not treated as KES 0.00.</p></div>; }
function Metric({ title, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-slate-900">{money(value)}</p></div>; }
function Badge({ status, children }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${statusClass(status)}`}>{children}</span>; }
function LedgerSummary({ data }) { if (!data?.accountFound) return null; return <div className="grid gap-3 border-t border-slate-100 bg-slate-50/70 p-4 sm:grid-cols-4"><div><p className="text-xs text-slate-500">Opening balance</p><p className="mt-1 font-bold text-slate-900">{money(data.openingBalance)}</p></div><div><p className="text-xs text-slate-500">Period debit</p><p className="mt-1 font-semibold text-slate-800">{money(data.periodDebit)}</p></div><div><p className="text-xs text-slate-500">Period credit</p><p className="mt-1 font-semibold text-slate-800">{money(data.periodCredit)}</p></div><div><p className="text-xs text-slate-500">Closing balance</p><p className="mt-1 font-bold text-emerald-800">{money(data.closingBalance)}</p></div></div>; }
function LedgerSection({ title, sub, type, from, to }) {
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: [`${type}-ledger`, from, to, page], queryFn: async () => (await api.get(`/admin/finance/accounting/${type}-ledger?from=${from}&to=${to}&page=${page}&pageSize=${PAGE_SIZE}`)).data, staleTime: 15000, placeholderData: (previous) => previous });
  const data = query.data?.data;
  const p = data?.pagination || { page, pages: 0, total: 0, pageSize: PAGE_SIZE };
  const pageChange = (next) => { setPage(next); window.requestAnimationFrame(() => document.getElementById(`${type}-ledger`)?.scrollIntoView({ behavior: "smooth", block: "start" })); };
  return <section id={`${type}-ledger`} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{sub}</p></div><div className="rounded-xl bg-emerald-50 px-3 py-2 text-right"><p className="text-xs text-emerald-700">Closing balance</p><p className="font-bold text-emerald-900">{query.isError || !data?.accountFound ? "—" : money(data.closingBalance)}</p></div></div></div>{query.isError ? null : !data?.accountFound ? <MissingAccount code={data?.account || (type === "customer" ? "1100" : "2000")} name={type === "customer" ? "Accounts receivable" : "Accounts payable"}/> : <><LedgerSummary data={data}/>{query.isFetching && <div className="border-b border-emerald-100 bg-emerald-50 px-4 py-2 text-xs font-medium text-emerald-800">Updating ledger page…</div>}{data.rows?.length ? <><div className="overflow-x-auto"><table className="min-w-[1080px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Date","Reference","Source","Description","Debit","Credit","Balance"].map(h => <th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{data.rows.map(r => <tr key={`${r._id || r.entryNumber || r.reference}-${r.entryDate}`} className="border-t border-slate-100 hover:bg-emerald-50/40"><td className="whitespace-nowrap px-4 py-3">{date(r.entryDate)}</td><td className="px-4 py-3"><div className="font-medium text-slate-900">{r.reference || r.entryNumber || "Journal entry"}</div>{r.isDemoReference && <span className="mt-1 inline-flex rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-800">TEST / DEMO</span>}</td><td className="px-4 py-3"><div className="font-medium text-slate-700">{label(r.sourceType)}</div>{r.sourceId && <div className="max-w-[180px] truncate text-xs text-slate-400" title={String(r.sourceId)}>Source ID: {String(r.sourceId)}</div>}</td><td className="max-w-[240px] truncate px-4 py-3 text-slate-600" title={r.description || ""}>{r.description || "—"}</td><td className="px-4 py-3 text-right">{money(r.debit)}</td><td className="px-4 py-3 text-right">{money(r.credit)}</td><td className="px-4 py-3 text-right font-semibold">{money(r.balance)}</td></tr>)}</tbody></table></div><Pagination page={p.page} pages={p.pages} total={p.total} pageSize={p.pageSize} onPageChange={pageChange}/></> : <Empty name={type}/>}</>}</section>;
}

export default function AccountingControlReports() {
  const year = new Date().getFullYear();
  const from = `${year}-01-01`, to = `${year}-12-31`;
  const tax = useQuery({ queryKey: ["tax-control", year], queryFn: async () => (await api.get(`/admin/finance/accounting/tax-control?from=${from}&to=${to}`)).data, staleTime: 15000 });
  const profitability = useQuery({ queryKey: ["profitability", year], queryFn: async () => (await api.get(`/admin/finance/accounting/profitability?from=${from}&to=${to}`)).data, staleTime: 15000 });
  const td = tax.data?.data;
  const serviceRows = profitability.data?.data || [];
  const reconciliation = profitability.data?.reconciliation;
  const taxAccounts = td?.reconciliation?.availableTaxAccounts || [];
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <header className="rounded-3xl bg-gradient-to-br from-emerald-950 via-emerald-900 to-slate-900 p-6 text-white shadow-lg sm:p-8"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-300">Accounting controls</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Tax, Ledgers &amp; Profitability</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-50/80">Read-only controls from tenant-scoped posted journals, qualifying invoices and completed payments. Zeros are shown only when the corresponding report successfully confirms no qualifying activity.</p><p className="mt-4 inline-flex rounded-full bg-white/10 px-3 py-1.5 text-xs">Reporting period: {from} — {to}</p></header>
    <ErrorBox query={tax} name="Tax control report"/><ErrorBox query={profitability} name="Service billing report"/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Output VAT" value={tax.isError || !taxAccounts.includes("2110") ? null : td?.outputVat}/><Metric title="Input VAT" value={tax.isError || !taxAccounts.includes("2120") ? null : td?.inputVat}/><Metric title="Net VAT" value={tax.isError || !taxAccounts.includes("2110") || !taxAccounts.includes("2120") ? null : td?.netVat}/><Metric title="WHT payable" value={tax.isError || !taxAccounts.includes("2130") ? null : td?.withholdingTaxPayable}/></section>
    {td?.reconciliation && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">Tax reconciliation check</h2><p className="mt-1 text-sm text-slate-500">Invoice tax is a supporting basis; posted tax journals remain the accounting control source.</p></div><Badge status={td.reconciliation.status}>{td.reconciliation.status === "no_activity" ? "No qualifying activity" : "Reviewable control"}</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Configured tax accounts</p><p className="mt-1 text-lg font-bold text-slate-900">{td.reconciliation.configuredTaxAccounts} / 5</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Qualifying invoices</p><p className="mt-1 text-lg font-bold text-slate-900">{td.reconciliation.invoiceCount}</p></div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Invoice VAT basis</p><p className="mt-1 text-lg font-bold text-slate-900">{money(td.reconciliation.invoiceVatBasis)}</p></div></div><div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-500">Posted tax journal activity</p><p className="mt-1 font-bold text-slate-900">{money(td.reconciliation.postedTaxActivity)}</p><p className="mt-2 text-xs leading-5 text-slate-500">{td.reconciliation.note}</p></div>{taxAccounts.length < 5 && <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><b>Chart-of-accounts coverage is incomplete.</b> Available tax accounts: {taxAccounts.length ? taxAccounts.join(", ") : "none"}. Missing accounts are not represented as zero.</div>}</section>}
    <div className="grid gap-6 xl:grid-cols-2"><LedgerSection title="Customer ledger" sub="Accounts receivable control account 1100" type="customer" from={from} to={to}/><LedgerSection title="Supplier ledger" sub="Accounts payable control account 2000" type="supplier" from={from} to={to}/></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-bold text-slate-900">Service billing &amp; collection</h2><p className="mt-1 text-sm text-slate-500">Invoice-linked collections are reported normally. Payments carrying an explicit service type but missing an invoice link are included under that recorded service and remain flagged for reconciliation.</p></div>{reconciliation && <Badge status={reconciliation.status}>{reconciliation.status === "reconciled" ? "Payment links reconciled" : `${reconciliation.unmatchedPaymentCount} payment link${reconciliation.unmatchedPaymentCount === 1 ? "" : "s"} need review`}</Badge>}</div></div>{profitability.isError ? null : serviceRows.length ? <div className="overflow-x-auto"><table className="min-w-[1220px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Service","Invoices","Invoiced","Collected","Refunded","Net collected","Outstanding","Net collection rate","Control"].map(h => <th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{serviceRows.map(r => <tr key={r.serviceType} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{label(r.serviceType)}</td><td className="px-4 py-3 text-center">{r.invoiceCount}</td><td className="px-4 py-3 text-right">{money(r.invoiced)}</td><td className="px-4 py-3 text-right">{money(r.collected)}</td><td className="px-4 py-3 text-right">{money(r.refunded)}</td><td className="px-4 py-3 text-right font-semibold">{money(r.netCollected)}</td><td className="px-4 py-3 text-right">{money(r.outstanding)}</td><td className="px-4 py-3 text-right font-semibold text-emerald-700">{r.collectionRate == null ? "—" : `${r.collectionRate}%`}</td><td className="px-4 py-3"><Badge status={r.reconciliationStatus}>{r.reconciliationStatus === "linked" ? `${r.linkedPaymentCount} linked payment${r.linkedPaymentCount === 1 ? "" : "s"}` : r.reconciliationStatus === "typed_payment_unlinked" ? `${r.unlinkedTypedPaymentCount} typed payment${r.unlinkedTypedPaymentCount === 1 ? "" : "s"} need review` : "No linked collection"}</Badge></td></tr>)}</tbody></table></div> : <Empty name="service billing"/>}{reconciliation?.unmatchedPaymentCount > 0 && <div className="border-t border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-900"><b>Reconciliation review required:</b> {reconciliation.unmatchedPaymentCount} qualifying payment(s), totalling {money(reconciliation.unmatchedPaymentAmount)}, were not linked to a qualifying invoice. Explicitly typed payments remain under their recorded service and are flagged rather than silently reassigned.</div>}</section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="text-lg font-bold text-slate-900">Tax control accounts</h2><p className="mt-1 text-sm text-slate-500">Posted journal balances for tax and statutory liability accounts only. No operational invoice value is silently substituted for a ledger balance.</p></div><div className="p-5">{td?.rows?.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{td.rows.map(r => <div key={r.code} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-semibold text-slate-900">{r.code} — {r.name}</p><p className="mt-2 text-xs text-slate-500">Debit {money(r.debit)} · Credit {money(r.credit)}</p><p className="mt-1 font-bold text-emerald-800">Balance {money(r.balance)}</p></div>)}</div> : <Empty name="tax"/>}</div></section>
  </div></main>;
}
