import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { getReports, getFinancialStatements, getArAging, getApAging, getCashFlow } from "../../../api/financeApi";

const money = (value) => value === null || value === undefined ? "—" : `KES ${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const statusTone = { reconciled: "border-emerald-200 bg-emerald-50 text-emerald-800", review_required: "border-amber-200 bg-amber-50 text-amber-800", unavailable: "border-slate-200 bg-slate-50 text-slate-700" };
const Card = ({ title, value, hint, tone = "default" }) => <div className={`rounded-xl border p-5 shadow-sm ${tone === "warning" ? "border-amber-200 bg-amber-50" : "bg-white"}`}><p className="text-sm text-gray-500">{title}</p><p className="mt-1 text-2xl font-bold text-gray-900">{value}</p>{hint && <p className="mt-1 text-xs text-gray-500">{hint}</p>}</div>;
const Rows = ({ rows = [], empty = "No posted activity in this period" }) => <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Code</th><th className="p-3 text-left">Account</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={`${row.code}-${row.name}`} className="border-t"><td className="p-3 font-mono text-xs text-slate-500">{row.code}</td><td className="p-3">{row.name}</td><td className="p-3 text-right font-medium">{money(row.amount)}</td></tr>) : <tr><td colSpan="3" className="p-6 text-center text-gray-500">{empty}</td></tr>}</tbody></table></div>;
const Aging = ({ buckets = {} }) => <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[["Current", "current"], ["1–30 days", "1_30"], ["31–60 days", "31_60"], ["61–90 days", "61_90"], ["90+ days", "90_plus"]].map(([label, key]) => <div key={key} className="rounded-lg border bg-slate-50 p-3"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-semibold text-gray-900">{money(buckets[key])}</p></div>)}</div>;

function ReconciliationCard({ title, item }) {
  if (!item) return null;
  const tone = statusTone[item.status] || statusTone.unavailable;
  const label = item.status === "reconciled" ? "Reconciled" : item.status === "review_required" ? "Review required" : "Unavailable";
  return <div className={`rounded-xl border p-4 ${tone}`}><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{title}</h3><span className="rounded-full border px-2 py-1 text-xs font-semibold">{label}</span></div><div className="mt-3 grid gap-3 text-sm md:grid-cols-3"><div><p className="text-xs opacity-70">Control account {item.controlAccount}</p><p className="font-semibold">{money(item.controlBalance)}</p></div><div><p className="text-xs opacity-70">Operational outstanding</p><p className="font-semibold">{money(item.operationalOutstanding)}</p></div><div><p className="text-xs opacity-70">Variance</p><p className="font-semibold">{money(item.variance)}</p></div></div>{item.status === "review_required" && <p className="mt-3 text-xs font-medium">The operational balance does not agree with the posted control account. Do not close the period until the difference is investigated.</p>}</div>;
}

export default function FinanceReports() {
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const params = { ...(from ? { from } : {}), ...(to ? { to } : {}) };
  const statements = useQuery({ queryKey: ["financialStatements", params], queryFn: () => getFinancialStatements(params), retry: 1 });
  const ar = useQuery({ queryKey: ["arAging", params], queryFn: () => getArAging(params), retry: 1 });
  const ap = useQuery({ queryKey: ["apAging", params], queryFn: () => getApAging(params), retry: 1 });
  const cash = useQuery({ queryKey: ["cashFlow", params], queryFn: () => getCashFlow(params), retry: 1 });
  const reports = useQuery({ queryKey: ["financeReports", params], queryFn: () => getReports(params), retry: 1 });
  const data = statements.data?.data || {};
  const pnl = data.profitAndLoss || {};
  const bs = data.balanceSheet || {};
  const cashData = cash.data?.data || {};
  const arData = ar.data?.data || {};
  const apData = ap.data?.data || {};
  const monthly = reports.data?.monthlyRevenue || reports.data?.data?.monthlyRevenue || [];
  const findAccount = (rows, code) => rows.find((row) => String(row.code) === String(code));
  const arControl = findAccount(bs.assets || [], "1100");
  const apControl = findAccount(bs.liabilities || [], "2000");
  const arOutstanding = ar.isSuccess ? Number(arData.totalOutstanding || 0) : null;
  const apOutstanding = ap.isSuccess ? Number(apData.totalOutstanding || 0) : null;
  const reconciliation = {
    accountsReceivable: { controlAccount: "1100", controlBalance: arControl ? Number(arControl.amount || 0) : null, operationalOutstanding: arOutstanding, variance: arControl && arOutstanding !== null ? Number(arControl.amount || 0) - arOutstanding : null, status: !arControl || arOutstanding === null ? "unavailable" : Math.abs(Number(arControl.amount || 0) - arOutstanding) <= 0.01 ? "reconciled" : "review_required" },
    accountsPayable: { controlAccount: "2000", controlBalance: apControl ? Number(apControl.amount || 0) : null, operationalOutstanding: apOutstanding, variance: apControl && apOutstanding !== null ? Number(apControl.amount || 0) - apOutstanding : null, status: !apControl || apOutstanding === null ? "unavailable" : Math.abs(Number(apControl.amount || 0) - apOutstanding) <= 0.01 ? "reconciled" : "review_required" },
  };
  const loading = statements.isLoading || ar.isLoading || ap.isLoading || cash.isLoading;
  const error = statements.isError || ar.isError || ap.isError || cash.isError;
  const hasReview = reconciliation.accountsReceivable.status === "review_required" || reconciliation.accountsPayable.status === "review_required" || bs.balanced === false;
  const periodLabel = data.period?.from || data.period?.to ? `${data.period?.from || "start"} to ${data.period?.to || "present"}` : "Current posted accounting activity";

  return <div className="space-y-6 bg-slate-50 p-4 md:p-6">
    <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-emerald-700">Tenant-scoped accounting</p><h1 className="text-3xl font-bold tracking-tight text-slate-900">Financial Reports</h1><p className="mt-1 text-sm text-slate-500">Production P&amp;L, balance sheet, cash flow, receivables and supplier liabilities.</p><p className="mt-2 text-xs font-medium text-slate-500">Report basis: posted journals · {periodLabel}</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-medium text-slate-500">From<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="mt-1 block rounded-lg border p-2 text-sm text-slate-900" /></label><label className="text-xs font-medium text-slate-500">To<input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="mt-1 block rounded-lg border p-2 text-sm text-slate-900" /></label><button onClick={() => { setFrom(""); setTo(""); }} className="rounded-lg border bg-white px-3 py-2 text-sm font-medium hover:bg-slate-50">Clear</button></div></div></div>
    {loading && <div className="rounded-xl border bg-white p-4 text-sm text-slate-600">Loading accounting reports…</div>}
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p className="font-semibold">Accounting data could not be fully loaded.</p><p className="mt-1">Unavailable values are shown as —. The system does not convert an API failure into KES 0.00.</p></div>}
    {hasReview && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Accounting control review required</p><p className="mt-1">At least one control-account reconciliation or balance-sheet check is outside tolerance. Investigate the variance before period close.</p></div>}
    <div className="grid gap-4 md:grid-cols-4"><Card title="Revenue" value={money(pnl.totalRevenue)} hint="Posted revenue, not cash collected" /><Card title="Expenses" value={money(pnl.totalExpenses)} hint="Posted expense activity" /><Card title="Net profit" value={money(pnl.netProfit)} hint="Revenue less posted expenses" /><Card title="Cash position" value={money(data.cash?.position)} hint="Cash, bank, M-Pesa and gateway clearing" /></div>
    <section className="rounded-xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-semibold">Profit &amp; Loss</h2><p className="text-sm text-gray-500">Posted accounting activity for the selected period. Revenue is not the same as cash collected.</p></div><div className="p-5"><Rows rows={pnl.revenue} empty="No posted revenue in this period" /><div className="my-4 border-t pt-4"><Rows rows={pnl.expenses} empty="No posted expenses in this period" /></div><div className="flex flex-col gap-2 border-t pt-4 text-sm sm:flex-row sm:justify-end sm:gap-8"><span>Total revenue <b>{money(pnl.totalRevenue)}</b></span><span>Total expenses <b>{money(pnl.totalExpenses)}</b></span><span>Net profit <b>{money(pnl.netProfit)}</b></span></div></div></section>
    <section className="rounded-xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-semibold">Balance Sheet</h2><p className="text-sm text-gray-500">Posted assets, liabilities and equity, with current-year result shown separately.</p></div><div className="grid gap-6 p-5 lg:grid-cols-2"><div><h3 className="mb-3 font-semibold">Assets</h3><Rows rows={bs.assets} /><p className="mt-3 text-right font-bold">Total assets: {money(bs.totalAssets)}</p></div><div><h3 className="mb-3 font-semibold">Liabilities &amp; equity</h3><Rows rows={[...(bs.liabilities || []), ...(bs.equity || []), { code: "CURRENT", name: "Current-year result", amount: bs.currentYearResult }]} /><p className="mt-3 text-right font-bold">Liabilities + equity: {money(bs.liabilitiesAndEquity)}</p><p className={`mt-1 text-right text-sm font-semibold ${bs.balanced ? "text-emerald-700" : "text-red-700"}`}>{bs.balanced ? "Balanced within KES 0.01 tolerance" : "Out of balance — investigate before close"}</p></div></div></section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="text-xl font-semibold">Control Reconciliation</h2><p className="text-sm text-gray-500">Operational aging is compared with the corresponding posted control account. A variance is a control issue, not a missing zero.</p></div><div className="grid gap-4 lg:grid-cols-2"><ReconciliationCard title="Accounts Receivable" item={reconciliation.accountsReceivable} /><ReconciliationCard title="Accounts Payable" item={reconciliation.accountsPayable} /></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Accounts Receivable Aging</h2><p className="mb-4 text-sm text-gray-500">Outstanding customer and corporate invoices from the operational invoice ledger.</p><Aging buckets={arData.buckets} /><p className="mt-4 text-right font-bold">Outstanding: {money(arData.totalOutstanding)}</p></div><div className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Accounts Payable Aging</h2><p className="mb-4 text-sm text-gray-500">Outstanding supplier liabilities from the supplier-payable ledger.</p><Aging buckets={apData.buckets} /><p className="mt-4 text-right font-bold">Outstanding: {money(apData.totalOutstanding)}</p></div></section>
    <section className="rounded-xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-semibold">Cash Flow</h2><p className="text-sm text-gray-500">Posted movements through cash, bank, M-Pesa and gateway-clearing accounts. This is cash movement, not revenue.</p></div><div className="grid gap-4 p-5 md:grid-cols-3"><Card title="Inflows" value={money(cashData.inflows)} /><Card title="Outflows" value={money(cashData.outflows)} /><Card title="Net movement" value={money(cashData.netMovement)} /></div><div className="overflow-x-auto px-5 pb-5"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Account</th><th className="p-3 text-left">Description</th><th className="p-3 text-right">Movement</th></tr></thead><tbody>{(cashData.movements || []).slice(-100).reverse().map((m, i) => <tr key={`${m.date}-${i}`} className="border-t"><td className="p-3">{m.date ? new Date(m.date).toLocaleDateString() : "—"}</td><td className="p-3 font-mono text-xs">{m.accountCode || "—"}</td><td className="p-3">{m.description || "—"}{m.reference && /DEMO|TEST/i.test(m.reference) && <span className="ml-2 rounded-full border border-amber-200 bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-800">TEST/DEMO</span>}</td><td className={`p-3 text-right font-medium ${Number(m.amount) >= 0 ? "text-emerald-700" : "text-red-700"}`}>{money(m.amount)}</td></tr>)}</tbody></table>{!cashData.movements?.length && !cash.isLoading && <p className="py-8 text-center text-sm text-slate-500">No posted cash movements are available for this period.</p>}</div></section>
    <section className="rounded-xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-semibold">Monthly Revenue</h2><p className="text-sm text-gray-500">Posted revenue trend from the existing finance reporting source. It is intentionally separate from cash-flow collections.</p></div><div className="p-5">{monthly.length ? <div className="grid gap-3 md:grid-cols-3">{monthly.map((r, i) => <div key={i} className="rounded-lg border p-4"><p className="text-sm text-gray-500">{r?._id?.month || "—"}/{r?._id?.year || "—"}</p><p className="mt-1 text-lg font-semibold">{money(r.revenue)}</p></div>)}</div> : <p className="text-sm text-gray-500">No monthly posted revenue records are available.</p>}</div></section>
  </div>;
}
