import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import api from "../../../api/axios";
const money=(n)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:2}).format(Number(n||0));
const year=new Date().getFullYear();
export default function ManagementAccounting(){
 const [assets,setAssets]=useState([]),[budgets,setBudgets]=useState([]),[periods,setPeriods]=useState([]),[variance,setVariance]=useState([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [a,b,p,v]=await Promise.all([api.get("/admin/finance/accounting/assets"),api.get(`/admin/finance/accounting/budgets?fiscalYear=${year}`),api.get("/admin/finance/accounting/periods"),api.get(`/admin/finance/accounting/budgets-vs-actual?fiscalYear=${year}`)]);setAssets(a.data?.data||[]);setBudgets(b.data?.data||[]);setPeriods(p.data?.data||[]);setVariance(v.data?.data?.rows||[]);}catch(e){setError(e?.response?.data?.message||e.message||"Unable to load management accounting.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const run=async(key,fn)=>{setBusy(key);setError("");setNotice("");try{await fn();setNotice("Accounting operation completed successfully.");await load();}catch(e){setError(e?.response?.data?.message||e.message||"Accounting operation failed.");}finally{setBusy("");}};
 const totals=useMemo(()=>({assets:assets.reduce((s,a)=>s+Number(a.acquisitionCost||0),0),budget:budgets.reduce((s,b)=>s+Number(b.amount||0),0),actual:variance.reduce((s,b)=>s+Number(b.actual||0),0)}),[assets,budgets,variance]);
 const depreciate=(a)=>{const months=Number(window.prompt("Number of depreciation months","1"));if(!Number.isInteger(months)||months<1)return;const period=window.prompt("Depreciation period (YYYY-MM)",new Date().toISOString().slice(0,7));if(!/^\\d{4}-(0[1-9]|1[0-2])$/.test(period||""))return;return run(`dep-${a._id}`,()=>api.post(`/admin/finance/accounting/assets/${a._id}/depreciate`,{months,period}));};
 const dispose=(a)=>{const proceeds=Number(window.prompt("Disposal proceeds (KES)","0"));if(!Number.isFinite(proceeds)||proceeds<0)return;const reference=window.prompt("Disposal reference",`DISP-${a.assetNumber}`)||`DISP-${a.assetNumber}`;return run(`disp-${a._id}`,()=>api.post(`/admin/finance/accounting/assets/${a._id}/dispose`,{proceeds,reference}));};
 const approveBudget=(b)=>run(`budget-${b._id}`,()=>api.post(`/admin/finance/accounting/budgets/${b._id}/approve`));
 const closePeriod=(p)=>run(`close-${p}`,()=>api.post(`/admin/finance/accounting/periods/${p}/close`,{note:"Closed from Management Accounting."}));
 const reopenPeriod=(p)=>run(`reopen-${p}`,()=>api.post(`/admin/finance/accounting/periods/${p}/reopen`));
 const closeYear=()=>{if(!window.confirm(`Close fiscal year ${year} and transfer the calculated profit/loss to retained earnings?`))return;return run(`year-${year}`,()=>api.post(`/admin/finance/accounting/periods/${year}/year-end-close`));};
 return <div className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-emerald-700">Finance & Accounting</p><h1 className="text-3xl font-bold text-slate-900">Management Accounting</h1><p className="mt-1 text-slate-600">Operational fixed assets, depreciation, budgets, variance control and financial-period closing.</p></div><Link to="/admin/finance" className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Back to Finance</Link></div>
 {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}{notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{notice}</div>}
 <div className="grid gap-4 md:grid-cols-3"><Metric title="Fixed asset cost" value={money(totals.assets)}/><Metric title={`${year} budgets`} value={money(totals.budget)}/><Metric title={`${year} budget actuals`} value={money(totals.actual)}/></div>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Fixed assets & depreciation</h2><p className="mb-4 text-sm text-slate-500">Asset acquisitions and depreciation post directly to the tenant general ledger.</p>{loading?<p>Loading...</p>:<Table headers={["Asset","Category","Cost","Accumulated depreciation","Status","Actions"]} rows={assets.map(a=>[a.assetNumber+" · "+a.name,a.category||"—",money(a.acquisitionCost),money(a.accumulatedDepreciation),a.status,a.status==="active"?<div className="flex gap-2"><button disabled={!!busy} onClick={()=>depreciate(a)} className="rounded bg-slate-900 px-3 py-1 text-xs font-semibold text-white disabled:opacity-50">{busy===`dep-${a._id}`?"Posting...":"Depreciate"}</button><button disabled={!!busy} onClick={()=>dispose(a)} className="rounded border px-3 py-1 text-xs font-semibold disabled:opacity-50">Dispose</button></div>:"—"])} />}</section>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Budgets</h2><p className="mb-4 text-sm text-slate-500">Only approved budgets feed budget-vs-actual reporting.</p>{loading?<p>Loading...</p>:<Table headers={["Budget","Account","Month","Amount","Status","Actions"]} rows={budgets.map(b=>[b.name,b.accountCode,b.month||"Annual",money(b.amount),b.status,b.status==="draft"?<button disabled={!!busy} onClick={()=>approveBudget(b)} className="rounded bg-emerald-700 px-3 py-1 text-xs font-semibold text-white disabled:opacity-50">{busy===`budget-${b._id}`?"Approving...":"Approve"}</button>:"—"])} />}</section>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Budget vs actual — {year}</h2><p className="mb-4 text-sm text-slate-500">Actuals come from posted tenant journals; no synthetic zeros are inserted.</p>{loading?<p>Loading...</p>:<Table headers={["Account","Budget","Actual","Variance","Utilization"]} rows={variance.map(b=>[b.accountCode,money(b.amount),money(b.actual),money(b.variance),b.utilizationPercent==null?"—":`${b.utilizationPercent}%`])}/>}</section>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Accounting periods</h2><p className="text-sm text-slate-500">Closed periods reject new automatic journal postings. Reopening is an explicit finance action.</p></div><button disabled={!!busy} onClick={closeYear} className="rounded bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy===`year-${year}`?"Closing year...":`Close ${year}`}</button></div>{periods.length?<Table headers={["Period","Status","Closed at","Actions"]} rows={periods.map(p=>[p.period,p.status,p.closedAt?new Date(p.closedAt).toLocaleString("en-KE"):"—",p.status==="closed"?<button disabled={!!busy} onClick={()=>reopenPeriod(p.period)} className="rounded border px-3 py-1 text-xs font-semibold disabled:opacity-50">{busy===`reopen-${p.period}`?"Reopening...":"Reopen"}</button>:<button disabled={!!busy} onClick={()=>closePeriod(p.period)} className="rounded bg-slate-900 px-3 py-1 text-xs font-semibold text-white disabled:opacity-50">{busy===`close-${p.period}`?"Closing...":"Close"}</button>])}/>:<p className="mt-4 text-slate-500">No periods have been closed yet. Open periods accept normal postings.</p>}</section>
 </div></div>;
}
function Metric({title,value}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>}
function Table({headers,rows}){return <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500">{headers.map(h=><th key={h} className="px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-b last:border-0">{r.map((v,j)=><td key={j} className="px-3 py-3 text-slate-800">{v}</td>)}</tr>):<tr><td colSpan={headers.length} className="px-3 py-6 text-center text-slate-500">No records</td></tr>}</tbody></table></div>}
