import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import api from "../../../api/axios";

const money=(n)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:2}).format(Number(n||0));
const year=new Date().getFullYear();

export default function ManagementAccounting(){
 const [assets,setAssets]=useState([]),[budgets,setBudgets]=useState([]),[periods,setPeriods]=useState([]),[variance,setVariance]=useState([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError("");try{const [a,b,p,v]=await Promise.all([api.get("/admin/finance/accounting/assets"),api.get(`/admin/finance/accounting/budgets?fiscalYear=${year}`),api.get("/admin/finance/accounting/periods"),api.get(`/admin/finance/accounting/budgets-vs-actual?fiscalYear=${year}`)]);setAssets(a.data?.data||[]);setBudgets(b.data?.data||[]);setPeriods(p.data?.data||[]);setVariance(v.data?.data?.rows||[]);}catch(e){setError(e?.response?.data?.message||e.message||"Unable to load management accounting.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const totals=useMemo(()=>({assets:assets.reduce((s,a)=>s+Number(a.acquisitionCost||0),0),budget:budgets.reduce((s,b)=>s+Number(b.amount||0),0),actual:variance.reduce((s,b)=>s+Number(b.actual||0),0)}),[assets,budgets,variance]);
 return <div className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-emerald-700">Finance & Accounting</p><h1 className="text-3xl font-bold text-slate-900">Management Accounting</h1><p className="mt-1 text-slate-600">Fixed assets, depreciation, budgets, budget-vs-actual and accounting period control.</p></div><Link to="/admin/finance" className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Back to Finance</Link></div>
 {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
 <div className="grid gap-4 md:grid-cols-3"><Metric title="Fixed asset cost" value={money(totals.assets)}/><Metric title={`${year} approved/draft budget`} value={money(totals.budget)}/><Metric title={`${year} budget actuals`} value={money(totals.actual)}/></div>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Fixed assets</h2><p className="mb-4 text-sm text-slate-500">Maintain the asset register and post straight-line depreciation without changing historical journals.</p>{loading?<p>Loading...</p>:<Table headers={["Asset","Category","Cost","Accumulated depreciation","Status"]} rows={assets.map(a=>[a.assetNumber+" · "+a.name,a.category,money(a.acquisitionCost),money(a.accumulatedDepreciation),a.status])}/>}</section>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Budget vs actual — {year}</h2><p className="mb-4 text-sm text-slate-500">Approved budgets are compared against posted tenant journals by account and month.</p>{loading?<p>Loading...</p>:<Table headers={["Account","Budget","Actual","Variance","Utilization"]} rows={variance.map(b=>[b.accountCode,money(b.amount),money(b.actual),money(b.variance),b.utilizationPercent==null?"—":`${b.utilizationPercent}%`])}/>}</section>
 <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Accounting periods</h2><p className="mb-4 text-sm text-slate-500">Closed periods reject new automatic postings; corrections must be made in an open period.</p>{periods.length?<Table headers={["Period","Status","Closed at"]} rows={periods.map(p=>[p.period,p.status,p.closedAt?new Date(p.closedAt).toLocaleString("en-KE"):"—"])}/>:<p className="text-slate-500">No periods have been closed yet. This is normal for a new tenant.</p>}</section>
 </div></div>;
}
function Metric({title,value}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>}
function Table({headers,rows}){return <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500">{headers.map(h=><th key={h} className="px-3 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i} className="border-b last:border-0">{r.map((v,j)=><td key={j} className="px-3 py-3 text-slate-800">{v}</td>)}</tr>):<tr><td colSpan={headers.length} className="px-3 py-6 text-center text-slate-500">No records</td></tr>}</tbody></table></div>}
