import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ExternalLink, Eye, RefreshCw, ShieldAlert, X } from "lucide-react";
import api from "../../../api/axios";

const money = (n) => `KES ${Number(n || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const display = (value, fallback = "Not provided") => value === null || value === undefined || value === "" ? fallback : String(value);

export default function WithholdingTax() {
  const qc = useQueryClient();
  const [selected, setSelected] = useState(null);
  const [remitRef, setRemitRef] = useState({});
  const [form, setForm] = useState({ payeeName: "", payeePin: "", reference: "", period: new Date().toISOString().slice(0, 7), baseAmount: "", rate: "", sourceType: "supplier_payment" });
  const q = useQuery({ queryKey: ["wht"], queryFn: async () => (await api.get("/admin/finance/withholding-tax")).data });
  const create = useMutation({ mutationFn: () => api.post("/admin/finance/withholding-tax", { ...form, taxPeriod: form.period, baseAmount: Number(form.baseAmount), rate: Number(form.rate) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["wht"] }); setForm({ ...form, payeeName: "", payeePin: "", reference: "", baseAmount: "", rate: "" }); } });
  const remit = useMutation({ mutationFn: ({ id, reference }) => api.post(`/admin/finance/withholding-tax/${id}/remit`, { paymentReference: reference }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["wht"] }); setRemitRef({}); } });
  const rows = q.data?.data || [];
  const totals = q.data?.totals || {};
  const selectedPayments = useMemo(() => selected?.sourceType === "supplier_payment" ? selected?.sourceId : null, [selected]);

  return <div className="min-h-full space-y-6 bg-slate-50 p-4 md:p-6">
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Tax control</p><h1 className="text-3xl font-bold text-slate-900">Withholding Tax</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Tenant-scoped accrual, payable, certificate and remittance tracking. Enter the actual payment/remittance reference; the application never invents statutory references.</p></div><button type="button" onClick={() => q.refetch()} disabled={q.isFetching} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">{q.isFetching ? <RefreshCw className="animate-spin" size={16} /> : <RefreshCw size={16} />} Refresh</button></div>
    </div>
    {q.isError && <div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ShieldAlert size={20} /><span>{q.error?.response?.data?.message || "Unable to load withholding-tax records."}</span></div>}
    <div className="grid gap-4 md:grid-cols-3"><Metric title="Records" value={rows.length}/><Metric title="Tax accrued" value={money(totals.accrued || 0)}/><Metric title="Tax remitted" value={money(totals.remitted || 0)}/></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-semibold text-slate-900">Record withholding tax</h2><div className="grid gap-3 md:grid-cols-3">{[["payeeName","Payee name"],["payeePin","Payee PIN"],["reference","Reference"],["period","Period YYYY-MM"],["baseAmount","Taxable base"],["rate","Rate %"]].map(([k,l])=><label key={k} className="text-xs font-medium text-slate-600">{l}<input type={k === "baseAmount" || k === "rate" ? "number" : k === "period" ? "month" : "text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm text-slate-900 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"/></label>)}</div><button onClick={()=>create.mutate()} disabled={create.isPending || !form.rate || !form.baseAmount || !form.payeeName || !form.reference} className="mt-4 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-50">{create.isPending ? "Recording…" : "Record WHT"}</button></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-xl font-semibold text-slate-900">WHT register</h2><p className="mt-1 text-sm text-slate-500">Open any record to inspect the actual stored tax and remittance data.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{["Payee","Period","Base","Rate","Tax","Status","Action"].map(h=><th key={h} className="whitespace-nowrap p-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-600">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map(x=><tr key={x._id} className="border-t border-slate-100 hover:bg-slate-50/70"><td className="p-3 font-medium text-slate-900">{display(x.payeeName)}<div className="text-xs font-normal text-slate-500">{display(x.payeePin, "No PIN")}</div></td><td className="p-3 text-slate-700">{display(x.taxPeriod || x.period)}</td><td className="p-3 text-slate-700">{money(x.baseAmount)}</td><td className="p-3 text-slate-700">{x.rate}%</td><td className="p-3 font-semibold text-slate-900">{money(x.taxAmount)}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${x.status === "remitted" ? "bg-emerald-100 text-emerald-800" : x.status === "cancelled" ? "bg-slate-100 text-slate-600" : "bg-amber-100 text-amber-800"}`}>{display(x.status)}</span></td><td className="p-3"><div className="flex min-w-[330px] flex-wrap items-center gap-2"><button type="button" onClick={()=>setSelected(x)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"><Eye size={14}/> View source</button>{x.status !== "remitted" && x.status !== "cancelled" && <><input placeholder="Actual remittance reference" value={remitRef[x._id] || ""} onChange={e=>setRemitRef({...remitRef,[x._id]:e.target.value})} className="rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs"/><button disabled={!remitRef[x._id] || remit.isPending} onClick={()=>remit.mutate({id:x._id,reference:remitRef[x._id]})} className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-800 disabled:opacity-50">Mark remitted</button></>}</div></td></tr>) : <tr><td colSpan="7" className="p-10 text-center text-slate-500">No withholding-tax records yet.</td></tr>}</tbody></table></div></section>
    {selected && <SourceDrawer record={selected} sourcePayments={selectedPayments} onClose={()=>setSelected(null)} />}
  </div>;
}

function SourceDrawer({ record, sourcePayments, onClose }) {
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" role="dialog" aria-modal="true" aria-label="Withholding tax source details" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 pb-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Tax control · Source data</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{display(record.reference)}</h2><p className="text-sm text-slate-500">Read-only inspection of the stored withholding-tax record.</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Close"><X size={20}/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Detail label="Record ID" value={record._id}/><Detail label="Tenant ID" value={record.tenantId}/><Detail label="Payee" value={record.payeeName}/><Detail label="Payee PIN" value={record.payeePin}/><Detail label="Period" value={record.taxPeriod || record.period}/><Detail label="Reference" value={record.reference}/><Detail label="Source type" value={record.sourceType}/><Detail label="Source ID" value={sourcePayments || record.sourceId}/><Detail label="Taxable base" value={money(record.baseAmount)}/><Detail label="Rate" value={`${record.rate}%`}/><Detail label="Tax amount" value={money(record.taxAmount)}/><Detail label="Status" value={record.status}/><Detail label="Payment reference" value={record.paymentReference}/><Detail label="Certificate number" value={record.certificateNumber}/><Detail label="Remitted at" value={record.remittedAt ? new Date(record.remittedAt).toLocaleString() : "Not remitted"}/><Detail label="Created" value={record.createdAt ? new Date(record.createdAt).toLocaleString() : "Not available"}/></div><div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Audit note:</strong> This view displays the values returned by the tenant-scoped WHT API. It does not invent a KRA/payment/certificate reference and does not modify the record.</div><div className="mt-5"><a href={record.sourceId ? `/admin/finance/transactions?sourceId=${encodeURIComponent(record.sourceId)}` : "/admin/finance/transactions"} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Open related finance transactions <ExternalLink size={15}/></a></div></aside></div>;
}
function Detail({label,value}) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 break-all text-sm font-medium text-slate-900">{display(value)}</p></div>; }
function Metric({title,value}) { return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></div>; }
