import Payment from "../models/Payment.js";
import HotelBooking from "../models/HotelBooking.js";
import AirportTransferBooking from "../models/AirportTransferBooking.js";
import Notification from "../models/Notification.js";

const MODELS = { hotel: HotelBooking, airport_transfer: AirportTransferBooking };
export const getHospitalityModel = (type) => MODELS[String(type || "").trim().toLowerCase()] || null;
export const getHospitalityPayableAmount = (booking) => { const total = Number(booking?.totalAmount || 0); if (!Number.isFinite(total) || total <= 0) throw new Error("Booking has an invalid total amount."); return Math.max(0, Math.round(total)); };
export const syncHospitalityPaymentStatus = async ({ type, booking, payment }) => { const payments = await Payment.find({ tenantId: booking.tenantId, hospitalityBooking: booking._id, hospitalityType: type, status: { $in: ["completed", "refunded"] } }).select("amount refundedAmount").lean(); const paid = payments.reduce((sum, item) => sum + Math.max(0, Number(item.amount || 0) - Number(item.refundedAmount || 0)), 0); const total = Number(booking.totalAmount || 0); booking.paymentStatus = paid >= total && total > 0 ? "paid" : paid > 0 ? "partial" : payment?.status === "failed" ? "failed" : "pending"; if (booking.paymentStatus === "paid" && booking.status === "pending") booking.status = "confirmed"; await booking.save(); return { booking, paidAmount: paid, balance: Math.max(0, total - paid) }; };
export const completeHospitalityPayment = async ({ payment, booking, paymentData = {} }) => { if (!payment || !booking) throw new Error("Payment and hospitality booking are required."); if (payment.status === "completed") return { payment, ...(await syncHospitalityPaymentStatus({ type: payment.hospitalityType, booking, payment })) }; const amount = Number(paymentData.amount ?? payment.amount ?? 0); if (!Number.isFinite(amount) || amount <= 0) throw new Error("Completed payment has an invalid amount."); const total = Number(booking.totalAmount || 0); const prior = await Payment.aggregate([{ $match: { tenantId: booking.tenantId, hospitalityBooking: booking._id, hospitalityType: payment.hospitalityType, status: { $in: ["completed", "refunded"] }, _id: { $ne: payment._id } } }, { $project: { net: { $max: [0, { $subtract: ["$amount", { $ifNull: ["$refundedAmount", 0] }] }] } } }, { $group: { _id: null, total: { $sum: "$net" } } }]); const remaining = Math.max(0, total - Number(prior[0]?.total || 0)); if (amount > remaining) throw new Error(`Payment amount ${amount} exceeds remaining balance ${remaining}.`); payment.status = "completed"; payment.amount = amount; payment.paidAt = payment.paidAt || new Date(); if (paymentData.paymentMethod) payment.paymentMethod = paymentData.paymentMethod; if (paymentData.phoneNumber) payment.phoneNumber = String(paymentData.phoneNumber).trim(); if (paymentData.mpesaReceiptNumber) { payment.mpesaReceiptNumber = String(paymentData.mpesaReceiptNumber).trim(); payment.transactionId = payment.mpesaReceiptNumber; payment.transactionReference = payment.mpesaReceiptNumber; } if (paymentData.checkoutRequestID) payment.checkoutRequestID = paymentData.checkoutRequestID; if (paymentData.merchantRequestID) payment.merchantRequestID = paymentData.merchantRequestID; if (paymentData.transactionDate) payment.transactionDate = paymentData.transactionDate; if (paymentData.callbackResponse) payment.callbackResponse = paymentData.callbackResponse; await payment.save(); const result = await syncHospitalityPaymentStatus({ type: payment.hospitalityType, booking, payment }); if (booking.user) { const label = payment.hospitalityType === "hotel" ? "Hotel reservation" : "Airport transfer"; await Notification.create({ tenantId: booking.tenantId, recipient: booking.user, user: booking.user, title: `${label} payment received`, message: `${label} ${booking.reference} received KES ${amount.toLocaleString()} via ${payment.paymentMethod || payment.provider}.`, type: "booking" }); } return { payment, ...result }; };
export const failHospitalityPayment = async ({ payment, booking, reason = "Payment failed.", paymentData = {} }) => { if (!payment) throw new Error("Payment is required."); if (payment.status === "completed") return { payment, booking }; payment.status = "failed"; payment.failureReason = String(reason).slice(0, 500); payment.failedAt = new Date(); if (paymentData.checkoutRequestID) payment.checkoutRequestID = paymentData.checkoutRequestID; if (paymentData.callbackResponse) payment.callbackResponse = paymentData.callbackResponse; await payment.save(); if (booking) { booking.paymentStatus = "failed"; await booking.save(); } return { payment, booking }; };
export const assertHospitalityPaymentAccess = (booking, user) => { if (!booking || !user?._id) return false; const role = String(user.role || user.legacyRole || "").toLowerCase(); const staff = ["admin", "super_admin", "superadmin", "manager", "tour_manager", "tourmanager", "agent"].includes(role); return staff || String(booking.user || "") === String(user._id) || String(booking.customer || "") === String(user._id); };
