import { useSettings } from "../../context/SettingsContext";
import { Link } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { useTenant } from "../../context/TenantContext";
import { FaFacebookF, FaInstagram, FaXTwitter, FaYoutube, FaPhone, FaLocationDot, FaEnvelope } from "react-icons/fa6";

export default function Footer() {
  const { user } = useAuth();
  const { settings = {} } = useSettings() || {};
  const { tenant = {} } = useTenant() || {};

  const companyName = settings.companyName || tenant.name || tenant.companyName || (user ? "Your Travel Company" : "");
  const supportEmail = settings.supportEmail || tenant.contactEmail || "";
  const supportPhone = settings.supportPhone || tenant.contactPhone || "";
  const year = new Date().getFullYear();

  const userRole = typeof user?.role === "string" ? user.role.toLowerCase() : user?.role?.name?.toLowerCase() || user?.roles?.[0]?.name?.toLowerCase() || "";
  const socialLinks = [["Facebook", settings.facebook, FaFacebookF], ["Instagram", settings.instagram, FaInstagram], ["X", settings.twitter, FaXTwitter], ["YouTube", settings.youtube, FaYoutube]].filter(([, href]) => href);
  const popularDestinations = [["Tsavo National Park", "/destinations/tsavo-national-park"], ["Lake Naivasha", "/destinations/lake-naivasha"], ["Watamu", "/destinations/watamu"], ["Mount Kenya", "/destinations/mount-kenya"], ["Samburu National Reserve", "/destinations/samburu-national-reserve"]];

  return (
    <footer className="bg-gray-900 text-gray-300">
      <div className="max-w-7xl mx-auto px-6 py-16 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-10">
        <div><h2 className="text-2xl font-bold text-white">{companyName}</h2><p className="mt-4 text-gray-400 leading-relaxed">Discover Kenya and East Africa through unforgettable safaris, wildlife adventures, luxury holidays, beach escapes, mountain expeditions, and tailor-made travel experiences.</p><div className="mt-6 space-y-3 text-sm">{supportPhone && <a href={`tel:${String(supportPhone).replace(/\s+/g, "")}`} className="flex items-center gap-2 hover:text-green-400 transition"><FaPhone /> {supportPhone}</a>}{supportEmail && <a href={`mailto:${supportEmail}`} className="flex items-center gap-2 hover:text-green-400 transition"><FaEnvelope /> {supportEmail}</a>}<div className="flex items-center gap-2"><FaLocationDot /> {settings.city || tenant.city || "Nairobi"}, {settings.country || tenant.country || "Kenya"}</div></div>{socialLinks.length > 0 && <div className="flex gap-4 mt-6">{socialLinks.map(([label, href, Icon]) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} className="hover:text-green-400 transition"><Icon size={20} /></a>)}</div>}</div>
        <div><h3 className="text-lg font-semibold text-white mb-4">Explore</h3><ul className="space-y-3"><li><Link to="/" className="hover:text-green-400 transition">Home</Link></li><li><Link to="/destinations" className="hover:text-green-400 transition">Destinations</Link></li><li><Link to="/tours" className="hover:text-green-400 transition">Tours</Link></li><li><Link to="/about" className="hover:text-green-400 transition">About Us</Link></li><li><Link to="/contact" className="hover:text-green-400 transition">Contact</Link></li>{!user && <><li><Link to="/login" className="hover:text-green-400 transition">Login</Link></li><li><Link to="/register" className="hover:text-green-400 transition">Register</Link></li></>}{user && <><li><Link to="/dashboard" className="hover:text-green-400 transition">Dashboard</Link></li><li><Link to="/profile" className="hover:text-green-400 transition">Profile</Link></li><li><Link to="/wishlist" className="hover:text-green-400 transition">Wishlist</Link></li></>}</ul></div>
        <div><h3 className="text-lg font-semibold text-white mb-4">Popular Destinations</h3><ul className="space-y-3">{popularDestinations.map(([name, path]) => <li key={path}><Link to={path} className="hover:text-green-400 transition">{name}</Link></li>)}</ul></div>
        <div><h3 className="text-lg font-semibold text-white mb-4">Travel Services</h3><ul className="space-y-3"><li><Link to="/tours?category=luxury" className="hover:text-green-400 transition">Luxury Safaris</Link></li><li><Link to="/tours?category=wildlife" className="hover:text-green-400 transition">Wildlife Tours</Link></li><li><Link to="/tours?category=beach" className="hover:text-green-400 transition">Beach Holidays</Link></li><li><Link to="/tours?category=group" className="hover:text-green-400 transition">Group Adventures</Link></li><li><Link to="/tours?category=honeymoon" className="hover:text-green-400 transition">Honeymoon Packages</Link></li><li><Link to="/airport-transfers" className="hover:text-green-400 transition">Airport Transfers</Link></li></ul>{userRole === "admin" && !["super_admin", "superadmin"].includes(user?.role) && <div className="mt-8"><h4 className="text-white font-semibold mb-3">Admin Panel</h4><ul className="space-y-2 text-sm"><li><Link to="/admin" className="hover:text-green-400">Dashboard</Link></li><li><Link to="/admin/manage-tours" className="hover:text-green-400">Manage Tours</Link></li><li><Link to="/admin/tours/add" className="hover:text-green-400">Add Tour</Link></li><li><Link to="/admin/analytics" className="hover:text-green-400">Analytics</Link></li><li><Link to="/admin/customers" className="hover:text-green-400">Customers</Link></li></ul></div>}{userRole === "agent" && <div className="mt-8"><h4 className="text-white font-semibold mb-3">Agent Portal</h4><Link to="/agent" className="hover:text-green-400 transition">Agent Dashboard</Link></div>}</div>
      </div>
      <div className="border-t border-gray-800"><div className="max-w-7xl mx-auto px-6 py-6 flex flex-col lg:flex-row justify-between items-center gap-4"><p className="text-sm text-gray-500 text-center lg:text-left">© {year} {companyName}. All Rights Reserved.</p><div className="flex flex-wrap justify-center gap-6 text-sm"><Link to="/privacy" className="hover:text-green-400 transition">Privacy Policy</Link><Link to="/terms" className="hover:text-green-400 transition">Terms & Conditions</Link><Link to="/refund-policy" className="hover:text-green-400 transition">Refund Policy</Link></div><p className="text-sm text-gray-500 text-center lg:text-right">{companyName} creates unforgettable African travel experiences.</p></div></div>
    </footer>
  );
}
