import "dotenv/config";
import mongoose from "mongoose";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SEEDED_MODELS } from "../seeds/completeTestDemoSeed.js";

const generatedName = /^hr_[0-9]+_[0-9]+_[a-f0-9]{8}$/;
const reportPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../reports/readiness-database-cleanup.json");
const redact = (error) => String(error?.message || "cleanup failed").replace(/mongodb(?:\+srv)?:\/\/[^\s"']+/gi, "[MongoDB URI redacted]");
let activeClient;

function assertTargets() {
  const appUri = process.env.MONGODB_URI;
  const testUri = process.env.HEALTH_TEST_MONGODB_URI;
  if (!appUri || !testUri) throw new Error("MONGODB_URI and HEALTH_TEST_MONGODB_URI must be loaded from the application environment.");
  const app = new URL(appUri);
  const test = new URL(testUri);
  const appDatabase = decodeURIComponent(app.pathname.replace(/^\//, "").split("/")[0] || "");
  const testDatabase = decodeURIComponent(test.pathname.replace(/^\//, "").split("/")[0] || "");
  if (appDatabase !== "husseindb" || testDatabase !== "global_tours_test" || app.hostname !== test.hostname) throw new Error("Readiness cleanup requires the configured application Atlas cluster, husseindb, and its global_tours_test source database.");
  if (!app.hostname.endsWith(".mongodb.net")) throw new Error("Readiness cleanup refuses a non-Atlas host.");
  return { appDatabase, testDatabase };
}

async function clusterCollectionCount(client, databases) {
  const counts = await Promise.all(databases.map(async ({ name }) => client.db(name).listCollections({}, { nameOnly: true }).toArray().then((items) => items.length)));
  return counts.reduce((sum, count) => sum + count, 0);
}

async function main() {
  const { appDatabase, testDatabase } = assertTargets();
  await import("../app.js");
  activeClient = new mongoose.mongo.MongoClient(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 });
  await activeClient.connect();
  const client = activeClient;
  const beforeDatabases = (await client.db("admin").admin().listDatabases({ nameOnly: true })).databases || [];
  const beforeCount = await clusterCollectionCount(client, beforeDatabases);
  const knownCollections = new Set([...SEEDED_MODELS, ...Object.values(mongoose.models)].map((model) => model.collection.collectionName));
  const candidates = beforeDatabases.map(({ name }) => name).filter((name) => generatedName.test(name));
  const validated = [];

  for (const name of candidates) {
    console.log(`Readiness cleanup inspection: ${name}`);
    if (name === appDatabase || name === testDatabase || /prod|production|stage|staging/i.test(name)) throw new Error(`Refusing a protected readiness database name: ${name}`);
    if (!generatedName.test(name)) throw new Error(`Refusing an unexpected database name: ${name}`);
    const collections = await client.db(name).listCollections({}, { nameOnly: true }).toArray();
    const collectionResults = [];
    for (const { name: collectionName } of collections) {
      if (!knownCollections.has(collectionName)) throw new Error(`Readiness database ${name} contains unrecognized collection ${collectionName}; refusing cleanup.`);
      const count = await client.db(name).collection(collectionName).countDocuments({});
      collectionResults.push({ name: collectionName, documents: count });
      if (count !== 0) throw new Error(`Readiness database ${name} contains documents; refusing cleanup because contents are not proven disposable.`);
    }
    validated.push({ name, collectionCount: collections.length, collections: collectionResults, classification: "EMPTY TEST database generated by healthReadiness.test.js" });
  }

  for (const item of validated) {
    if (!generatedName.test(item.name) || item.name === appDatabase || item.name === testDatabase) throw new Error(`Readiness database changed validation state: ${item.name}`);
    console.log(`Removing confirmed empty readiness-test collections from: ${item.name} (${item.collectionCount} app-schema collections)`);
    for (const collection of item.collections) {
      if (collection.documents !== 0 || !knownCollections.has(collection.name)) throw new Error(`Readiness collection changed validation state: ${item.name}.${collection.name}`);
      await client.db(item.name).collection(collection.name).drop();
    }
  }

  const afterDatabases = (await client.db("admin").admin().listDatabases({ nameOnly: true })).databases || [];
  const afterCount = await clusterCollectionCount(client, afterDatabases);
  const remaining = afterDatabases.map(({ name }) => name).filter((name) => generatedName.test(name));
  if (remaining.length) throw new Error(`Readiness-test databases remain after cleanup: ${remaining.length}`);
  const report = { timestamp: new Date().toISOString(), applicationDatabase: appDatabase, testSourceDatabase: testDatabase, clusterCollectionsBefore: beforeCount, clusterCollectionsAfter: afterCount, atlasLimit: 500, removedDatabaseCount: validated.length, removedCollectionCount: validated.reduce((sum, item) => sum + item.collectionCount, 0), removedDatabases: validated };
  await fs.mkdir(path.dirname(reportPath), { recursive: true });
  await fs.writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, { mode: 0o600 });
  console.log(JSON.stringify({ clusterCollectionsBefore: beforeCount, clusterCollectionsAfter: afterCount, removedDatabaseCount: validated.length, removedCollectionCount: report.removedCollectionCount, report: "reports/readiness-database-cleanup.json" }, null, 2));
  await activeClient.close();
  activeClient = null;
}

main().catch((error) => {
  console.error(`Confirmed readiness cleanup failed: ${redact(error)}`);
  process.exitCode = 1;
}).finally(async () => {
  await activeClient?.close();
});
