import TaxProfile from "../models/TaxProfile.js";
import EtimsCredential, { encryptEtimsSecret } from "../models/EtimsCredential.js";
import Expense from "../models/Expense.js";
import CreditDebitNote from "../models/CreditDebitNote.js";
import Invoice from "../models/Invoice.js";
import EtimsSubmission from "../models/EtimsSubmission.js";
import { enqueueNoteForEtims } from "../services/etimsNoteService.js";
import { mergeTenantFilter, requireTenantId } from "../tenancy/context.js";

export const getTaxProfile = async (req, res, next) => { try { requireTenantId(); let profile = await TaxProfile.findOne(mergeTenantFilter(req, {})).lean(); if (!profile) profile = { kraPin: "", vatRegistered: false, defaultVatRate: 16, taxRegime: "VAT", etimsEnabled: false, etimsSolution: "", etimsEnvironment: "sandbox", etimsDeviceId: "", etimsBranchId: "", etimsBranchName: "Head Office", etimsTillId: "", etimsInvoicePrefix: "INV", etimsCredentialRef: "" }; return res.json({ success: true, data: profile }); } catch (error) { next(error); } };

export const upsertTaxProfile = async (req, res, next) => { try { const tenantId = requireTenantId(); const allowed = ["kraPin", "vatRegistered", "vatNumber", "defaultVatRate", "taxRegime", "etimsEnabled", "etimsSolution", "etimsEnvironment", "etimsDeviceId", "etimsBranchId", "etimsBranchName", "etimsTillId", "etimsInvoicePrefix", "etimsCredentialRef", "etimsAdapterUrl", "complianceNotes"]; const data = {}; for (const key of allowed) if (req.body?.[key] !== undefined) data[key] = req.body[key]; if (data.kraPin && !/^P\d{9}[A-Z]$/i.test(String(data.kraPin).trim())) return res.status(400).json({ success: false, message: "Invalid Kenyan KRA PIN format." }); if (data.defaultVatRate !== undefined && (!Number.isFinite(Number(data.defaultVatRate)) || Number(data.defaultVatRate) < 0 || Number(data.defaultVatRate) > 100)) return res.status(400).json({ success: false, message: "Invalid VAT rate." }); if (data.etimsEnvironment && !["sandbox", "production"].includes(data.etimsEnvironment)) return res.status(400).json({ success: false, message: "Invalid eTIMS environment." }); if (data.etimsEnabled && !data.kraPin) { const existing = await TaxProfile.findOne({ tenantId }).lean(); if (!existing?.kraPin) return res.status(400).json({ success: false, message: "A KRA PIN is required before eTIMS can be enabled." }); } if (data.etimsEnabled && data.etimsEnvironment === "production" && data.etimsSolution === "") return res.status(400).json({ success: false, message: "Select the tenant's certified eTIMS solution before enabling production submission." }); if (data.etimsAdapterUrl) { const parsed = new URL(String(data.etimsAdapterUrl)); if (!["http:", "https:"].includes(parsed.protocol) || (process.env.NODE_ENV === "production" && parsed.protocol !== "https:")) return res.status(400).json({ success: false, message: "eTIMS adapter URL must use HTTPS in production." }); } data.updatedBy = req.user?._id || null; const profile = await TaxProfile.findOneAndUpdate({ tenantId }, { $set: data, $setOnInsert: { tenantId } }, { upsert: true, new: true, runValidators: true }); return res.json({ success: true, data: profile }); } catch (error) { next(error); } };

export const getEtimsCredentialStatus = async (req, res, next) => { try { const tenantId = requireTenantId(); const environment = String(req.query.environment || "sandbox"); const credential = await EtimsCredential.findOne({ tenantId, environment }).lean(); return res.json({ success: true, data: credential ? { environment: credential.environment, credentialRef: credential.credentialRef, certificateRef: credential.certificateRef, configured: Boolean(credential.adapterTokenEncrypted || credential.clientIdEncrypted || credential.clientSecretEncrypted), updatedAt: credential.updatedAt } : { environment, configured: false } }); } catch (error) { next(error); } };

export const saveEtimsCredentials = async (req, res, next) => { try { const tenantId = requireTenantId(); const environment = String(req.body?.environment || "sandbox"); if (!["sandbox", "production"].includes(environment)) return res.status(400).json({ success: false, message: "Invalid eTIMS environment." }); const data = { tenantId, environment, credentialRef: String(req.body?.credentialRef || "").trim(), certificateRef: String(req.body?.certificateRef || "").trim(), updatedBy: req.user?._id || null }; if (req.body?.adapterToken) data.adapterTokenEncrypted = encryptEtimsSecret(req.body.adapterToken); if (req.body?.clientId) data.clientIdEncrypted = encryptEtimsSecret(req.body.clientId); if (req.body?.clientSecret) data.clientSecretEncrypted = encryptEtimsSecret(req.body.clientSecret); const credential = await EtimsCredential.findOneAndUpdate({ tenantId, environment }, { $set: data }, { upsert: true, new: true, runValidators: true }).lean(); return res.json({ success: true, data: { environment: credential.environment, credentialRef: credential.credentialRef, certificateRef: credential.certificateRef, configured: true, updatedAt: credential.updatedAt } }); } catch (error) { next(error); } };

export const listExpenses = async (req, res, next) => { try { const page = Math.max(Number(req.query.page) || 1, 1); const limit = Math.min(Math.max(Number(req.query.limit) || 25, 1), 100); const filter = {}; if (req.query.status) filter.status = req.query.status; if (req.query.category) filter.category = req.query.category; if (req.query.startDate || req.query.endDate) { filter.expenseDate = {}; if (req.query.startDate) filter.expenseDate.$gte = new Date(req.query.startDate); if (req.query.endDate) filter.expenseDate.$lte = new Date(req.query.endDate); } const tenantFilter = mergeTenantFilter(req, filter); const [data, total] = await Promise.all([Expense.find(tenantFilter).sort({ expenseDate: -1 }).skip((page - 1) * limit).limit(limit).lean(), Expense.countDocuments(tenantFilter)]); return res.json({ success: true, data, pagination: { total, page, limit, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } };
export const createExpense = async (req, res, next) => { try { const tenantId = requireTenantId(); const amount = Number(req.body?.amount); if (!req.body?.category || !req.body?.description || !Number.isFinite(amount) || amount <= 0) return res.status(400).json({ success: false, message: "Category, description and a positive amount are required." }); const expense = await Expense.create({ ...req.body, tenantId, amount, createdBy: req.user?._id || null }); return res.status(201).json({ success: true, data: expense }); } catch (error) { next(error); } };
export const listNotes = async (req, res, next) => { try { const data = await CreditDebitNote.find(mergeTenantFilter(req, {})).populate("originalInvoice", "invoiceNumber etimsInvoiceNumber totalAmount issueDate").sort({ createdAt: -1 }).limit(200).lean(); return res.json({ success: true, data }); } catch (error) { next(error); } };
export const createNote = async (req, res, next) => { try { const tenantId = requireTenantId(); const type = String(req.body?.type || "").toLowerCase(); if (!["credit", "debit"].includes(type)) return res.status(400).json({ success: false, message: "Note type must be credit or debit." }); const invoice = await Invoice.findOne(mergeTenantFilter(req, { _id: req.body?.originalInvoice, isDeleted: { $ne: true } })); if (!invoice) return res.status(404).json({ success: false, message: "Original invoice not found." }); if (invoice.etimsStatus !== "synced" || !invoice.etimsInvoiceNumber) return res.status(400).json({ success: false, message: "The original invoice must have a successful eTIMS submission before a tax note can be issued." }); if (type === "credit" && new Date(invoice.issueDate).getTime() < Date.now() - 183 * 86400000) return res.status(400).json({ success: false, message: "A credit note cannot be created more than six months after the original tax invoice." }); const totalAmount = Number(req.body?.totalAmount); const taxAmount = Number(req.body?.taxAmount || 0); const amount = Number(req.body?.amount || Math.max(0, totalAmount - taxAmount)); if (!Number.isFinite(totalAmount) || totalAmount <= 0 || totalAmount > Number(invoice.totalAmount)) return res.status(400).json({ success: false, message: "Note amount must be positive and cannot exceed the original invoice total." }); if (!Number.isFinite(taxAmount) || taxAmount < 0 || taxAmount > totalAmount) return res.status(400).json({ success: false, message: "Invalid note tax amount." }); const profile = await TaxProfile.findOne({ tenantId }).lean(); const note = await CreditDebitNote.create({ tenantId, type, originalInvoice: invoice._id, originalInvoiceNumber: invoice.invoiceNumber, originalEtimsInvoiceNumber: invoice.etimsInvoiceNumber, etimsSolution: profile?.etimsSolution || "", reason: req.body?.reason, amount, taxAmount, totalAmount, taxRate: Number(invoice.taxRate || 0), status: "issued", createdBy: req.user?._id || null }); const job = await enqueueNoteForEtims(note._id, tenantId); return res.status(201).json({ success: true, data: note, jobId: job._id }); } catch (error) { next(error); } };
export const queueNoteEtims = async (req, res, next) => { try { const tenantId = requireTenantId(); const note = await CreditDebitNote.findOne(mergeTenantFilter(req, { _id: req.params.id })).lean(); if (!note) return res.status(404).json({ success: false, message: "Credit/debit note not found." }); const job = await enqueueNoteForEtims(note._id, tenantId); return res.status(202).json({ success: true, data: { note, jobId: job._id, jobStatus: job.status } }); } catch (error) { next(error); } };
export const listEtimsSubmissions = async (req, res, next) => { try { const filter = {}; if (req.query.documentType) filter.documentType = req.query.documentType; if (req.query.status) filter.status = req.query.status; if (req.query.documentId) filter.documentId = req.query.documentId; const data = await EtimsSubmission.find(mergeTenantFilter(req, filter)).sort({ createdAt: -1 }).limit(Math.min(Number(req.query.limit) || 100, 250)).lean(); return res.json({ success: true, data }); } catch (error) { next(error); } };
export const getFinanceComplianceSummary = async (req, res, next) => { try { const [profile, expenses, etims] = await Promise.all([TaxProfile.findOne(mergeTenantFilter(req, {})).lean(), Expense.aggregate([{ $match: mergeTenantFilter(req, {}) }, { $group: { _id: null, total: { $sum: "$amount" }, tax: { $sum: "$taxAmount" }, count: { $sum: 1 } } }]), EtimsSubmission.aggregate([{ $match: mergeTenantFilter(req, {}) }, { $group: { _id: "$status", count: { $sum: 1 } } }])]); const etimsCounts = Object.fromEntries(etims.map((item) => [item._id, item.count])); return res.json({ success: true, data: { taxProfile: profile, expenses: expenses[0] || { total: 0, tax: 0, count: 0 }, etims: etimsCounts, compliance: { etimsConfigured: Boolean(profile?.etimsEnabled && profile?.kraPin && profile?.etimsSolution), kraPinConfigured: Boolean(profile?.kraPin), productionReady: Boolean(profile?.etimsEnabled && profile?.etimsEnvironment === "production" && profile?.kraPin && profile?.etimsSolution && profile?.etimsDeviceId) } } }); } catch (error) { next(error); } };
