import mongoose from "mongoose";
import Hotel from "../models/Hotel.js";
import HotelRoomType from "../models/HotelRoomType.js";
import HotelBooking from "../models/HotelBooking.js";
import AirportTransferBooking from "../models/AirportTransferBooking.js";
import Vehicle from "../models/Vehicle.js";
import User from "../models/User.js";
import Payment from "../models/Payment.js";
import HospitalityRoomBlock from "../models/HospitalityRoomBlock.js";
import HospitalityRatePlan from "../models/HospitalityRatePlan.js";
import HospitalitySupplierContract from "../models/HospitalitySupplierContract.js";
import HospitalityDeposit from "../models/HospitalityDeposit.js";
import { createAuditLog } from "../services/auditService.js";

const tenantIdOf=req=>req.tenantId||req.user?.tenantId;
const clean=v=>String(v??"").trim();
const asDate=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?null:d;};
const staff= req => ["admin","manager","tour_manager","tourmanager","agent"].includes(String(req.user?.role||"").toLowerCase());
const audit=async(req,action,resource,id,metadata={})=>{try{await createAuditLog({user:req.user?._id||null,action,resource,resourceId:id,description:`${action} ${resource}`,method:req.method,endpoint:req.originalUrl,ipAddress:req.ip,userAgent:req.get("user-agent")||"",metadata});}catch{} };

export const hotelCalendar=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),hotelId=req.query.hotelId;const from=asDate(req.query.from)||new Date(),to=asDate(req.query.to)||new Date(Date.now()+30*86400000);if(to<=from)return res.status(400).json({success:false,message:"Invalid calendar range."});const hotel=await Hotel.findOne({_id:hotelId,tenantId}).lean();if(!hotel)return res.status(404).json({success:false,message:"Hotel not found."});const rooms=await HotelRoomType.find({tenantId,hotel:hotelId}).lean();const bookings=await HotelBooking.find({tenantId,hotel:hotelId,status:{$nin:["cancelled","no_show"]},checkIn:{$lt:to},checkOut:{$gt:from}}).populate("roomType","name").lean();const blocks=await HospitalityRoomBlock.find({tenantId,hotel:hotelId,status:"blocked",startDate:{$lt:to},endDate:{$gt:from}}).lean();const days=[];for(let d=new Date(from);d<to;d.setUTCDate(d.getUTCDate()+1)){const day=new Date(d),next=new Date(d);next.setUTCDate(next.getUTCDate()+1);const byRoom=rooms.map(r=>{const sold=bookings.filter(b=>String(b.roomType?._id||b.roomType)===String(r._id)&&new Date(b.checkIn)<next&&new Date(b.checkOut)>day).reduce((s,b)=>s+Number(b.rooms||0),0);const blocked=blocks.filter(b=>String(b.roomType)===String(r._id)&&new Date(b.startDate)<next&&new Date(b.endDate)>day).reduce((s,b)=>s+Number(b.quantity||0),0);return {_id:r._id,name:r.name,totalRooms:r.totalRooms,sold,blocked,available:Math.max(0,Number(r.totalRooms||0)-sold-blocked)};});const total=byRoom.reduce((s,r)=>s+Number(r.totalRooms||0),0),sold=byRoom.reduce((s,r)=>s+r.sold,0),blocked=byRoom.reduce((s,r)=>s+r.blocked,0);days.push({date:day.toISOString().slice(0,10),totalRooms:total,soldRooms:sold,blockedRooms:blocked,availableRooms:Math.max(0,total-sold-blocked),occupancyPercent:total?Number((sold/total*100).toFixed(1)):0,roomTypes:byRoom});}res.json({success:true,data:{hotel,from,to,days}});}catch(e){next(e);}};

export const hotelPerformance=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),hotelId=req.query.hotelId,from=asDate(req.query.from)||new Date(Date.now()-30*86400000),to=asDate(req.query.to)||new Date();const filter={tenantId,checkIn:{$lt:to},checkOut:{$gt:from},status:{$nin:["cancelled","no_show"]}};if(hotelId)filter.hotel=hotelId;const [rooms,bookings]=await Promise.all([HotelRoomType.find({tenantId,...(hotelId?{hotel:hotelId}:{})}).lean(),HotelBooking.find(filter).lean()]);const days=Math.max(1,Math.ceil((to-from)/86400000)),inventory=rooms.reduce((s,r)=>s+Number(r.totalRooms||0),0)*days,roomNights=bookings.reduce((s,b)=>s+Number(b.rooms||0)*Math.max(1,Math.ceil((new Date(b.checkOut)-new Date(b.checkIn))/86400000)),0),revenue=bookings.reduce((s,b)=>s+Number(b.totalAmount||0),0),occupied=Math.min(inventory,roomNights);res.json({success:true,data:{from,to,days,inventoryRoomNights:inventory,occupiedRoomNights:roomNights,occupancyPercent:inventory?Number((occupied/inventory*100).toFixed(1)):0,revenue,currency:"KES",adr:occupied?Number((revenue/occupied).toFixed(2)):0,bookings:bookings.length}});}catch(e){next(e);}};

export const amendHotelBooking=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),b=await HotelBooking.findOne({_id:req.params.id,tenantId});if(!b)return res.status(404).json({success:false,message:"Hotel booking not found."});if(b.status==="cancelled")return res.status(409).json({success:false,message:"Cancelled bookings cannot be amended."});const checkIn=req.body.checkIn?asDate(req.body.checkIn):b.checkIn,checkOut=req.body.checkOut?asDate(req.body.checkOut):b.checkOut,rooms=req.body.rooms===undefined?b.rooms:Number(req.body.rooms);if(!checkIn||!checkOut||checkOut<=checkIn||rooms<1)return res.status(400).json({success:false,message:"Invalid amended stay."});const conflict=await HotelBooking.aggregate([{$match:{tenantId,hotel:b.hotel,roomType:b.roomType,_id:{$ne:b._id},status:{$nin:["cancelled","no_show"]},checkIn:{$lt:checkOut},checkOut:{$gt:checkIn}}},{$group:{_id:null,rooms:{$sum:"$rooms"}}}]);const rt=await HotelRoomType.findOne({_id:b.roomType,tenantId}).lean();if(!rt||Number(conflict[0]?.rooms||0)+rooms>Number(rt.totalRooms||0))return res.status(409).json({success:false,message:"The amended dates/rooms are not available."});const nights=Math.ceil((checkOut-checkIn)/86400000);b.checkIn=checkIn;b.checkOut=checkOut;b.rooms=rooms;b.adults=req.body.adults===undefined?b.adults:Number(req.body.adults);b.children=req.body.children===undefined?b.children:Number(req.body.children);b.mealPlan=req.body.mealPlan||b.mealPlan;b.specialRequests=req.body.specialRequests===undefined?b.specialRequests:clean(req.body.specialRequests);b.subtotal=nights*rooms*Number(rt.nightlyRate||0);b.totalAmount=b.subtotal+Number(b.taxes||0)+Number(b.fees||0);b.updatedBy=req.user?._id||null;await b.save();await audit(req,"amend","HotelBooking",b._id,{checkIn,checkOut,rooms});res.json({success:true,data:b});}catch(e){next(e);}};

export const cancelHotelBooking=async(req,res,next)=>{try{const b=await HotelBooking.findOne({_id:req.params.id,tenantId:tenantIdOf(req)});if(!b)return res.status(404).json({success:false,message:"Hotel booking not found."});if(b.status==="checked_in"||b.status==="checked_out")return res.status(409).json({success:false,message:"This booking can no longer be cancelled."});b.status="cancelled";b.notes=[b.notes,clean(req.body.reason||"Cancelled by operations")].filter(Boolean).join(" | ");b.updatedBy=req.user?._id||null;await b.save();await audit(req,"cancel","HotelBooking",b._id,{reason:req.body.reason||""});res.json({success:true,data:b});}catch(e){next(e);}};

export const blockRooms=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),room=await HotelRoomType.findOne({_id:req.body.roomTypeId,tenantId});if(!room)return res.status(404).json({success:false,message:"Room type not found."});const start=asDate(req.body.startDate),end=asDate(req.body.endDate),quantity=Number(req.body.quantity);if(!start||!end||end<=start||quantity<1)return res.status(400).json({success:false,message:"Valid block dates and quantity are required."});const block=await HospitalityRoomBlock.create({tenantId,hotel:room.hotel,roomType:room._id,startDate:start,endDate:end,quantity,reason:clean(req.body.reason)||"Maintenance",createdBy:req.user?._id||null,updatedBy:req.user?._id||null});await audit(req,"block","HospitalityRoomBlock",block._id,{quantity,startDate:start,endDate:end});res.status(201).json({success:true,data:block});}catch(e){next(e);}};
export const releaseRoomBlock=async(req,res,next)=>{try{const block=await HospitalityRoomBlock.findOne({_id:req.params.id,tenantId:tenantIdOf(req)});if(!block)return res.status(404).json({success:false,message:"Room block not found."});block.status="released";block.updatedBy=req.user?._id||null;await block.save();await audit(req,"release","HospitalityRoomBlock",block._id);res.json({success:true,data:block});}catch(e){next(e);}};

export const ratePlans=async(req,res,next)=>{try{const filter={tenantId:tenantIdOf(req)};if(req.query.hotelId)filter.hotel=req.query.hotelId;if(req.query.roomTypeId)filter.roomType=req.query.roomTypeId;const rows=await HospitalityRatePlan.find(filter).populate("hotel","name").populate("roomType","name").sort({createdAt:-1}).lean();res.json({success:true,data:rows});}catch(e){next(e);}};
export const saveRatePlan=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),payload={...req.body,tenantId,createdBy:req.user?._id||null,updatedBy:req.user?._id||null};let row=req.params.id?await HospitalityRatePlan.findOne({_id:req.params.id,tenantId}):new HospitalityRatePlan(payload);if(!row)return res.status(404).json({success:false,message:"Rate plan not found."});Object.assign(row,payload);await row.save();await audit(req,req.params.id?"update":"create","HospitalityRatePlan",row._id);res.status(req.params.id?200:201).json({success:true,data:row});}catch(e){next(e);}};

export const supplierContracts=async(req,res,next)=>{try{const filter={tenantId:tenantIdOf(req)};if(req.query.status)filter.status=req.query.status;if(req.query.supplierType)filter.supplierType=req.query.supplierType;const rows=await HospitalitySupplierContract.find(filter).populate("hotel","name").sort({validTo:1,createdAt:-1}).lean();res.json({success:true,data:rows});}catch(e){next(e);}};
export const saveSupplierContract=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),payload={...req.body,tenantId,createdBy:req.user?._id||null,updatedBy:req.user?._id||null};let row=req.params.id?await HospitalitySupplierContract.findOne({_id:req.params.id,tenantId}):new HospitalitySupplierContract(payload);if(!row)return res.status(404).json({success:false,message:"Supplier contract not found."});Object.assign(row,payload);await row.save();await audit(req,req.params.id?"update":"create","HospitalitySupplierContract",row._id);res.status(req.params.id?200:201).json({success:true,data:row});}catch(e){next(e);}};

export const deposits=async(req,res,next)=>{try{const filter={tenantId:tenantIdOf(req)};if(req.query.status)filter.status=req.query.status;const rows=await HospitalityDeposit.find(filter).sort({dueDate:1,createdAt:-1}).lean();res.json({success:true,data:rows});}catch(e){next(e);}};
export const saveDeposit=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),payload={...req.body,tenantId,createdBy:req.user?._id||null,updatedBy:req.user?._id||null};let row=req.params.id?await HospitalityDeposit.findOne({_id:req.params.id,tenantId}):new HospitalityDeposit(payload);if(!row)return res.status(404).json({success:false,message:"Deposit not found."});Object.assign(row,payload);row.paidAmount=Number(row.paidAmount||0);row.status=row.paidAmount<=0?"pending":row.paidAmount>=row.amount?"paid":"partial";await row.save();await audit(req,req.params.id?"update":"create","HospitalityDeposit",row._id);res.status(req.params.id?200:201).json({success:true,data:row});}catch(e){next(e);}};

export const transferDispatch=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),from=asDate(req.query.from)||new Date(new Date().setHours(0,0,0,0)),to=asDate(req.query.to)||new Date(from.getTime()+86400000),filter={tenantId,pickupDateTime:{$gte:from,$lt:to},status:{$nin:["cancelled","no_show"]}};if(req.query.status)filter.status=req.query.status;const rows=await AirportTransferBooking.find(filter).populate("assignedVehicle","registrationNumber registration type model").populate("assignedDriver","name firstName lastName phone").populate("transfer","name airportName airportCode").sort({pickupDateTime:1}).lean();res.json({success:true,data:rows});}catch(e){next(e);}};

export const assignTransfer=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),b=await AirportTransferBooking.findOne({_id:req.params.id,tenantId});if(!b)return res.status(404).json({success:false,message:"Transfer booking not found."});if(req.body.vehicleId){const v=await Vehicle.findOne({_id:req.body.vehicleId,tenantId});if(!v)return res.status(404).json({success:false,message:"Vehicle not found."});b.assignedVehicle=v._id;}if(req.body.driverId){const d=await User.findOne({_id:req.body.driverId,tenantId});if(!d)return res.status(404).json({success:false,message:"Driver not found."});b.assignedDriver=d._id;}if(req.body.status)b.status=req.body.status;if(req.body.notes!==undefined)b.notes=clean(req.body.notes);b.updatedBy=req.user?._id||null;await b.save();await audit(req,"dispatch","AirportTransferBooking",b._id,{vehicleId:req.body.vehicleId,driverId:req.body.driverId,status:req.body.status});res.json({success:true,data:b});}catch(e){next(e);}};

export const updateTransferStatus=async(req,res,next)=>{try{const allowed=["pending","confirmed","assigned","driver_en_route","picked_up","completed","cancelled","no_show"];const b=await AirportTransferBooking.findOne({_id:req.params.id,tenantId:tenantIdOf(req)});if(!b)return res.status(404).json({success:false,message:"Transfer booking not found."});if(!allowed.includes(req.body.status))return res.status(400).json({success:false,message:"Invalid transfer status."});b.status=req.body.status;if(req.body.delayMinutes!==undefined)b.notes=[b.notes,`Delay: ${Number(req.body.delayMinutes)||0} minutes`].filter(Boolean).join(" | ");b.updatedBy=req.user?._id||null;await b.save();await audit(req,"status","AirportTransferBooking",b._id,{status:b.status});res.json({success:true,data:b});}catch(e){next(e);}};

export const paymentReconciliation=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),from=asDate(req.query.from)||new Date(Date.now()-7*86400000),to=asDate(req.query.to)||new Date(),filter={tenantId,createdAt:{$gte:from,$lt:to}};if(req.query.provider)filter.provider=req.query.provider;const rows=await Payment.find(filter).sort({createdAt:-1}).limit(500).lean();const mpesa=rows.filter(p=>String(p.provider).toUpperCase()==="MPESA"||String(p.paymentMethod).toUpperCase().includes("MPESA"));const summary=mpesa.reduce((a,p)=>{const k=p.status||"pending";a[k]=(a[k]||0)+Number(p.amount||0);return a;},{});res.json({success:true,data:{rows:mpesa,summary,matched:mpesa.filter(p=>p.transactionReference||p.mpesaReceiptNumber||p.transactionId).length,unmatched:mpesa.filter(p=>!p.transactionReference&&!p.mpesaReceiptNumber&&!p.transactionId).length}});}catch(e){next(e);}};

export const hospitalityDashboard=async(req,res,next)=>{try{const tenantId=tenantIdOf(req),now=new Date(),tomorrow=new Date(now.getTime()+86400000);const [hotels,rooms,todayTransfers,todayBookings,paid]=await Promise.all([Hotel.countDocuments({tenantId,status:"active"}),HotelRoomType.find({tenantId,status:"active"}).lean(),AirportTransferBooking.countDocuments({tenantId,pickupDateTime:{$gte:new Date(new Date().setHours(0,0,0,0)),$lt:tomorrow},status:{$nin:["cancelled","no_show"]}}),HotelBooking.countDocuments({tenantId,checkIn:{$gte:new Date(new Date().setHours(0,0,0,0)),$lt:tomorrow},status:{$nin:["cancelled","no_show"]}}),Payment.aggregate([{$match:{tenantId,status:"completed",createdAt:{$gte:new Date(now.getTime()-30*86400000)}}},{$group:{_id:null,total:{$sum:"$amount"}}}])]);const inventory=rooms.reduce((s,r)=>s+Number(r.totalRooms||0),0);res.json({success:true,data:{hotels,roomTypes:rooms.length,inventory,todayTransfers,todayBookings,last30DaysPaid:Number(paid[0]?.total||0)}});}catch(e){next(e);}};

export const listDrivers=async(req,res,next)=>{try{const tenantId=tenantIdOf(req);const rows=await User.find({tenantId,$or:[{role:"driver"},{role:"Driver"},{roles:"driver"},{roles:"Driver"}] }).select("name firstName lastName phone email role roles").sort({name:1,firstName:1}).lean();res.json({success:true,data:rows});}catch(e){next(e);}};
export const listVehicles=async(req,res,next)=>{try{const rows=await Vehicle.find({tenantId:tenantIdOf(req)}).sort({registration:1,registrationNumber:1}).lean();res.json({success:true,data:rows});}catch(e){next(e);}};

export const ensureOpsAccess=(req,res,next)=>staff(req)?next():res.status(403).json({success:false,message:"Operations access required."});
